// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package divememoriessqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDiveMemoryMedia = `-- name: AddDiveMemoryMedia :one
INSERT INTO dive_memory_media (
  memory_id,
  media_id,
  sort_order
)
VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (memory_id, media_id) DO UPDATE
SET sort_order = EXCLUDED.sort_order
RETURNING
  id,
  memory_id,
  media_id,
  sort_order,
  created_at
`

type AddDiveMemoryMediaParams struct {
	MemoryID  pgtype.UUID `db:"memory_id" json:"memory_id"`
	MediaID   pgtype.UUID `db:"media_id" json:"media_id"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
}

func (q *Queries) AddDiveMemoryMedia(ctx context.Context, arg AddDiveMemoryMediaParams) (DiveMemoryMedium, error) {
	row := q.db.QueryRow(ctx, addDiveMemoryMedia, arg.MemoryID, arg.MediaID, arg.SortOrder)
	var i DiveMemoryMedium
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.MediaID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createDiveMemory = `-- name: CreateDiveMemory :one
INSERT INTO dive_memories (
  author_user_id,
  dive_site_id,
  title,
  body,
  visibility,
  occurred_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING
  id,
  author_user_id,
  dive_site_id,
  title,
  body,
  visibility,
  occurred_at,
  deleted_at,
  created_at,
  updated_at
`

type CreateDiveMemoryParams struct {
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	DiveSiteID   pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Title        string             `db:"title" json:"title"`
	Body         string             `db:"body" json:"body"`
	Visibility   string             `db:"visibility" json:"visibility"`
	OccurredAt   pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateDiveMemory(ctx context.Context, arg CreateDiveMemoryParams) (DiveMemory, error) {
	row := q.db.QueryRow(ctx, createDiveMemory,
		arg.AuthorUserID,
		arg.DiveSiteID,
		arg.Title,
		arg.Body,
		arg.Visibility,
		arg.OccurredAt,
	)
	var i DiveMemory
	err := row.Scan(
		&i.ID,
		&i.AuthorUserID,
		&i.DiveSiteID,
		&i.Title,
		&i.Body,
		&i.Visibility,
		&i.OccurredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDiveMemoryMedia = `-- name: DeleteDiveMemoryMedia :execrows
DELETE FROM dive_memory_media
WHERE memory_id = $1
  AND EXISTS (
    SELECT 1
    FROM dive_memories dm
    WHERE dm.id = dive_memory_media.memory_id
      AND dm.author_user_id = $2
      AND dm.deleted_at IS NULL
  )
`

type DeleteDiveMemoryMediaParams struct {
	MemoryID     pgtype.UUID `db:"memory_id" json:"memory_id"`
	AuthorUserID pgtype.UUID `db:"author_user_id" json:"author_user_id"`
}

func (q *Queries) DeleteDiveMemoryMedia(ctx context.Context, arg DeleteDiveMemoryMediaParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDiveMemoryMedia, arg.MemoryID, arg.AuthorUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDiveMemoryTag = `-- name: DeleteDiveMemoryTag :execrows
DELETE FROM dive_memory_tagged_users
WHERE memory_id = $1
  AND tagged_user_id = $2
`

type DeleteDiveMemoryTagParams struct {
	MemoryID     pgtype.UUID `db:"memory_id" json:"memory_id"`
	TaggedUserID pgtype.UUID `db:"tagged_user_id" json:"tagged_user_id"`
}

func (q *Queries) DeleteDiveMemoryTag(ctx context.Context, arg DeleteDiveMemoryTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDiveMemoryTag, arg.MemoryID, arg.TaggedUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDiveMemoryByID = `-- name: GetDiveMemoryByID :one
SELECT
  id,
  author_user_id,
  dive_site_id,
  title,
  body,
  visibility,
  occurred_at,
  deleted_at,
  created_at,
  updated_at
FROM dive_memories
WHERE id = $1
`

func (q *Queries) GetDiveMemoryByID(ctx context.Context, id pgtype.UUID) (DiveMemory, error) {
	row := q.db.QueryRow(ctx, getDiveMemoryByID, id)
	var i DiveMemory
	err := row.Scan(
		&i.ID,
		&i.AuthorUserID,
		&i.DiveSiteID,
		&i.Title,
		&i.Body,
		&i.Visibility,
		&i.OccurredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemoryOwnerByUsername = `-- name: GetMemoryOwnerByUsername :one
SELECT
  u.id,
  COALESCE(NULLIF($1, '')::uuid = u.id, false)::boolean AS viewer_is_self,
  COALESCE((
    SELECT EXISTS (
      SELECT 1
      FROM saved_users su
      WHERE su.viewer_app_user_id = NULLIF($1, '')::uuid
        AND su.saved_app_user_id = u.id
    )
  ), false)::boolean AS viewer_follows,
  COALESCE((
    SELECT EXISTS (
      SELECT 1
      FROM user_blocks ub
      WHERE (
          ub.blocker_app_user_id = NULLIF($1, '')::uuid
          AND ub.blocked_app_user_id = u.id
        )
        OR (
          ub.blocker_app_user_id = u.id
          AND ub.blocked_app_user_id = NULLIF($1, '')::uuid
        )
    )
  ), false)::boolean AS blocked
FROM users u
WHERE lower(u.username) = lower($2)
  AND u.account_status = 'active'
LIMIT 1
`

type GetMemoryOwnerByUsernameParams struct {
	ViewerUserID interface{} `db:"viewer_user_id" json:"viewer_user_id"`
	Username     string      `db:"username" json:"username"`
}

type GetMemoryOwnerByUsernameRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	ViewerIsSelf  bool        `db:"viewer_is_self" json:"viewer_is_self"`
	ViewerFollows bool        `db:"viewer_follows" json:"viewer_follows"`
	Blocked       bool        `db:"blocked" json:"blocked"`
}

func (q *Queries) GetMemoryOwnerByUsername(ctx context.Context, arg GetMemoryOwnerByUsernameParams) (GetMemoryOwnerByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getMemoryOwnerByUsername, arg.ViewerUserID, arg.Username)
	var i GetMemoryOwnerByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.ViewerIsSelf,
		&i.ViewerFollows,
		&i.Blocked,
	)
	return i, err
}

const hasBlockBetweenUsers = `-- name: HasBlockBetweenUsers :one
SELECT EXISTS (
  SELECT 1
  FROM user_blocks ub
  WHERE (
      ub.blocker_app_user_id = $1
      AND ub.blocked_app_user_id = $2
    )
    OR (
      ub.blocker_app_user_id = $2
      AND ub.blocked_app_user_id = $1
    )
)::boolean
`

type HasBlockBetweenUsersParams struct {
	BlockerAppUserID pgtype.UUID `db:"blocker_app_user_id" json:"blocker_app_user_id"`
	BlockedAppUserID pgtype.UUID `db:"blocked_app_user_id" json:"blocked_app_user_id"`
}

func (q *Queries) HasBlockBetweenUsers(ctx context.Context, arg HasBlockBetweenUsersParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasBlockBetweenUsers, arg.BlockerAppUserID, arg.BlockedAppUserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listDiveMemoriesForOwnedMapSite = `-- name: ListDiveMemoriesForOwnedMapSite :many
SELECT
  dm.id,
  dm.author_user_id,
  dm.dive_site_id,
  dm.title,
  dm.body,
  dm.visibility,
  dm.occurred_at,
  dm.deleted_at,
  dm.created_at,
  dm.updated_at
FROM dive_memories dm
WHERE dm.author_user_id = $1
  AND dm.dive_site_id = $2
  AND dm.deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM user_dive_sites uds
    WHERE uds.user_id = dm.author_user_id
      AND uds.dive_site_id = dm.dive_site_id
  )
ORDER BY dm.occurred_at DESC, dm.id DESC
LIMIT $3
`

type ListDiveMemoriesForOwnedMapSiteParams struct {
	AuthorUserID pgtype.UUID `db:"author_user_id" json:"author_user_id"`
	DiveSiteID   pgtype.UUID `db:"dive_site_id" json:"dive_site_id"`
	ResultLimit  int32       `db:"result_limit" json:"result_limit"`
}

func (q *Queries) ListDiveMemoriesForOwnedMapSite(ctx context.Context, arg ListDiveMemoriesForOwnedMapSiteParams) ([]DiveMemory, error) {
	rows, err := q.db.Query(ctx, listDiveMemoriesForOwnedMapSite, arg.AuthorUserID, arg.DiveSiteID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiveMemory{}
	for rows.Next() {
		var i DiveMemory
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUserID,
			&i.DiveSiteID,
			&i.Title,
			&i.Body,
			&i.Visibility,
			&i.OccurredAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiveMemoryMedia = `-- name: ListDiveMemoryMedia :many
SELECT
  id,
  memory_id,
  media_id,
  sort_order,
  created_at
FROM dive_memory_media
WHERE memory_id = $1
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListDiveMemoryMedia(ctx context.Context, memoryID pgtype.UUID) ([]DiveMemoryMedium, error) {
	rows, err := q.db.Query(ctx, listDiveMemoryMedia, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiveMemoryMedium{}
	for rows.Next() {
		var i DiveMemoryMedium
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.MediaID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiveMemoryTags = `-- name: ListDiveMemoryTags :many
SELECT
  id,
  memory_id,
  tagged_user_id,
  status,
  created_at,
  updated_at
FROM dive_memory_tagged_users
WHERE memory_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListDiveMemoryTags(ctx context.Context, memoryID pgtype.UUID) ([]DiveMemoryTaggedUser, error) {
	rows, err := q.db.Query(ctx, listDiveMemoryTags, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiveMemoryTaggedUser{}
	for rows.Next() {
		var i DiveMemoryTaggedUser
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.TaggedUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryTagsForTaggedUser = `-- name: ListMemoryTagsForTaggedUser :many
SELECT
  dmtu.id,
  dmtu.memory_id,
  dmtu.tagged_user_id,
  dmtu.status,
  dmtu.created_at,
  dmtu.updated_at
FROM dive_memory_tagged_users dmtu
JOIN dive_memories dm ON dm.id = dmtu.memory_id
WHERE dmtu.tagged_user_id = $1
  AND dm.deleted_at IS NULL
  AND (
    $2 = ''
    OR dmtu.status = $2
  )
  AND NOT EXISTS (
    SELECT 1
    FROM user_blocks ub
    WHERE (
        ub.blocker_app_user_id = dmtu.tagged_user_id
        AND ub.blocked_app_user_id = dm.author_user_id
      )
      OR (
        ub.blocker_app_user_id = dm.author_user_id
        AND ub.blocked_app_user_id = dmtu.tagged_user_id
      )
  )
ORDER BY dmtu.created_at DESC, dmtu.id DESC
LIMIT $3
`

type ListMemoryTagsForTaggedUserParams struct {
	TaggedUserID pgtype.UUID `db:"tagged_user_id" json:"tagged_user_id"`
	StatusFilter interface{} `db:"status_filter" json:"status_filter"`
	ResultLimit  int32       `db:"result_limit" json:"result_limit"`
}

func (q *Queries) ListMemoryTagsForTaggedUser(ctx context.Context, arg ListMemoryTagsForTaggedUserParams) ([]DiveMemoryTaggedUser, error) {
	rows, err := q.db.Query(ctx, listMemoryTagsForTaggedUser, arg.TaggedUserID, arg.StatusFilter, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiveMemoryTaggedUser{}
	for rows.Next() {
		var i DiveMemoryTaggedUser
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.TaggedUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnDiveMemories = `-- name: ListOwnDiveMemories :many
SELECT
  id,
  author_user_id,
  dive_site_id,
  title,
  body,
  visibility,
  occurred_at,
  deleted_at,
  created_at,
  updated_at
FROM dive_memories
WHERE author_user_id = $1
  AND deleted_at IS NULL
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListOwnDiveMemoriesParams struct {
	AuthorUserID pgtype.UUID `db:"author_user_id" json:"author_user_id"`
	ResultLimit  int32       `db:"result_limit" json:"result_limit"`
}

func (q *Queries) ListOwnDiveMemories(ctx context.Context, arg ListOwnDiveMemoriesParams) ([]DiveMemory, error) {
	rows, err := q.db.Query(ctx, listOwnDiveMemories, arg.AuthorUserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiveMemory{}
	for rows.Next() {
		var i DiveMemory
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUserID,
			&i.DiveSiteID,
			&i.Title,
			&i.Body,
			&i.Visibility,
			&i.OccurredAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleDiveMemoriesForProfile = `-- name: ListVisibleDiveMemoriesForProfile :many
SELECT
  dm.id,
  dm.author_user_id,
  dm.dive_site_id,
  dm.title,
  dm.body,
  dm.visibility,
  dm.occurred_at,
  dm.deleted_at,
  dm.created_at,
  dm.updated_at
FROM dive_memories dm
WHERE dm.author_user_id = $1
  AND dm.deleted_at IS NULL
  AND (
    dm.visibility = 'public'
    OR ($2::boolean AND dm.visibility IN ('private', 'followers', 'tagged'))
    OR (($2::boolean OR $3::boolean) AND dm.visibility = 'followers')
    OR (
      dm.visibility = 'tagged'
      AND EXISTS (
        SELECT 1
        FROM dive_memory_tagged_users dmtu
        WHERE dmtu.memory_id = dm.id
          AND dmtu.tagged_user_id = NULLIF($4, '')::uuid
          AND dmtu.status = 'accepted'
      )
    )
  )
ORDER BY dm.occurred_at DESC, dm.id DESC
LIMIT $5
`

type ListVisibleDiveMemoriesForProfileParams struct {
	TargetUserID  pgtype.UUID `db:"target_user_id" json:"target_user_id"`
	ViewerIsSelf  bool        `db:"viewer_is_self" json:"viewer_is_self"`
	ViewerFollows bool        `db:"viewer_follows" json:"viewer_follows"`
	ViewerUserID  interface{} `db:"viewer_user_id" json:"viewer_user_id"`
	ResultLimit   int32       `db:"result_limit" json:"result_limit"`
}

func (q *Queries) ListVisibleDiveMemoriesForProfile(ctx context.Context, arg ListVisibleDiveMemoriesForProfileParams) ([]DiveMemory, error) {
	rows, err := q.db.Query(ctx, listVisibleDiveMemoriesForProfile,
		arg.TargetUserID,
		arg.ViewerIsSelf,
		arg.ViewerFollows,
		arg.ViewerUserID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiveMemory{}
	for rows.Next() {
		var i DiveMemory
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUserID,
			&i.DiveSiteID,
			&i.Title,
			&i.Body,
			&i.Visibility,
			&i.OccurredAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDiveMemory = `-- name: SoftDeleteDiveMemory :execrows
UPDATE dive_memories
SET
  deleted_at = NOW(),
  updated_at = NOW()
WHERE id = $1
  AND author_user_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteDiveMemoryParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	AuthorUserID pgtype.UUID `db:"author_user_id" json:"author_user_id"`
}

func (q *Queries) SoftDeleteDiveMemory(ctx context.Context, arg SoftDeleteDiveMemoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDiveMemory, arg.ID, arg.AuthorUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDiveMemory = `-- name: UpdateDiveMemory :one
UPDATE dive_memories
SET
  dive_site_id = $3,
  title = $4,
  body = $5,
  visibility = $6,
  occurred_at = $7,
  updated_at = NOW()
WHERE id = $1
  AND author_user_id = $2
  AND deleted_at IS NULL
RETURNING
  id,
  author_user_id,
  dive_site_id,
  title,
  body,
  visibility,
  occurred_at,
  deleted_at,
  created_at,
  updated_at
`

type UpdateDiveMemoryParams struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	DiveSiteID   pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Title        string             `db:"title" json:"title"`
	Body         string             `db:"body" json:"body"`
	Visibility   string             `db:"visibility" json:"visibility"`
	OccurredAt   pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) UpdateDiveMemory(ctx context.Context, arg UpdateDiveMemoryParams) (DiveMemory, error) {
	row := q.db.QueryRow(ctx, updateDiveMemory,
		arg.ID,
		arg.AuthorUserID,
		arg.DiveSiteID,
		arg.Title,
		arg.Body,
		arg.Visibility,
		arg.OccurredAt,
	)
	var i DiveMemory
	err := row.Scan(
		&i.ID,
		&i.AuthorUserID,
		&i.DiveSiteID,
		&i.Title,
		&i.Body,
		&i.Visibility,
		&i.OccurredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDiveMemoryTagStatus = `-- name: UpdateDiveMemoryTagStatus :one
UPDATE dive_memory_tagged_users
SET
  status = $3,
  updated_at = NOW()
WHERE memory_id = $1
  AND tagged_user_id = $2
RETURNING
  id,
  memory_id,
  tagged_user_id,
  status,
  created_at,
  updated_at
`

type UpdateDiveMemoryTagStatusParams struct {
	MemoryID     pgtype.UUID `db:"memory_id" json:"memory_id"`
	TaggedUserID pgtype.UUID `db:"tagged_user_id" json:"tagged_user_id"`
	Status       string      `db:"status" json:"status"`
}

func (q *Queries) UpdateDiveMemoryTagStatus(ctx context.Context, arg UpdateDiveMemoryTagStatusParams) (DiveMemoryTaggedUser, error) {
	row := q.db.QueryRow(ctx, updateDiveMemoryTagStatus, arg.MemoryID, arg.TaggedUserID, arg.Status)
	var i DiveMemoryTaggedUser
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.TaggedUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDiveMemoryTag = `-- name: UpsertDiveMemoryTag :one
INSERT INTO dive_memory_tagged_users (
  memory_id,
  tagged_user_id,
  status
)
VALUES (
  $1,
  $2,
  'pending'
)
ON CONFLICT (memory_id, tagged_user_id) DO UPDATE
SET
  status = CASE
    WHEN dive_memory_tagged_users.status = 'hidden' THEN dive_memory_tagged_users.status
    ELSE 'pending'
  END,
  updated_at = NOW()
RETURNING
  id,
  memory_id,
  tagged_user_id,
  status,
  created_at,
  updated_at
`

type UpsertDiveMemoryTagParams struct {
	MemoryID     pgtype.UUID `db:"memory_id" json:"memory_id"`
	TaggedUserID pgtype.UUID `db:"tagged_user_id" json:"tagged_user_id"`
}

func (q *Queries) UpsertDiveMemoryTag(ctx context.Context, arg UpsertDiveMemoryTagParams) (DiveMemoryTaggedUser, error) {
	row := q.db.QueryRow(ctx, upsertDiveMemoryTag, arg.MemoryID, arg.TaggedUserID)
	var i DiveMemoryTaggedUser
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.TaggedUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
