import { normalizeUsername } from "@/lib/routes";

export const reservedSlugs = [
  "admin",
  "api",
  "auth",
  "about-us",
  "about-us.md",
  "awareness",
  "buddies",
  "buddy",
  "chika",
  "collaboration",
  "competitive-records",
  "events",
  "explore",
  "features",
  "features.md",
  "freediving",
  "freediving.md",
  "favicon.ico",
  "groups",
  "guides",
  "guides.md",
  "icon",
  "manifest.json",
  "manifest.webmanifest",
  "llms.txt",
  "marketplace",
  "media",
  "messages",
  "moderation",
  "notifications",
  "onboarding",
  "opengraph-image",
  "profile",
  "robots.txt",
  "safety",
  "saved",
  "services",
  "settings",
  "sign-in",
  "sign-up",
  "sitemap-index.xml",
  "sitemap.xml",
  "twitter-image",
  "training-logs",
].sort();

const reservedSlugSet = new Set(reservedSlugs);

export const isReservedProfileSlug = (slug: string): boolean =>
  reservedSlugSet.has(normalizeUsername(slug));
