services:
  api:
    container_name: api
    build: ./api
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/usr/src/app # Sync project files (hot reload)
      - /usr/src/app/node_modules # Prevent overwriting node_modules (IMPORTANT)
    restart: unless-stopped

  app:
    container_name: app
    build: ./app
    ports:
      - "3000:3000"
    # env_file:
    #   - ./app/.env
    volumes:
      - ./app:/usr/src/app # Sync local files to container
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    depends_on:
      - api
      - database
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://fphbuddies:fphbuddiespw@database:5432/freedivingph

  database:
    container_name: database
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: fphbuddies
      POSTGRES_PASSWORD: fphbuddiespw
      POSTGRES_DB: freedivingph
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
