// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package reportsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityItem struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Type            string             `db:"type" json:"type"`
	SourceModule    string             `db:"source_module" json:"source_module"`
	SourceType      string             `db:"source_type" json:"source_type"`
	SourceID        pgtype.UUID        `db:"source_id" json:"source_id"`
	ActorUserID     pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	TargetType      string             `db:"target_type" json:"target_type"`
	TargetID        pgtype.UUID        `db:"target_id" json:"target_id"`
	Visibility      string             `db:"visibility" json:"visibility"`
	State           string             `db:"state" json:"state"`
	Area            *string            `db:"area" json:"area"`
	DiveSiteID      pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	GroupID         pgtype.UUID        `db:"group_id" json:"group_id"`
	EventID         pgtype.UUID        `db:"event_id" json:"event_id"`
	OccurredAt      pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	SourceCreatedAt pgtype.Timestamptz `db:"source_created_at" json:"source_created_at"`
	Title           *string            `db:"title" json:"title"`
	Body            *string            `db:"body" json:"body"`
	Media           []byte             `db:"media" json:"media"`
	Stats           []byte             `db:"stats" json:"stats"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type BadgeTemplate struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Slug         string             `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	Category     string             `db:"category" json:"category"`
	ValueType    string             `db:"value_type" json:"value_type"`
	Unit         *string            `db:"unit" json:"unit"`
	Icon         *string            `db:"icon" json:"icon"`
	Description  *string            `db:"description" json:"description"`
	IsSystem     bool               `db:"is_system" json:"is_system"`
	DisplayOrder int32              `db:"display_order" json:"display_order"`
	Rarity       string             `db:"rarity" json:"rarity"`
	IsPublic     bool               `db:"is_public" json:"is_public"`
	IsRepeatable bool               `db:"is_repeatable" json:"is_repeatable"`
	SourceModule string             `db:"source_module" json:"source_module"`
	MetadataJson []byte             `db:"metadata_json" json:"metadata_json"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Block struct {
	BlockerID pgtype.UUID        `db:"blocker_id" json:"blocker_id"`
	BlockedID pgtype.UUID        `db:"blocked_id" json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Buddy struct {
	AppUserIDA pgtype.UUID        `db:"app_user_id_a" json:"app_user_id_a"`
	AppUserIDB pgtype.UUID        `db:"app_user_id_b" json:"app_user_id_b"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BuddyIntent struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	AuthorAppUserID pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	DiveSiteID      pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Area            string             `db:"area" json:"area"`
	IntentType      string             `db:"intent_type" json:"intent_type"`
	TimeWindow      string             `db:"time_window" json:"time_window"`
	DateStart       pgtype.Date        `db:"date_start" json:"date_start"`
	DateEnd         pgtype.Date        `db:"date_end" json:"date_end"`
	Note            *string            `db:"note" json:"note"`
	Visibility      string             `db:"visibility" json:"visibility"`
	State           string             `db:"state" json:"state"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type BuddyRelationship struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	BuddyID   pgtype.UUID        `db:"buddy_id" json:"buddy_id"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type BuddyRequest struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	RequesterAppUserID pgtype.UUID        `db:"requester_app_user_id" json:"requester_app_user_id"`
	TargetAppUserID    pgtype.UUID        `db:"target_app_user_id" json:"target_app_user_id"`
	Status             string             `db:"status" json:"status"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ChikaCategory struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Slug         string             `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	Pseudonymous bool               `db:"pseudonymous" json:"pseudonymous"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ChikaComment struct {
	ID           int64              `db:"id" json:"id"`
	ThreadID     pgtype.UUID        `db:"thread_id" json:"thread_id"`
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	Pseudonym    string             `db:"pseudonym" json:"pseudonym"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	HiddenAt     pgtype.Timestamptz `db:"hidden_at" json:"hidden_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ChikaCommentReaction struct {
	CommentID    int64              `db:"comment_id" json:"comment_id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	ReactionType string             `db:"reaction_type" json:"reaction_type"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ChikaPost struct {
	ID           int64              `db:"id" json:"id"`
	ThreadID     pgtype.UUID        `db:"thread_id" json:"thread_id"`
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	Pseudonym    string             `db:"pseudonym" json:"pseudonym"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ChikaThread struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Slug            string             `db:"slug" json:"slug"`
	Title           string             `db:"title" json:"title"`
	Mode            string             `db:"mode" json:"mode"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	CreatedByUserID pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	HiddenAt        pgtype.Timestamptz `db:"hidden_at" json:"hidden_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ChikaThreadAlias struct {
	ThreadID  pgtype.UUID        `db:"thread_id" json:"thread_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Pseudonym string             `db:"pseudonym" json:"pseudonym"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ChikaThreadReaction struct {
	ThreadID     pgtype.UUID        `db:"thread_id" json:"thread_id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	ReactionType string             `db:"reaction_type" json:"reaction_type"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Conversation struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Kind            string             `db:"kind" json:"kind"`
	DmPairKey       string             `db:"dm_pair_key" json:"dm_pair_key"`
	InitiatorUserID pgtype.UUID        `db:"initiator_user_id" json:"initiator_user_id"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ConversationParticipant struct {
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	LastReadAt     pgtype.Timestamptz `db:"last_read_at" json:"last_read_at"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type Course struct {
	ID                         pgtype.UUID        `db:"id" json:"id"`
	SchoolID                   pgtype.UUID        `db:"school_id" json:"school_id"`
	Slug                       string             `db:"slug" json:"slug"`
	Title                      string             `db:"title" json:"title"`
	ShortDescription           string             `db:"short_description" json:"short_description"`
	DescriptionMarkdown        string             `db:"description_markdown" json:"description_markdown"`
	CourseType                 string             `db:"course_type" json:"course_type"`
	Level                      *string            `db:"level" json:"level"`
	DurationLabel              *string            `db:"duration_label" json:"duration_label"`
	PriceAmount                pgtype.Numeric     `db:"price_amount" json:"price_amount"`
	Currency                   string             `db:"currency" json:"currency"`
	PaymentRequired            bool               `db:"payment_required" json:"payment_required"`
	ApprovalRequired           bool               `db:"approval_required" json:"approval_required"`
	AllowSessionBooking        bool               `db:"allow_session_booking" json:"allow_session_booking"`
	AllowPreferredDateRequest  bool               `db:"allow_preferred_date_request" json:"allow_preferred_date_request"`
	LocationMode               string             `db:"location_mode" json:"location_mode"`
	LocationLabel              *string            `db:"location_label" json:"location_label"`
	LocationNote               *string            `db:"location_note" json:"location_note"`
	FormattedAddress           *string            `db:"formatted_address" json:"formatted_address"`
	RegionCode                 *string            `db:"region_code" json:"region_code"`
	RegionName                 *string            `db:"region_name" json:"region_name"`
	ProvinceCode               *string            `db:"province_code" json:"province_code"`
	ProvinceName               *string            `db:"province_name" json:"province_name"`
	CityCode                   *string            `db:"city_code" json:"city_code"`
	CityName                   *string            `db:"city_name" json:"city_name"`
	BarangayCode               *string            `db:"barangay_code" json:"barangay_code"`
	BarangayName               *string            `db:"barangay_name" json:"barangay_name"`
	LocationSource             string             `db:"location_source" json:"location_source"`
	DiveSiteID                 pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	IncludedMarkdown           *string            `db:"included_markdown" json:"included_markdown"`
	PrerequisitesMarkdown      *string            `db:"prerequisites_markdown" json:"prerequisites_markdown"`
	EquipmentMarkdown          *string            `db:"equipment_markdown" json:"equipment_markdown"`
	CancellationPolicyMarkdown *string            `db:"cancellation_policy_markdown" json:"cancellation_policy_markdown"`
	AvailabilityNote           *string            `db:"availability_note" json:"availability_note"`
	Status                     string             `db:"status" json:"status"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CourseBookingPayment struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	BookingID       pgtype.UUID        `db:"booking_id" json:"booking_id"`
	CourseID        pgtype.UUID        `db:"course_id" json:"course_id"`
	SchoolID        pgtype.UUID        `db:"school_id" json:"school_id"`
	StudentUserID   pgtype.UUID        `db:"student_user_id" json:"student_user_id"`
	PaymentMethodID pgtype.UUID        `db:"payment_method_id" json:"payment_method_id"`
	Amount          pgtype.Numeric     `db:"amount" json:"amount"`
	Currency        string             `db:"currency" json:"currency"`
	ProofMediaID    pgtype.UUID        `db:"proof_media_id" json:"proof_media_id"`
	ReferenceNumber *string            `db:"reference_number" json:"reference_number"`
	Status          string             `db:"status" json:"status"`
	ReviewedBy      pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ReviewNotes     *string            `db:"review_notes" json:"review_notes"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CourseBookingRequest struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	CourseID           pgtype.UUID        `db:"course_id" json:"course_id"`
	SchoolID           pgtype.UUID        `db:"school_id" json:"school_id"`
	SessionID          pgtype.UUID        `db:"session_id" json:"session_id"`
	StudentUserID      pgtype.UUID        `db:"student_user_id" json:"student_user_id"`
	StudentName        *string            `db:"student_name" json:"student_name"`
	StudentEmail       *string            `db:"student_email" json:"student_email"`
	StudentPhone       *string            `db:"student_phone" json:"student_phone"`
	BookingMode        string             `db:"booking_mode" json:"booking_mode"`
	PreferredDate      pgtype.Date        `db:"preferred_date" json:"preferred_date"`
	AlternateDate      pgtype.Date        `db:"alternate_date" json:"alternate_date"`
	Status             string             `db:"status" json:"status"`
	StudentNote        *string            `db:"student_note" json:"student_note"`
	ExperienceLevel    *string            `db:"experience_level" json:"experience_level"`
	CertificationLevel *string            `db:"certification_level" json:"certification_level"`
	EquipmentNeeds     *string            `db:"equipment_needs" json:"equipment_needs"`
	AnswersJson        []byte             `db:"answers_json" json:"answers_json"`
	AdminNotes         *string            `db:"admin_notes" json:"admin_notes"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ReviewedAt         pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ReviewedBy         pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ScheduledAt        pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	CancelledAt        pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CompletedAt        pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CoursePaymentMethod struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	CourseID      pgtype.UUID        `db:"course_id" json:"course_id"`
	Type          string             `db:"type" json:"type"`
	Name          string             `db:"name" json:"name"`
	Instructions  *string            `db:"instructions" json:"instructions"`
	QrMediaID     pgtype.UUID        `db:"qr_media_id" json:"qr_media_id"`
	BankName      *string            `db:"bank_name" json:"bank_name"`
	AccountName   *string            `db:"account_name" json:"account_name"`
	AccountNumber *string            `db:"account_number" json:"account_number"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CourseSession struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SchoolID         pgtype.UUID        `db:"school_id" json:"school_id"`
	CourseID         pgtype.UUID        `db:"course_id" json:"course_id"`
	Slug             string             `db:"slug" json:"slug"`
	Title            string             `db:"title" json:"title"`
	StartsAt         pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt           pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	Timezone         string             `db:"timezone" json:"timezone"`
	LocationMode     string             `db:"location_mode" json:"location_mode"`
	LocationLabel    *string            `db:"location_label" json:"location_label"`
	LocationNote     *string            `db:"location_note" json:"location_note"`
	FormattedAddress *string            `db:"formatted_address" json:"formatted_address"`
	RegionCode       *string            `db:"region_code" json:"region_code"`
	RegionName       *string            `db:"region_name" json:"region_name"`
	ProvinceCode     *string            `db:"province_code" json:"province_code"`
	ProvinceName     *string            `db:"province_name" json:"province_name"`
	CityCode         *string            `db:"city_code" json:"city_code"`
	CityName         *string            `db:"city_name" json:"city_name"`
	BarangayCode     *string            `db:"barangay_code" json:"barangay_code"`
	BarangayName     *string            `db:"barangay_name" json:"barangay_name"`
	LocationSource   string             `db:"location_source" json:"location_source"`
	DiveSiteID       pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	InstructorUserID pgtype.UUID        `db:"instructor_user_id" json:"instructor_user_id"`
	Capacity         *int32             `db:"capacity" json:"capacity"`
	Status           string             `db:"status" json:"status"`
	NotesMarkdown    *string            `db:"notes_markdown" json:"notes_markdown"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CancelledAt      pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type DevicePushToken struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	ExpoPushToken string             `db:"expo_push_token" json:"expo_push_token"`
	Platform      string             `db:"platform" json:"platform"`
	DeviceID      *string            `db:"device_id" json:"device_id"`
	DeviceName    *string            `db:"device_name" json:"device_name"`
	AppVersion    *string            `db:"app_version" json:"app_version"`
	Enabled       bool               `db:"enabled" json:"enabled"`
	LastSeenAt    pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DivePresence struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	DiveSiteID     pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	PresenceType   string             `db:"presence_type" json:"presence_type"`
	StartAt        pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt          pgtype.Timestamptz `db:"end_at" json:"end_at"`
	Visibility     string             `db:"visibility" json:"visibility"`
	ContactEnabled bool               `db:"contact_enabled" json:"contact_enabled"`
	Note           *string            `db:"note" json:"note"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DiveSite struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	Name                 string             `db:"name" json:"name"`
	Slug                 string             `db:"slug" json:"slug"`
	Area                 string             `db:"area" json:"area"`
	Latitude             *float64           `db:"latitude" json:"latitude"`
	Longitude            *float64           `db:"longitude" json:"longitude"`
	Description          *string            `db:"description" json:"description"`
	EntryDifficulty      string             `db:"entry_difficulty" json:"entry_difficulty"`
	DepthMinM            pgtype.Numeric     `db:"depth_min_m" json:"depth_min_m"`
	DepthMaxM            pgtype.Numeric     `db:"depth_max_m" json:"depth_max_m"`
	Hazards              []string           `db:"hazards" json:"hazards"`
	BestSeason           *string            `db:"best_season" json:"best_season"`
	TypicalConditions    *string            `db:"typical_conditions" json:"typical_conditions"`
	Access               *string            `db:"access" json:"access"`
	Fees                 *string            `db:"fees" json:"fees"`
	ContactInfo          *string            `db:"contact_info" json:"contact_info"`
	VerificationStatus   string             `db:"verification_status" json:"verification_status"`
	VerifiedByAppUserID  pgtype.UUID        `db:"verified_by_app_user_id" json:"verified_by_app_user_id"`
	SubmittedByAppUserID pgtype.UUID        `db:"submitted_by_app_user_id" json:"submitted_by_app_user_id"`
	ReviewedByAppUserID  pgtype.UUID        `db:"reviewed_by_app_user_id" json:"reviewed_by_app_user_id"`
	ReviewedAt           pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ModerationReason     *string            `db:"moderation_reason" json:"moderation_reason"`
	ModerationState      string             `db:"moderation_state" json:"moderation_state"`
	LastUpdatedAt        pgtype.Timestamptz `db:"last_updated_at" json:"last_updated_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DiveSiteEditProposal struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	DiveSiteID                pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	SubmittedByAppUserID      pgtype.UUID        `db:"submitted_by_app_user_id" json:"submitted_by_app_user_id"`
	ReviewedByAppUserID       pgtype.UUID        `db:"reviewed_by_app_user_id" json:"reviewed_by_app_user_id"`
	ReviewedAt                pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ModerationReason          *string            `db:"moderation_reason" json:"moderation_reason"`
	State                     string             `db:"state" json:"state"`
	ProposedName              string             `db:"proposed_name" json:"proposed_name"`
	ProposedArea              string             `db:"proposed_area" json:"proposed_area"`
	ProposedLatitude          *float64           `db:"proposed_latitude" json:"proposed_latitude"`
	ProposedLongitude         *float64           `db:"proposed_longitude" json:"proposed_longitude"`
	ProposedDescription       string             `db:"proposed_description" json:"proposed_description"`
	ProposedEntryDifficulty   string             `db:"proposed_entry_difficulty" json:"proposed_entry_difficulty"`
	ProposedDepthMinM         pgtype.Numeric     `db:"proposed_depth_min_m" json:"proposed_depth_min_m"`
	ProposedDepthMaxM         pgtype.Numeric     `db:"proposed_depth_max_m" json:"proposed_depth_max_m"`
	ProposedHazards           []string           `db:"proposed_hazards" json:"proposed_hazards"`
	ProposedBestSeason        string             `db:"proposed_best_season" json:"proposed_best_season"`
	ProposedTypicalConditions string             `db:"proposed_typical_conditions" json:"proposed_typical_conditions"`
	ProposedAccess            string             `db:"proposed_access" json:"proposed_access"`
	ProposedFees              string             `db:"proposed_fees" json:"proposed_fees"`
	BaseSiteUpdatedAt         pgtype.Timestamptz `db:"base_site_updated_at" json:"base_site_updated_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DiveSiteLike struct {
	DiveSiteID pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DiveSiteReview struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	DiveSiteID pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Rating     int32              `db:"rating" json:"rating"`
	Comment    *string            `db:"comment" json:"comment"`
	Visibility string             `db:"visibility" json:"visibility"`
	Status     string             `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DiveSiteSafe struct {
	AppUserID  pgtype.UUID        `db:"app_user_id" json:"app_user_id"`
	DiveSiteID pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DiveSiteUpdate struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	DiveSiteID           pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	AuthorAppUserID      pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	Note                 string             `db:"note" json:"note"`
	ConditionVisibilityM pgtype.Numeric     `db:"condition_visibility_m" json:"condition_visibility_m"`
	ConditionCurrent     *string            `db:"condition_current" json:"condition_current"`
	ConditionWaves       *string            `db:"condition_waves" json:"condition_waves"`
	ConditionTempC       pgtype.Numeric     `db:"condition_temp_c" json:"condition_temp_c"`
	OccurredAt           pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	State                string             `db:"state" json:"state"`
}

type Event struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	Slug                 string             `db:"slug" json:"slug"`
	Title                string             `db:"title" json:"title"`
	Description          *string            `db:"description" json:"description"`
	ShortDescription     *string            `db:"short_description" json:"short_description"`
	DescriptionMarkdown  *string            `db:"description_markdown" json:"description_markdown"`
	LogoMediaID          pgtype.UUID        `db:"logo_media_id" json:"logo_media_id"`
	CoverMediaID         pgtype.UUID        `db:"cover_media_id" json:"cover_media_id"`
	CoverPhotoUrl        *string            `db:"cover_photo_url" json:"cover_photo_url"`
	Location             *string            `db:"location" json:"location"`
	LocationName         *string            `db:"location_name" json:"location_name"`
	FormattedAddress     *string            `db:"formatted_address" json:"formatted_address"`
	Latitude             *float64           `db:"latitude" json:"latitude"`
	Longitude            *float64           `db:"longitude" json:"longitude"`
	GooglePlaceID        *string            `db:"google_place_id" json:"google_place_id"`
	RegionCode           *string            `db:"region_code" json:"region_code"`
	ProvinceCode         *string            `db:"province_code" json:"province_code"`
	CityMunicipalityCode *string            `db:"city_municipality_code" json:"city_municipality_code"`
	BarangayCode         *string            `db:"barangay_code" json:"barangay_code"`
	LocationSource       string             `db:"location_source" json:"location_source"`
	StartsAt             pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt               pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	Timezone             string             `db:"timezone" json:"timezone"`
	Status               string             `db:"status" json:"status"`
	Visibility           string             `db:"visibility" json:"visibility"`
	EventType            string             `db:"event_type" json:"event_type"`
	Difficulty           string             `db:"difficulty" json:"difficulty"`
	MaxAttendees         *int32             `db:"max_attendees" json:"max_attendees"`
	Capacity             *int32             `db:"capacity" json:"capacity"`
	CurrentAttendees     int32              `db:"current_attendees" json:"current_attendees"`
	OrganizerUserID      pgtype.UUID        `db:"organizer_user_id" json:"organizer_user_id"`
	GroupID              pgtype.UUID        `db:"group_id" json:"group_id"`
	DiveSiteID           pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	RequiresApproval     bool               `db:"requires_approval" json:"requires_approval"`
	IsPaid               bool               `db:"is_paid" json:"is_paid"`
	PaymentMode          string             `db:"payment_mode" json:"payment_mode"`
	PriceAmount          pgtype.Numeric     `db:"price_amount" json:"price_amount"`
	Currency             string             `db:"currency" json:"currency"`
	PaymentInstructions  *string            `db:"payment_instructions" json:"payment_instructions"`
	MeetingPoint         *string            `db:"meeting_point" json:"meeting_point"`
	BeginnerFriendly     bool               `db:"beginner_friendly" json:"beginner_friendly"`
	MaxDepthM            *int32             `db:"max_depth_m" json:"max_depth_m"`
	EntryType            *string            `db:"entry_type" json:"entry_type"`
	EquipmentNotes       *string            `db:"equipment_notes" json:"equipment_notes"`
	SafetyNotes          *string            `db:"safety_notes" json:"safety_notes"`
	CancellationPolicy   *string            `db:"cancellation_policy" json:"cancellation_policy"`
	PaymentEnabled       bool               `db:"payment_enabled" json:"payment_enabled"`
	PostsEnabled         bool               `db:"posts_enabled" json:"posts_enabled"`
	AwardsEnabled        bool               `db:"awards_enabled" json:"awards_enabled"`
	SponsorsEnabled      bool               `db:"sponsors_enabled" json:"sponsors_enabled"`
	InterestedEnabled    bool               `db:"interested_enabled" json:"interested_enabled"`
	ProgramEnabled       bool               `db:"program_enabled" json:"program_enabled"`
	PostCreatePolicy     string             `db:"post_create_policy" json:"post_create_policy"`
	PublishedAt          pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CancelledAt          pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	CancelReason         *string            `db:"cancel_reason" json:"cancel_reason"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EventCompetition struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	EventID             pgtype.UUID        `db:"event_id" json:"event_id"`
	Name                string             `db:"name" json:"name"`
	DescriptionMarkdown *string            `db:"description_markdown" json:"description_markdown"`
	RulesMarkdown       *string            `db:"rules_markdown" json:"rules_markdown"`
	SortOrder           int32              `db:"sort_order" json:"sort_order"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type EventInterest struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	EventID   pgtype.UUID        `db:"event_id" json:"event_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type EventJoinFormField struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	EventID     pgtype.UUID        `db:"event_id" json:"event_id"`
	FieldKey    string             `db:"field_key" json:"field_key"`
	Label       string             `db:"label" json:"label"`
	FieldType   string             `db:"field_type" json:"field_type"`
	Required    bool               `db:"required" json:"required"`
	OptionsJson []byte             `db:"options_json" json:"options_json"`
	SortOrder   int32              `db:"sort_order" json:"sort_order"`
	Enabled     bool               `db:"enabled" json:"enabled"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EventMembership struct {
	EventID   pgtype.UUID        `db:"event_id" json:"event_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	Status    string             `db:"status" json:"status"`
	InvitedBy pgtype.UUID        `db:"invited_by" json:"invited_by"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt    pgtype.Timestamptz `db:"left_at" json:"left_at"`
	Notes     *string            `db:"notes" json:"notes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EventParticipantPayment struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	EventID              pgtype.UUID        `db:"event_id" json:"event_id"`
	EventParticipationID pgtype.UUID        `db:"event_participation_id" json:"event_participation_id"`
	UserID               pgtype.UUID        `db:"user_id" json:"user_id"`
	PaymentMethodID      pgtype.UUID        `db:"payment_method_id" json:"payment_method_id"`
	Amount               pgtype.Numeric     `db:"amount" json:"amount"`
	Currency             string             `db:"currency" json:"currency"`
	ProofMediaID         pgtype.UUID        `db:"proof_media_id" json:"proof_media_id"`
	ProofAttachmentUrl   *string            `db:"proof_attachment_url" json:"proof_attachment_url"`
	ReferenceNumber      *string            `db:"reference_number" json:"reference_number"`
	Status               string             `db:"status" json:"status"`
	ReviewedBy           pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ReviewNotes          *string            `db:"review_notes" json:"review_notes"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EventParticipation struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	EventID               pgtype.UUID        `db:"event_id" json:"event_id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	Role                  string             `db:"role" json:"role"`
	Status                string             `db:"status" json:"status"`
	ParticipantNote       *string            `db:"participant_note" json:"participant_note"`
	EmergencyContactName  *string            `db:"emergency_contact_name" json:"emergency_contact_name"`
	EmergencyContactPhone *string            `db:"emergency_contact_phone" json:"emergency_contact_phone"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ApprovedAt            pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ApprovedBy            pgtype.UUID        `db:"approved_by" json:"approved_by"`
	RejectedAt            pgtype.Timestamptz `db:"rejected_at" json:"rejected_at"`
	RejectedBy            pgtype.UUID        `db:"rejected_by" json:"rejected_by"`
	CancelledAt           pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	LeftAt                pgtype.Timestamptz `db:"left_at" json:"left_at"`
	QrToken               string             `db:"qr_token" json:"qr_token"`
	QrIssuedAt            pgtype.Timestamptz `db:"qr_issued_at" json:"qr_issued_at"`
	QrRevokedAt           pgtype.Timestamptz `db:"qr_revoked_at" json:"qr_revoked_at"`
	CheckedInAt           pgtype.Timestamptz `db:"checked_in_at" json:"checked_in_at"`
	CheckedInBy           pgtype.UUID        `db:"checked_in_by" json:"checked_in_by"`
	JoinAnswersJson       []byte             `db:"join_answers_json" json:"join_answers_json"`
}

type EventPaymentMethod struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	EventID       pgtype.UUID        `db:"event_id" json:"event_id"`
	Type          string             `db:"type" json:"type"`
	Name          string             `db:"name" json:"name"`
	Instructions  *string            `db:"instructions" json:"instructions"`
	QrMediaID     pgtype.UUID        `db:"qr_media_id" json:"qr_media_id"`
	QrImageUrl    *string            `db:"qr_image_url" json:"qr_image_url"`
	AccountName   *string            `db:"account_name" json:"account_name"`
	AccountNumber *string            `db:"account_number" json:"account_number"`
	BankName      *string            `db:"bank_name" json:"bank_name"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EventPost struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	EventID      pgtype.UUID        `db:"event_id" json:"event_id"`
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	PostType     string             `db:"post_type" json:"post_type"`
	Title        *string            `db:"title" json:"title"`
	BodyMarkdown string             `db:"body_markdown" json:"body_markdown"`
	Status       string             `db:"status" json:"status"`
	IsPinned     bool               `db:"is_pinned" json:"is_pinned"`
	ParentPostID pgtype.UUID        `db:"parent_post_id" json:"parent_post_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type EventPrize struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	EventID             pgtype.UUID        `db:"event_id" json:"event_id"`
	CompetitionID       pgtype.UUID        `db:"competition_id" json:"competition_id"`
	Title               string             `db:"title" json:"title"`
	DescriptionMarkdown *string            `db:"description_markdown" json:"description_markdown"`
	Placement           string             `db:"placement" json:"placement"`
	PlacementLabel      *string            `db:"placement_label" json:"placement_label"`
	PrizeType           *string            `db:"prize_type" json:"prize_type"`
	Amount              pgtype.Numeric     `db:"amount" json:"amount"`
	Currency            string             `db:"currency" json:"currency"`
	SponsorID           pgtype.UUID        `db:"sponsor_id" json:"sponsor_id"`
	SortOrder           int32              `db:"sort_order" json:"sort_order"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type EventProgramItem struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	EventID             pgtype.UUID        `db:"event_id" json:"event_id"`
	Title               string             `db:"title" json:"title"`
	DescriptionMarkdown *string            `db:"description_markdown" json:"description_markdown"`
	ProgramDate         pgtype.Date        `db:"program_date" json:"program_date"`
	StartTime           pgtype.Time        `db:"start_time" json:"start_time"`
	EndTime             pgtype.Time        `db:"end_time" json:"end_time"`
	Timezone            *string            `db:"timezone" json:"timezone"`
	LocationLabel       *string            `db:"location_label" json:"location_label"`
	CompetitionID       pgtype.UUID        `db:"competition_id" json:"competition_id"`
	SortOrder           int32              `db:"sort_order" json:"sort_order"`
	IsHighlighted       bool               `db:"is_highlighted" json:"is_highlighted"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type EventSponsor struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	EventID      pgtype.UUID        `db:"event_id" json:"event_id"`
	Name         string             `db:"name" json:"name"`
	Tier         *string            `db:"tier" json:"tier"`
	Description  *string            `db:"description" json:"description"`
	LogoMediaID  pgtype.UUID        `db:"logo_media_id" json:"logo_media_id"`
	WebsiteUrl   *string            `db:"website_url" json:"website_url"`
	SocialUrl    *string            `db:"social_url" json:"social_url"`
	ContactName  *string            `db:"contact_name" json:"contact_name"`
	ContactEmail *string            `db:"contact_email" json:"contact_email"`
	SortOrder    int32              `db:"sort_order" json:"sort_order"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type EventUpdateReaction struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	EventUpdateID pgtype.UUID        `db:"event_update_id" json:"event_update_id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	ReactionType  string             `db:"reaction_type" json:"reaction_type"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type FeedAction struct {
	ID         int64              `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	SessionID  string             `db:"session_id" json:"session_id"`
	FeedItemID *string            `db:"feed_item_id" json:"feed_item_id"`
	FeedSource string             `db:"feed_source" json:"feed_source"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   string             `db:"entity_id" json:"entity_id"`
	ActionType string             `db:"action_type" json:"action_type"`
	Mode       string             `db:"mode" json:"mode"`
	ValueJson  []byte             `db:"value_json" json:"value_json"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type FeedImpression struct {
	ID         int64              `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	SessionID  string             `db:"session_id" json:"session_id"`
	FeedItemID string             `db:"feed_item_id" json:"feed_item_id"`
	FeedSource string             `db:"feed_source" json:"feed_source"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   string             `db:"entity_id" json:"entity_id"`
	Mode       string             `db:"mode" json:"mode"`
	Position   int32              `db:"position" json:"position"`
	SeenAt     pgtype.Timestamptz `db:"seen_at" json:"seen_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Group struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	Name                 string             `db:"name" json:"name"`
	Slug                 string             `db:"slug" json:"slug"`
	Bio                  *string            `db:"bio" json:"bio"`
	Description          *string            `db:"description" json:"description"`
	LogoMediaID          pgtype.UUID        `db:"logo_media_id" json:"logo_media_id"`
	CoverMediaID         pgtype.UUID        `db:"cover_media_id" json:"cover_media_id"`
	Visibility           string             `db:"visibility" json:"visibility"`
	Status               string             `db:"status" json:"status"`
	JoinPolicy           string             `db:"join_policy" json:"join_policy"`
	Location             *string            `db:"location" json:"location"`
	LocationName         *string            `db:"location_name" json:"location_name"`
	FormattedAddress     *string            `db:"formatted_address" json:"formatted_address"`
	Lat                  *float64           `db:"lat" json:"lat"`
	Lng                  *float64           `db:"lng" json:"lng"`
	GooglePlaceID        *string            `db:"google_place_id" json:"google_place_id"`
	RegionCode           *string            `db:"region_code" json:"region_code"`
	ProvinceCode         *string            `db:"province_code" json:"province_code"`
	CityMunicipalityCode *string            `db:"city_municipality_code" json:"city_municipality_code"`
	BarangayCode         *string            `db:"barangay_code" json:"barangay_code"`
	LocationSource       string             `db:"location_source" json:"location_source"`
	MemberCount          int32              `db:"member_count" json:"member_count"`
	EventCount           int32              `db:"event_count" json:"event_count"`
	PostCount            int32              `db:"post_count" json:"post_count"`
	CreatedBy            pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupMembership struct {
	GroupID     pgtype.UUID        `db:"group_id" json:"group_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Role        string             `db:"role" json:"role"`
	Status      string             `db:"status" json:"status"`
	InvitedBy   pgtype.UUID        `db:"invited_by" json:"invited_by"`
	InvitedAt   pgtype.Timestamptz `db:"invited_at" json:"invited_at"`
	RespondedAt pgtype.Timestamptz `db:"responded_at" json:"responded_at"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt      pgtype.Timestamptz `db:"left_at" json:"left_at"`
	Muted       bool               `db:"muted" json:"muted"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupPost struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	GroupID      pgtype.UUID        `db:"group_id" json:"group_id"`
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	Title        *string            `db:"title" json:"title"`
	Content      string             `db:"content" json:"content"`
	Status       string             `db:"status" json:"status"`
	LikeCount    int64              `db:"like_count" json:"like_count"`
	CommentCount int64              `db:"comment_count" json:"comment_count"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type InstructorCertification struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	InstructorProfileID     pgtype.UUID        `db:"instructor_profile_id" json:"instructor_profile_id"`
	Agency                  string             `db:"agency" json:"agency"`
	AgencyOtherName         *string            `db:"agency_other_name" json:"agency_other_name"`
	CertificationLevel      string             `db:"certification_level" json:"certification_level"`
	CertificationNumber     *string            `db:"certification_number" json:"certification_number"`
	IssuedAt                pgtype.Date        `db:"issued_at" json:"issued_at"`
	ExpiresAt               pgtype.Date        `db:"expires_at" json:"expires_at"`
	ProofMediaID            pgtype.UUID        `db:"proof_media_id" json:"proof_media_id"`
	OfficialVerificationUrl *string            `db:"official_verification_url" json:"official_verification_url"`
	VerificationStatus      string             `db:"verification_status" json:"verification_status"`
	VerifiedAt              pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	VerifiedBy              pgtype.UUID        `db:"verified_by" json:"verified_by"`
	RejectionReason         *string            `db:"rejection_reason" json:"rejection_reason"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type InstructorProfile struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	DisplayName           string             `db:"display_name" json:"display_name"`
	Bio                   string             `db:"bio" json:"bio"`
	TeachingSince         pgtype.Date        `db:"teaching_since" json:"teaching_since"`
	HomeLocationLabel     string             `db:"home_location_label" json:"home_location_label"`
	FormattedAddress      string             `db:"formatted_address" json:"formatted_address"`
	RegionCode            string             `db:"region_code" json:"region_code"`
	RegionName            string             `db:"region_name" json:"region_name"`
	ProvinceCode          string             `db:"province_code" json:"province_code"`
	ProvinceName          string             `db:"province_name" json:"province_name"`
	CityCode              string             `db:"city_code" json:"city_code"`
	CityName              string             `db:"city_name" json:"city_name"`
	BarangayCode          string             `db:"barangay_code" json:"barangay_code"`
	BarangayName          string             `db:"barangay_name" json:"barangay_name"`
	LocationSource        string             `db:"location_source" json:"location_source"`
	Specialties           string             `db:"specialties" json:"specialties"`
	SchoolAffiliation     string             `db:"school_affiliation" json:"school_affiliation"`
	WebsiteUrl            string             `db:"website_url" json:"website_url"`
	SocialLinks           string             `db:"social_links" json:"social_links"`
	SafetyCredentials     string             `db:"safety_credentials" json:"safety_credentials"`
	VerificationStatus    string             `db:"verification_status" json:"verification_status"`
	VerifiedAt            pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	VerifiedBy            pgtype.UUID        `db:"verified_by" json:"verified_by"`
	RejectionReason       *string            `db:"rejection_reason" json:"rejection_reason"`
	AttestationAcceptedAt pgtype.Timestamptz `db:"attestation_accepted_at" json:"attestation_accepted_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MediaAsset struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OwnerUserID pgtype.UUID        `db:"owner_user_id" json:"owner_user_id"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    string             `db:"entity_id" json:"entity_id"`
	StorageKey  string             `db:"storage_key" json:"storage_key"`
	Url         string             `db:"url" json:"url"`
	MimeType    string             `db:"mime_type" json:"mime_type"`
	SizeBytes   int64              `db:"size_bytes" json:"size_bytes"`
	Width       *int32             `db:"width" json:"width"`
	Height      *int32             `db:"height" json:"height"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MediaItem struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PostID           pgtype.UUID        `db:"post_id" json:"post_id"`
	MediaObjectID    pgtype.UUID        `db:"media_object_id" json:"media_object_id"`
	AuthorAppUserID  pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID    pgtype.UUID        `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID       pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Type             string             `db:"type" json:"type"`
	StorageKey       string             `db:"storage_key" json:"storage_key"`
	MimeType         string             `db:"mime_type" json:"mime_type"`
	Width            int32              `db:"width" json:"width"`
	Height           int32              `db:"height" json:"height"`
	DurationMs       *int32             `db:"duration_ms" json:"duration_ms"`
	Caption          *string            `db:"caption" json:"caption"`
	SortOrder        int32              `db:"sort_order" json:"sort_order"`
	Status           string             `db:"status" json:"status"`
	Provider         string             `db:"provider" json:"provider"`
	StreamUid        *string            `db:"stream_uid" json:"stream_uid"`
	PlaybackUid      *string            `db:"playback_uid" json:"playback_uid"`
	PlaybackUrl      *string            `db:"playback_url" json:"playback_url"`
	ThumbnailUrl     *string            `db:"thumbnail_url" json:"thumbnail_url"`
	PreviewUrl       *string            `db:"preview_url" json:"preview_url"`
	AspectRatio      pgtype.Numeric     `db:"aspect_ratio" json:"aspect_ratio"`
	HasAudio         *bool              `db:"has_audio" json:"has_audio"`
	ProcessingStatus string             `db:"processing_status" json:"processing_status"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	UploadExpiresAt  pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	ReadyAt          pgtype.Timestamptz `db:"ready_at" json:"ready_at"`
	FailedReason     *string            `db:"failed_reason" json:"failed_reason"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type MediaObject struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	OwnerAppUserID pgtype.UUID        `db:"owner_app_user_id" json:"owner_app_user_id"`
	ContextType    string             `db:"context_type" json:"context_type"`
	ContextID      pgtype.UUID        `db:"context_id" json:"context_id"`
	ObjectKey      string             `db:"object_key" json:"object_key"`
	MimeType       string             `db:"mime_type" json:"mime_type"`
	SizeBytes      int64              `db:"size_bytes" json:"size_bytes"`
	Width          int32              `db:"width" json:"width"`
	Height         int32              `db:"height" json:"height"`
	State          string             `db:"state" json:"state"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MediaPost struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	AuthorAppUserID pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID   pgtype.UUID        `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID      pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	PostCaption     *string            `db:"post_caption" json:"post_caption"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type MediaPostComment struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	MediaPostID     pgtype.UUID        `db:"media_post_id" json:"media_post_id"`
	AuthorUserID    pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	Body            string             `db:"body" json:"body"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedByUserID pgtype.UUID        `db:"deleted_by_user_id" json:"deleted_by_user_id"`
}

type MediaPostCommentLike struct {
	CommentID pgtype.UUID        `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MediaPostLike struct {
	MediaPostID pgtype.UUID        `db:"media_post_id" json:"media_post_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MediaPostSafe struct {
	MediaPostID pgtype.UUID        `db:"media_post_id" json:"media_post_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MediaUploadGroup struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	AuthorAppUserID pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	Source          string             `db:"source" json:"source"`
	ItemCount       int32              `db:"item_count" json:"item_count"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Message struct {
	ID             int64              `db:"id" json:"id"`
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	SenderUserID   pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Content        string             `db:"content" json:"content"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	IdempotencyKey *string            `db:"idempotency_key" json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MessageThread struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastMessageAt   pgtype.Timestamptz `db:"last_message_at" json:"last_message_at"`
	Type            interface{}        `db:"type" json:"type"`
	CreatedByUserID pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	DirectUserLow   pgtype.UUID        `db:"direct_user_low" json:"direct_user_low"`
	DirectUserHigh  pgtype.UUID        `db:"direct_user_high" json:"direct_user_high"`
}

type MessageThreadMember struct {
	ThreadID          pgtype.UUID        `db:"thread_id" json:"thread_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	JoinedAt          pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt            pgtype.Timestamptz `db:"left_at" json:"left_at"`
	InboxCategory     interface{}        `db:"inbox_category" json:"inbox_category"`
	IsArchived        bool               `db:"is_archived" json:"is_archived"`
	IsMuted           bool               `db:"is_muted" json:"is_muted"`
	LastReadMessageID *int64             `db:"last_read_message_id" json:"last_read_message_id"`
	LastReadAt        pgtype.Timestamptz `db:"last_read_at" json:"last_read_at"`
}

type ModerationAction struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ActorAppUserID pgtype.UUID        `db:"actor_app_user_id" json:"actor_app_user_id"`
	TargetType     string             `db:"target_type" json:"target_type"`
	TargetUuid     pgtype.UUID        `db:"target_uuid" json:"target_uuid"`
	TargetBigint   *int64             `db:"target_bigint" json:"target_bigint"`
	Action         string             `db:"action" json:"action"`
	Reason         string             `db:"reason" json:"reason"`
	ReportID       pgtype.UUID        `db:"report_id" json:"report_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Notification struct {
	ID                int64              `db:"id" json:"id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Type              interface{}        `db:"type" json:"type"`
	Category          string             `db:"category" json:"category"`
	Title             string             `db:"title" json:"title"`
	Message           string             `db:"message" json:"message"`
	Status            interface{}        `db:"status" json:"status"`
	Priority          interface{}        `db:"priority" json:"priority"`
	ActorUserID       pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	RelatedUserID     pgtype.UUID        `db:"related_user_id" json:"related_user_id"`
	RelatedEntityType *string            `db:"related_entity_type" json:"related_entity_type"`
	RelatedEntityID   *string            `db:"related_entity_id" json:"related_entity_id"`
	ImageUrl          *string            `db:"image_url" json:"image_url"`
	ActionUrl         *string            `db:"action_url" json:"action_url"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	IsEmailSent       bool               `db:"is_email_sent" json:"is_email_sent"`
	IsPushSent        bool               `db:"is_push_sent" json:"is_push_sent"`
	EmailSentAt       pgtype.Timestamptz `db:"email_sent_at" json:"email_sent_at"`
	PushSentAt        pgtype.Timestamptz `db:"push_sent_at" json:"push_sent_at"`
	ReadAt            pgtype.Timestamptz `db:"read_at" json:"read_at"`
	SeenAt            pgtype.Timestamptz `db:"seen_at" json:"seen_at"`
	ArchivedAt        pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	IdempotencyKey    *string            `db:"idempotency_key" json:"idempotency_key"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type NotificationOutbox struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	EventType      string             `db:"event_type" json:"event_type"`
	AggregateType  string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID    pgtype.UUID        `db:"aggregate_id" json:"aggregate_id"`
	Payload        []byte             `db:"payload" json:"payload"`
	Status         string             `db:"status" json:"status"`
	Attempts       int32              `db:"attempts" json:"attempts"`
	NextRetryAt    pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	LastError      *string            `db:"last_error" json:"last_error"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProcessedAt    pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

type NotificationSetting struct {
	ID                         pgtype.UUID        `db:"id" json:"id"`
	UserID                     pgtype.UUID        `db:"user_id" json:"user_id"`
	EmailEnabled               bool               `db:"email_enabled" json:"email_enabled"`
	PushEnabled                bool               `db:"push_enabled" json:"push_enabled"`
	InAppEnabled               bool               `db:"in_app_enabled" json:"in_app_enabled"`
	SystemNotifications        bool               `db:"system_notifications" json:"system_notifications"`
	MessageNotifications       bool               `db:"message_notifications" json:"message_notifications"`
	EventNotifications         bool               `db:"event_notifications" json:"event_notifications"`
	GroupNotifications         bool               `db:"group_notifications" json:"group_notifications"`
	ServiceNotifications       bool               `db:"service_notifications" json:"service_notifications"`
	BookingNotifications       bool               `db:"booking_notifications" json:"booking_notifications"`
	ReviewNotifications        bool               `db:"review_notifications" json:"review_notifications"`
	MentionNotifications       bool               `db:"mention_notifications" json:"mention_notifications"`
	LikeNotifications          bool               `db:"like_notifications" json:"like_notifications"`
	CommentNotifications       bool               `db:"comment_notifications" json:"comment_notifications"`
	FriendRequestNotifications bool               `db:"friend_request_notifications" json:"friend_request_notifications"`
	GroupInviteNotifications   bool               `db:"group_invite_notifications" json:"group_invite_notifications"`
	EventReminderNotifications bool               `db:"event_reminder_notifications" json:"event_reminder_notifications"`
	PaymentNotifications       bool               `db:"payment_notifications" json:"payment_notifications"`
	SecurityNotifications      bool               `db:"security_notifications" json:"security_notifications"`
	NewDiveSitePublished       bool               `db:"new_dive_site_published" json:"new_dive_site_published"`
	ChikaReplies               bool               `db:"chika_replies" json:"chika_replies"`
	DigestFrequency            interface{}        `db:"digest_frequency" json:"digest_frequency"`
	QuietHoursStart            *string            `db:"quiet_hours_start" json:"quiet_hours_start"`
	QuietHoursEnd              *string            `db:"quiet_hours_end" json:"quiet_hours_end"`
	Timezone                   string             `db:"timezone" json:"timezone"`
	BuddyUpdates               bool               `db:"buddy_updates" json:"buddy_updates"`
	ProfileSocialUpdates       bool               `db:"profile_social_updates" json:"profile_social_updates"`
	DiveConditionAlerts        bool               `db:"dive_condition_alerts" json:"dive_condition_alerts"`
	DiveConditionSavedSites    bool               `db:"dive_condition_saved_sites" json:"dive_condition_saved_sites"`
	DiveConditionRegions       []byte             `db:"dive_condition_regions" json:"dive_condition_regions"`
	DiveConditionNearMe        bool               `db:"dive_condition_near_me" json:"dive_condition_near_me"`
	DiveConditionCoarseArea    *string            `db:"dive_condition_coarse_area" json:"dive_condition_coarse_area"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Profile struct {
	UserID              pgtype.UUID        `db:"user_id" json:"user_id"`
	Bio                 string             `db:"bio" json:"bio"`
	AvatarUrl           string             `db:"avatar_url" json:"avatar_url"`
	Location            string             `db:"location" json:"location"`
	HomeArea            string             `db:"home_area" json:"home_area"`
	Interests           []string           `db:"interests" json:"interests"`
	CertLevel           *string            `db:"cert_level" json:"cert_level"`
	Socials             []byte             `db:"socials" json:"socials"`
	PseudonymousEnabled bool               `db:"pseudonymous_enabled" json:"pseudonymous_enabled"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PsgcBarangay struct {
	Code                 string             `db:"code" json:"code"`
	PsgcCode             string             `db:"psgc_code" json:"psgc_code"`
	RegionCode           string             `db:"region_code" json:"region_code"`
	ProvinceCode         *string            `db:"province_code" json:"province_code"`
	CityMunicipalityCode string             `db:"city_municipality_code" json:"city_municipality_code"`
	Name                 string             `db:"name" json:"name"`
	OldName              *string            `db:"old_name" json:"old_name"`
	SourceVersion        string             `db:"source_version" json:"source_version"`
	IsActive             bool               `db:"is_active" json:"is_active"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PsgcCitiesMunicipality struct {
	Code          string             `db:"code" json:"code"`
	PsgcCode      string             `db:"psgc_code" json:"psgc_code"`
	RegionCode    string             `db:"region_code" json:"region_code"`
	ProvinceCode  *string            `db:"province_code" json:"province_code"`
	Name          string             `db:"name" json:"name"`
	OldName       *string            `db:"old_name" json:"old_name"`
	SourceVersion string             `db:"source_version" json:"source_version"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PsgcImportHistory struct {
	ID                        int64              `db:"id" json:"id"`
	SourceVersion             string             `db:"source_version" json:"source_version"`
	SourceDirectory           string             `db:"source_directory" json:"source_directory"`
	PublishedAt               pgtype.Timestamptz `db:"published_at" json:"published_at"`
	RegionsCount              int32              `db:"regions_count" json:"regions_count"`
	ProvincesCount            int32              `db:"provinces_count" json:"provinces_count"`
	CitiesMunicipalitiesCount int32              `db:"cities_municipalities_count" json:"cities_municipalities_count"`
	BarangaysCount            int32              `db:"barangays_count" json:"barangays_count"`
	ImportedAt                pgtype.Timestamptz `db:"imported_at" json:"imported_at"`
}

type PsgcProvince struct {
	Code          string             `db:"code" json:"code"`
	PsgcCode      string             `db:"psgc_code" json:"psgc_code"`
	RegionCode    string             `db:"region_code" json:"region_code"`
	Name          string             `db:"name" json:"name"`
	OldName       *string            `db:"old_name" json:"old_name"`
	CityClass     *string            `db:"city_class" json:"city_class"`
	SourceVersion string             `db:"source_version" json:"source_version"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PsgcRegion struct {
	Code          string             `db:"code" json:"code"`
	PsgcCode      string             `db:"psgc_code" json:"psgc_code"`
	Name          string             `db:"name" json:"name"`
	SourceVersion string             `db:"source_version" json:"source_version"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RateLimitEvent struct {
	ID            int64              `db:"id" json:"id"`
	Scope         string             `db:"scope" json:"scope"`
	KeyHash       string             `db:"key_hash" json:"key_hash"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	WindowSeconds int32              `db:"window_seconds" json:"window_seconds"`
}

type Report struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ReporterAppUserID pgtype.UUID        `db:"reporter_app_user_id" json:"reporter_app_user_id"`
	TargetType        string             `db:"target_type" json:"target_type"`
	TargetUuid        pgtype.UUID        `db:"target_uuid" json:"target_uuid"`
	TargetBigint      *int64             `db:"target_bigint" json:"target_bigint"`
	TargetAppUserID   pgtype.UUID        `db:"target_app_user_id" json:"target_app_user_id"`
	ReasonCode        string             `db:"reason_code" json:"reason_code"`
	Details           *string            `db:"details" json:"details"`
	EvidenceUrls      []byte             `db:"evidence_urls" json:"evidence_urls"`
	Status            string             `db:"status" json:"status"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ReportEvent struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ReportID       pgtype.UUID        `db:"report_id" json:"report_id"`
	ActorAppUserID pgtype.UUID        `db:"actor_app_user_id" json:"actor_app_user_id"`
	EventType      string             `db:"event_type" json:"event_type"`
	FromStatus     *string            `db:"from_status" json:"from_status"`
	ToStatus       *string            `db:"to_status" json:"to_status"`
	Note           *string            `db:"note" json:"note"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SavedUser struct {
	ViewerAppUserID pgtype.UUID        `db:"viewer_app_user_id" json:"viewer_app_user_id"`
	SavedAppUserID  pgtype.UUID        `db:"saved_app_user_id" json:"saved_app_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type School struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Slug                string             `db:"slug" json:"slug"`
	Name                string             `db:"name" json:"name"`
	ShortDescription    string             `db:"short_description" json:"short_description"`
	DescriptionMarkdown string             `db:"description_markdown" json:"description_markdown"`
	LogoMediaID         pgtype.UUID        `db:"logo_media_id" json:"logo_media_id"`
	CoverMediaID        pgtype.UUID        `db:"cover_media_id" json:"cover_media_id"`
	BaseLocation        *string            `db:"base_location" json:"base_location"`
	BaseLocationLabel   *string            `db:"base_location_label" json:"base_location_label"`
	FormattedAddress    *string            `db:"formatted_address" json:"formatted_address"`
	RegionCode          *string            `db:"region_code" json:"region_code"`
	RegionName          *string            `db:"region_name" json:"region_name"`
	ProvinceCode        *string            `db:"province_code" json:"province_code"`
	ProvinceName        *string            `db:"province_name" json:"province_name"`
	CityCode            *string            `db:"city_code" json:"city_code"`
	CityName            *string            `db:"city_name" json:"city_name"`
	BarangayCode        *string            `db:"barangay_code" json:"barangay_code"`
	BarangayName        *string            `db:"barangay_name" json:"barangay_name"`
	LocationSource      string             `db:"location_source" json:"location_source"`
	DiveSiteID          pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	ContactEmail        *string            `db:"contact_email" json:"contact_email"`
	ContactPhone        *string            `db:"contact_phone" json:"contact_phone"`
	WebsiteUrl          *string            `db:"website_url" json:"website_url"`
	FacebookUrl         *string            `db:"facebook_url" json:"facebook_url"`
	InstagramUrl        *string            `db:"instagram_url" json:"instagram_url"`
	Status              string             `db:"status" json:"status"`
	OwnerUserID         pgtype.UUID        `db:"owner_user_id" json:"owner_user_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type SchoolMember struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	SchoolID  pgtype.UUID        `db:"school_id" json:"school_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type SchoolPaymentMethod struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	SchoolID      pgtype.UUID        `db:"school_id" json:"school_id"`
	Type          string             `db:"type" json:"type"`
	Name          string             `db:"name" json:"name"`
	Instructions  *string            `db:"instructions" json:"instructions"`
	QrMediaID     pgtype.UUID        `db:"qr_media_id" json:"qr_media_id"`
	BankName      *string            `db:"bank_name" json:"bank_name"`
	AccountName   *string            `db:"account_name" json:"account_name"`
	AccountNumber *string            `db:"account_number" json:"account_number"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ThreadMessage struct {
	ID           int64              `db:"id" json:"id"`
	ThreadID     pgtype.UUID        `db:"thread_id" json:"thread_id"`
	SenderUserID pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	ClientID     *string            `db:"client_id" json:"client_id"`
	Kind         interface{}        `db:"kind" json:"kind"`
	Body         string             `db:"body" json:"body"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	EditedAt     pgtype.Timestamptz `db:"edited_at" json:"edited_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Username           string             `db:"username" json:"username"`
	DisplayName        string             `db:"display_name" json:"display_name"`
	AuthProvider       string             `db:"auth_provider" json:"auth_provider"`
	AuthProviderUserID *string            `db:"auth_provider_user_id" json:"auth_provider_user_id"`
	EmailVerified      bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified      bool               `db:"phone_verified" json:"phone_verified"`
	GlobalRole         string             `db:"global_role" json:"global_role"`
	AccountStatus      string             `db:"account_status" json:"account_status"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserBadge struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	BadgeTemplateID    pgtype.UUID        `db:"badge_template_id" json:"badge_template_id"`
	ValueText          *string            `db:"value_text" json:"value_text"`
	ValueNumber        pgtype.Numeric     `db:"value_number" json:"value_number"`
	ValueMinutes       *int32             `db:"value_minutes" json:"value_minutes"`
	ValueSeconds       *int32             `db:"value_seconds" json:"value_seconds"`
	ReferenceLabel     *string            `db:"reference_label" json:"reference_label"`
	ReferenceValue     *string            `db:"reference_value" json:"reference_value"`
	ProofMediaID       pgtype.UUID        `db:"proof_media_id" json:"proof_media_id"`
	VerificationStatus string             `db:"verification_status" json:"verification_status"`
	VerifiedAt         pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	VerifiedBy         pgtype.UUID        `db:"verified_by" json:"verified_by"`
	SourceType         string             `db:"source_type" json:"source_type"`
	SourceID           *string            `db:"source_id" json:"source_id"`
	EarnedAt           pgtype.Timestamptz `db:"earned_at" json:"earned_at"`
	Visibility         string             `db:"visibility" json:"visibility"`
	DisplayOrder       int32              `db:"display_order" json:"display_order"`
	MetadataJson       []byte             `db:"metadata_json" json:"metadata_json"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserBlock struct {
	BlockerAppUserID pgtype.UUID        `db:"blocker_app_user_id" json:"blocker_app_user_id"`
	BlockedAppUserID pgtype.UUID        `db:"blocked_app_user_id" json:"blocked_app_user_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserDiveSite struct {
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	DiveSiteID     pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	FirstPostID    pgtype.UUID        `db:"first_post_id" json:"first_post_id"`
	FirstVisitedAt pgtype.Timestamptz `db:"first_visited_at" json:"first_visited_at"`
	LastPostID     pgtype.UUID        `db:"last_post_id" json:"last_post_id"`
	LastVisitedAt  pgtype.Timestamptz `db:"last_visited_at" json:"last_visited_at"`
	MediaPostCount int32              `db:"media_post_count" json:"media_post_count"`
	Visibility     string             `db:"visibility" json:"visibility"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserDiveSiteAffinity struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	DiveSiteID     pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Relationship   string             `db:"relationship" json:"relationship"`
	Visibility     string             `db:"visibility" json:"visibility"`
	ContactEnabled bool               `db:"contact_enabled" json:"contact_enabled"`
	Note           *string            `db:"note" json:"note"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserFeedPreference struct {
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	PreferredRegions []string           `db:"preferred_regions" json:"preferred_regions"`
	MutedEntityTypes []string           `db:"muted_entity_types" json:"muted_entity_types"`
	MutedTopics      []string           `db:"muted_topics" json:"muted_topics"`
	HiddenCreators   []string           `db:"hidden_creators" json:"hidden_creators"`
	HiddenSpots      []string           `db:"hidden_spots" json:"hidden_spots"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserHiddenFeedItem struct {
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   string             `db:"entity_id" json:"entity_id"`
	Reason     string             `db:"reason" json:"reason"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserPermissionOverride struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Overrides []byte             `db:"overrides" json:"overrides"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
