// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package reportsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReportEvent = `-- name: AddReportEvent :one
INSERT INTO report_events (report_id, actor_app_user_id, event_type, from_status, to_status, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, report_id, actor_app_user_id, event_type, from_status, to_status, note, created_at
`

type AddReportEventParams struct {
	ReportID       pgtype.UUID `db:"report_id" json:"report_id"`
	ActorAppUserID pgtype.UUID `db:"actor_app_user_id" json:"actor_app_user_id"`
	EventType      string      `db:"event_type" json:"event_type"`
	FromStatus     *string     `db:"from_status" json:"from_status"`
	ToStatus       *string     `db:"to_status" json:"to_status"`
	Note           *string     `db:"note" json:"note"`
}

func (q *Queries) AddReportEvent(ctx context.Context, arg AddReportEventParams) (ReportEvent, error) {
	row := q.db.QueryRow(ctx, addReportEvent,
		arg.ReportID,
		arg.ActorAppUserID,
		arg.EventType,
		arg.FromStatus,
		arg.ToStatus,
		arg.Note,
	)
	var i ReportEvent
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.ActorAppUserID,
		&i.EventType,
		&i.FromStatus,
		&i.ToStatus,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const countReportsByReporterSince = `-- name: CountReportsByReporterSince :one
SELECT COUNT(*)
FROM reports
WHERE reporter_app_user_id = $1
  AND created_at >= $2
`

type CountReportsByReporterSinceParams struct {
	ReporterAppUserID pgtype.UUID        `db:"reporter_app_user_id" json:"reporter_app_user_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CountReportsByReporterSince(ctx context.Context, arg CountReportsByReporterSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByReporterSince, arg.ReporterAppUserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
  reporter_app_user_id,
  target_type,
  target_uuid,
  target_bigint,
  target_app_user_id,
  reason_code,
  details,
  evidence_urls,
  status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'open')
RETURNING id, reporter_app_user_id, target_type, target_uuid, target_bigint, target_app_user_id, reason_code, details, evidence_urls, status, created_at, updated_at
`

type CreateReportParams struct {
	ReporterAppUserID pgtype.UUID `db:"reporter_app_user_id" json:"reporter_app_user_id"`
	TargetType        string      `db:"target_type" json:"target_type"`
	TargetUuid        pgtype.UUID `db:"target_uuid" json:"target_uuid"`
	TargetBigint      *int64      `db:"target_bigint" json:"target_bigint"`
	TargetAppUserID   pgtype.UUID `db:"target_app_user_id" json:"target_app_user_id"`
	ReasonCode        string      `db:"reason_code" json:"reason_code"`
	Details           *string     `db:"details" json:"details"`
	EvidenceUrls      []byte      `db:"evidence_urls" json:"evidence_urls"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterAppUserID,
		arg.TargetType,
		arg.TargetUuid,
		arg.TargetBigint,
		arg.TargetAppUserID,
		arg.ReasonCode,
		arg.Details,
		arg.EvidenceUrls,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterAppUserID,
		&i.TargetType,
		&i.TargetUuid,
		&i.TargetBigint,
		&i.TargetAppUserID,
		&i.ReasonCode,
		&i.Details,
		&i.EvidenceUrls,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRecentReportByReporterAndTargetBigint = `-- name: FindRecentReportByReporterAndTargetBigint :one
SELECT id, created_at
FROM reports
WHERE reporter_app_user_id = $1
  AND target_type = $2
  AND target_bigint = $3
  AND created_at >= $4
ORDER BY created_at DESC
LIMIT 1
`

type FindRecentReportByReporterAndTargetBigintParams struct {
	ReporterAppUserID pgtype.UUID        `db:"reporter_app_user_id" json:"reporter_app_user_id"`
	TargetType        string             `db:"target_type" json:"target_type"`
	TargetBigint      *int64             `db:"target_bigint" json:"target_bigint"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type FindRecentReportByReporterAndTargetBigintRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) FindRecentReportByReporterAndTargetBigint(ctx context.Context, arg FindRecentReportByReporterAndTargetBigintParams) (FindRecentReportByReporterAndTargetBigintRow, error) {
	row := q.db.QueryRow(ctx, findRecentReportByReporterAndTargetBigint,
		arg.ReporterAppUserID,
		arg.TargetType,
		arg.TargetBigint,
		arg.CreatedAt,
	)
	var i FindRecentReportByReporterAndTargetBigintRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const findRecentReportByReporterAndTargetUUID = `-- name: FindRecentReportByReporterAndTargetUUID :one
SELECT id, created_at
FROM reports
WHERE reporter_app_user_id = $1
  AND target_type = $2
  AND target_uuid = $3
  AND created_at >= $4
ORDER BY created_at DESC
LIMIT 1
`

type FindRecentReportByReporterAndTargetUUIDParams struct {
	ReporterAppUserID pgtype.UUID        `db:"reporter_app_user_id" json:"reporter_app_user_id"`
	TargetType        string             `db:"target_type" json:"target_type"`
	TargetUuid        pgtype.UUID        `db:"target_uuid" json:"target_uuid"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type FindRecentReportByReporterAndTargetUUIDRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) FindRecentReportByReporterAndTargetUUID(ctx context.Context, arg FindRecentReportByReporterAndTargetUUIDParams) (FindRecentReportByReporterAndTargetUUIDRow, error) {
	row := q.db.QueryRow(ctx, findRecentReportByReporterAndTargetUUID,
		arg.ReporterAppUserID,
		arg.TargetType,
		arg.TargetUuid,
		arg.CreatedAt,
	)
	var i FindRecentReportByReporterAndTargetUUIDRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, reporter_app_user_id, target_type, target_uuid, target_bigint, target_app_user_id, reason_code, details, evidence_urls, status, created_at, updated_at
FROM reports
WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterAppUserID,
		&i.TargetType,
		&i.TargetUuid,
		&i.TargetBigint,
		&i.TargetAppUserID,
		&i.ReasonCode,
		&i.Details,
		&i.EvidenceUrls,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReportEventsByReportID = `-- name: ListReportEventsByReportID :many
SELECT id, report_id, actor_app_user_id, event_type, from_status, to_status, note, created_at
FROM report_events
WHERE report_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListReportEventsByReportID(ctx context.Context, reportID pgtype.UUID) ([]ReportEvent, error) {
	rows, err := q.db.Query(ctx, listReportEventsByReportID, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportEvent{}
	for rows.Next() {
		var i ReportEvent
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.ActorAppUserID,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsForModeration = `-- name: ListReportsForModeration :many
SELECT id, reporter_app_user_id, target_type, target_uuid, target_bigint, target_app_user_id, reason_code, details, evidence_urls, status, created_at, updated_at
FROM reports r
WHERE ($4::text IS NULL OR r.status = $4::text)
  AND ($5::text IS NULL OR r.target_type = $5::text)
  AND ($6::uuid IS NULL OR r.reporter_app_user_id = $6::uuid)
  AND (r.created_at < $1 OR (r.created_at = $1 AND r.id < $2))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $3
`

type ListReportsForModerationParams struct {
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID               pgtype.UUID        `db:"id" json:"id"`
	Limit            int32              `db:"limit" json:"limit"`
	StatusFilter     *string            `db:"status_filter" json:"status_filter"`
	TargetTypeFilter *string            `db:"target_type_filter" json:"target_type_filter"`
	ReporterFilter   pgtype.UUID        `db:"reporter_filter" json:"reporter_filter"`
}

func (q *Queries) ListReportsForModeration(ctx context.Context, arg ListReportsForModerationParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsForModeration,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
		arg.StatusFilter,
		arg.TargetTypeFilter,
		arg.ReporterFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterAppUserID,
			&i.TargetType,
			&i.TargetUuid,
			&i.TargetBigint,
			&i.TargetAppUserID,
			&i.ReasonCode,
			&i.Details,
			&i.EvidenceUrls,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChikaCommentAuthor = `-- name: ResolveChikaCommentAuthor :one
SELECT author_user_id
FROM chika_comments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ResolveChikaCommentAuthor(ctx context.Context, id int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveChikaCommentAuthor, id)
	var author_user_id pgtype.UUID
	err := row.Scan(&author_user_id)
	return author_user_id, err
}

const resolveChikaThreadAuthor = `-- name: ResolveChikaThreadAuthor :one
SELECT created_by_user_id
FROM chika_threads
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ResolveChikaThreadAuthor(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveChikaThreadAuthor, id)
	var created_by_user_id pgtype.UUID
	err := row.Scan(&created_by_user_id)
	return created_by_user_id, err
}

const resolveDiveSiteUpdateAuthor = `-- name: ResolveDiveSiteUpdateAuthor :one
SELECT author_app_user_id
FROM dive_site_updates
WHERE id = $1
  AND state = 'active'
`

func (q *Queries) ResolveDiveSiteUpdateAuthor(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveDiveSiteUpdateAuthor, id)
	var author_app_user_id pgtype.UUID
	err := row.Scan(&author_app_user_id)
	return author_app_user_id, err
}

const resolveMessageAuthor = `-- name: ResolveMessageAuthor :one
SELECT sender_user_id
FROM messages
WHERE id = $1
`

func (q *Queries) ResolveMessageAuthor(ctx context.Context, id int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveMessageAuthor, id)
	var sender_user_id pgtype.UUID
	err := row.Scan(&sender_user_id)
	return sender_user_id, err
}

const resolveUserExists = `-- name: ResolveUserExists :one
SELECT id
FROM users
WHERE id = $1
`

func (q *Queries) ResolveUserExists(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveUserExists, id)
	err := row.Scan(&id)
	return id, err
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, reporter_app_user_id, target_type, target_uuid, target_bigint, target_app_user_id, reason_code, details, evidence_urls, status, created_at, updated_at
`

type UpdateReportStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportStatus, arg.ID, arg.Status)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterAppUserID,
		&i.TargetType,
		&i.TargetUuid,
		&i.TargetBigint,
		&i.TargetAppUserID,
		&i.ReasonCode,
		&i.Details,
		&i.EvidenceUrls,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
