// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package blocksqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlock = `-- name: CreateBlock :exec
INSERT INTO user_blocks (blocker_app_user_id, blocked_app_user_id)
VALUES ($1, $2)
ON CONFLICT (blocker_app_user_id, blocked_app_user_id) DO NOTHING
`

type CreateBlockParams struct {
	BlockerAppUserID pgtype.UUID `db:"blocker_app_user_id" json:"blocker_app_user_id"`
	BlockedAppUserID pgtype.UUID `db:"blocked_app_user_id" json:"blocked_app_user_id"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock, arg.BlockerAppUserID, arg.BlockedAppUserID)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM user_blocks
WHERE blocker_app_user_id = $1 AND blocked_app_user_id = $2
`

type DeleteBlockParams struct {
	BlockerAppUserID pgtype.UUID `db:"blocker_app_user_id" json:"blocker_app_user_id"`
	BlockedAppUserID pgtype.UUID `db:"blocked_app_user_id" json:"blocked_app_user_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.BlockerAppUserID, arg.BlockedAppUserID)
	return err
}

const isBlockedEitherDirection = `-- name: IsBlockedEitherDirection :one
SELECT EXISTS (
  SELECT 1
  FROM user_blocks
  WHERE (blocker_app_user_id = $1 AND blocked_app_user_id = $2)
     OR (blocker_app_user_id = $2 AND blocked_app_user_id = $1)
)
`

type IsBlockedEitherDirectionParams struct {
	BlockerAppUserID pgtype.UUID `db:"blocker_app_user_id" json:"blocker_app_user_id"`
	BlockedAppUserID pgtype.UUID `db:"blocked_app_user_id" json:"blocked_app_user_id"`
}

func (q *Queries) IsBlockedEitherDirection(ctx context.Context, arg IsBlockedEitherDirectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedEitherDirection, arg.BlockerAppUserID, arg.BlockedAppUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlockedUserIDs = `-- name: ListBlockedUserIDs :many
SELECT blocked_app_user_id
FROM user_blocks
WHERE blocker_app_user_id = $1
`

func (q *Queries) ListBlockedUserIDs(ctx context.Context, blockerAppUserID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listBlockedUserIDs, blockerAppUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var blocked_app_user_id pgtype.UUID
		if err := rows.Scan(&blocked_app_user_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_app_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByBlocker = `-- name: ListBlocksByBlocker :many
SELECT
  b.blocked_app_user_id,
  b.created_at,
  u.username,
  u.display_name,
  p.avatar_url
FROM user_blocks b
JOIN users u ON u.id = b.blocked_app_user_id
LEFT JOIN profiles p ON p.user_id = u.id
WHERE b.blocker_app_user_id = $1
  AND (b.created_at < $2 OR (b.created_at = $2 AND b.blocked_app_user_id < $3))
ORDER BY b.created_at DESC, b.blocked_app_user_id DESC
LIMIT $4
`

type ListBlocksByBlockerParams struct {
	BlockerAppUserID pgtype.UUID        `db:"blocker_app_user_id" json:"blocker_app_user_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	BlockedAppUserID pgtype.UUID        `db:"blocked_app_user_id" json:"blocked_app_user_id"`
	Limit            int32              `db:"limit" json:"limit"`
}

type ListBlocksByBlockerRow struct {
	BlockedAppUserID pgtype.UUID        `db:"blocked_app_user_id" json:"blocked_app_user_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Username         string             `db:"username" json:"username"`
	DisplayName      string             `db:"display_name" json:"display_name"`
	AvatarUrl        *string            `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) ListBlocksByBlocker(ctx context.Context, arg ListBlocksByBlockerParams) ([]ListBlocksByBlockerRow, error) {
	rows, err := q.db.Query(ctx, listBlocksByBlocker,
		arg.BlockerAppUserID,
		arg.CreatedAt,
		arg.BlockedAppUserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksByBlockerRow{}
	for rows.Next() {
		var i ListBlocksByBlockerRow
		if err := rows.Scan(
			&i.BlockedAppUserID,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWhoBlockedMe = `-- name: ListUsersWhoBlockedMe :many
SELECT blocker_app_user_id
FROM user_blocks
WHERE blocked_app_user_id = $1
`

func (q *Queries) ListUsersWhoBlockedMe(ctx context.Context, blockedAppUserID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUsersWhoBlockedMe, blockedAppUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var blocker_app_user_id pgtype.UUID
		if err := rows.Scan(&blocker_app_user_id); err != nil {
			return nil, err
		}
		items = append(items, blocker_app_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
