// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buddyfinder.sql

package buddyfinderqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPreviewByArea = `-- name: CountPreviewByArea :one
SELECT COUNT(*)::bigint
FROM buddy_intents bi
WHERE bi.state = 'active'
  AND bi.visibility = 'members'
  AND bi.expires_at > NOW()
  AND ($1::text = '' OR bi.area = $1)
`

func (q *Queries) CountPreviewByArea(ctx context.Context, areaFilter string) (int64, error) {
	row := q.db.QueryRow(ctx, countPreviewByArea, areaFilter)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createIntent = `-- name: CreateIntent :one
INSERT INTO buddy_intents (
  author_app_user_id,
  dive_site_id,
  area,
  intent_type,
  time_window,
  date_start,
  date_end,
  note,
  expires_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING id, author_app_user_id, dive_site_id, area, intent_type, time_window, date_start, date_end, note, visibility, state, created_at, expires_at
`

type CreateIntentParams struct {
	AuthorAppUserID pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	DiveSiteID      pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Area            string             `db:"area" json:"area"`
	IntentType      string             `db:"intent_type" json:"intent_type"`
	TimeWindow      string             `db:"time_window" json:"time_window"`
	DateStart       pgtype.Date        `db:"date_start" json:"date_start"`
	DateEnd         pgtype.Date        `db:"date_end" json:"date_end"`
	Note            *string            `db:"note" json:"note"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateIntent(ctx context.Context, arg CreateIntentParams) (BuddyIntent, error) {
	row := q.db.QueryRow(ctx, createIntent,
		arg.AuthorAppUserID,
		arg.DiveSiteID,
		arg.Area,
		arg.IntentType,
		arg.TimeWindow,
		arg.DateStart,
		arg.DateEnd,
		arg.Note,
		arg.ExpiresAt,
	)
	var i BuddyIntent
	err := row.Scan(
		&i.ID,
		&i.AuthorAppUserID,
		&i.DiveSiteID,
		&i.Area,
		&i.IntentType,
		&i.TimeWindow,
		&i.DateStart,
		&i.DateEnd,
		&i.Note,
		&i.Visibility,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteIntentByOwner = `-- name: DeleteIntentByOwner :execrows
DELETE FROM buddy_intents
WHERE id = $1
  AND author_app_user_id = $2
`

type DeleteIntentByOwnerParams struct {
	IntentID        pgtype.UUID `db:"intent_id" json:"intent_id"`
	AuthorAppUserID pgtype.UUID `db:"author_app_user_id" json:"author_app_user_id"`
}

func (q *Queries) DeleteIntentByOwner(ctx context.Context, arg DeleteIntentByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntentByOwner, arg.IntentID, arg.AuthorAppUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntentByID = `-- name: GetIntentByID :one
SELECT
  bi.id,
  bi.author_app_user_id,
  bi.dive_site_id,
  bi.area,
  bi.intent_type,
  bi.time_window,
  bi.date_start,
  bi.date_end,
  bi.note,
  bi.visibility,
  bi.state,
  bi.created_at,
  bi.expires_at
FROM buddy_intents bi
WHERE bi.id = $1
`

func (q *Queries) GetIntentByID(ctx context.Context, intentID pgtype.UUID) (BuddyIntent, error) {
	row := q.db.QueryRow(ctx, getIntentByID, intentID)
	var i BuddyIntent
	err := row.Scan(
		&i.ID,
		&i.AuthorAppUserID,
		&i.DiveSiteID,
		&i.Area,
		&i.IntentType,
		&i.TimeWindow,
		&i.DateStart,
		&i.DateEnd,
		&i.Note,
		&i.Visibility,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSharePreviewByID = `-- name: GetSharePreviewByID :one
SELECT
  bi.id,
  bi.author_app_user_id,
  bi.dive_site_id,
  COALESCE(ds.name, '') AS dive_site_name,
  bi.area,
  bi.intent_type,
  bi.time_window,
  bi.date_start,
  bi.date_end,
  bi.note,
  bi.created_at,
  bi.expires_at,
  u.email_verified,
  u.phone_verified,
  p.cert_level,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM (
      SELECT app_user_id_a AS app_user_id FROM buddies
      UNION ALL
      SELECT app_user_id_b AS app_user_id FROM buddies
    ) pairs
    WHERE pairs.app_user_id = bi.author_app_user_id
  ), 0)::bigint AS buddy_count,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM reports r
    WHERE r.target_app_user_id = bi.author_app_user_id
  ), 0)::bigint AS report_count
FROM buddy_intents bi
JOIN users u ON u.id = bi.author_app_user_id
JOIN profiles p ON p.user_id = bi.author_app_user_id
LEFT JOIN dive_sites ds ON ds.id = bi.dive_site_id
WHERE bi.id = $1
  AND bi.state = 'active'
  AND bi.visibility = 'members'
  AND bi.expires_at > NOW()
  AND u.account_status = 'active'
`

type GetSharePreviewByIDRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	AuthorAppUserID pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	DiveSiteID      pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	DiveSiteName    string             `db:"dive_site_name" json:"dive_site_name"`
	Area            string             `db:"area" json:"area"`
	IntentType      string             `db:"intent_type" json:"intent_type"`
	TimeWindow      string             `db:"time_window" json:"time_window"`
	DateStart       pgtype.Date        `db:"date_start" json:"date_start"`
	DateEnd         pgtype.Date        `db:"date_end" json:"date_end"`
	Note            *string            `db:"note" json:"note"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	EmailVerified   bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified   bool               `db:"phone_verified" json:"phone_verified"`
	CertLevel       *string            `db:"cert_level" json:"cert_level"`
	BuddyCount      int64              `db:"buddy_count" json:"buddy_count"`
	ReportCount     int64              `db:"report_count" json:"report_count"`
}

func (q *Queries) GetSharePreviewByID(ctx context.Context, intentID pgtype.UUID) (GetSharePreviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getSharePreviewByID, intentID)
	var i GetSharePreviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorAppUserID,
		&i.DiveSiteID,
		&i.DiveSiteName,
		&i.Area,
		&i.IntentType,
		&i.TimeWindow,
		&i.DateStart,
		&i.DateEnd,
		&i.Note,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.CertLevel,
		&i.BuddyCount,
		&i.ReportCount,
	)
	return i, err
}

const listMemberIntentsByArea = `-- name: ListMemberIntentsByArea :many
SELECT
  bi.id,
  bi.author_app_user_id,
  bi.dive_site_id,
  u.username,
  u.display_name,
  COALESCE(p.avatar_url, '') AS avatar_url,
  p.home_area,
  bi.area,
  bi.intent_type,
  bi.time_window,
  bi.date_start,
  bi.date_end,
  bi.note,
  bi.created_at,
  bi.expires_at,
  u.email_verified,
  u.phone_verified,
  p.cert_level,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM (
      SELECT app_user_id_a AS app_user_id FROM buddies
      UNION ALL
      SELECT app_user_id_b AS app_user_id FROM buddies
    ) pairs
    WHERE pairs.app_user_id = bi.author_app_user_id
  ), 0)::bigint AS buddy_count,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM reports r
    WHERE r.target_app_user_id = bi.author_app_user_id
  ), 0)::bigint AS report_count,
  0::bigint AS mutual_buddies_count
FROM buddy_intents bi
JOIN users u ON u.id = bi.author_app_user_id
JOIN profiles p ON p.user_id = bi.author_app_user_id
WHERE bi.state = 'active'
  AND bi.visibility = 'members'
  AND bi.expires_at > NOW()
  AND u.account_status = 'active'
  AND bi.author_app_user_id <> $1
  AND ($2::text = '' OR bi.area = $2)
  AND ($3::text = '' OR bi.intent_type = $3)
  AND ($4::text = '' OR bi.time_window = $4)
  AND NOT EXISTS (
    SELECT 1
    FROM user_blocks ub
    WHERE (ub.blocker_app_user_id = $1 AND ub.blocked_app_user_id = bi.author_app_user_id)
       OR (ub.blocker_app_user_id = bi.author_app_user_id AND ub.blocked_app_user_id = $1)
  )
  AND (bi.created_at < $5 OR (bi.created_at = $5 AND bi.id < $6))
ORDER BY bi.created_at DESC, bi.id DESC
LIMIT $7
`

type ListMemberIntentsByAreaParams struct {
	ViewerUserID     pgtype.UUID        `db:"viewer_user_id" json:"viewer_user_id"`
	AreaFilter       string             `db:"area_filter" json:"area_filter"`
	IntentTypeFilter string             `db:"intent_type_filter" json:"intent_type_filter"`
	TimeWindowFilter string             `db:"time_window_filter" json:"time_window_filter"`
	CursorCreatedAt  pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID         pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	LimitRows        int32              `db:"limit_rows" json:"limit_rows"`
}

type ListMemberIntentsByAreaRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	AuthorAppUserID    pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	DiveSiteID         pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Username           string             `db:"username" json:"username"`
	DisplayName        string             `db:"display_name" json:"display_name"`
	AvatarUrl          string             `db:"avatar_url" json:"avatar_url"`
	HomeArea           string             `db:"home_area" json:"home_area"`
	Area               string             `db:"area" json:"area"`
	IntentType         string             `db:"intent_type" json:"intent_type"`
	TimeWindow         string             `db:"time_window" json:"time_window"`
	DateStart          pgtype.Date        `db:"date_start" json:"date_start"`
	DateEnd            pgtype.Date        `db:"date_end" json:"date_end"`
	Note               *string            `db:"note" json:"note"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	EmailVerified      bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified      bool               `db:"phone_verified" json:"phone_verified"`
	CertLevel          *string            `db:"cert_level" json:"cert_level"`
	BuddyCount         int64              `db:"buddy_count" json:"buddy_count"`
	ReportCount        int64              `db:"report_count" json:"report_count"`
	MutualBuddiesCount int64              `db:"mutual_buddies_count" json:"mutual_buddies_count"`
}

func (q *Queries) ListMemberIntentsByArea(ctx context.Context, arg ListMemberIntentsByAreaParams) ([]ListMemberIntentsByAreaRow, error) {
	rows, err := q.db.Query(ctx, listMemberIntentsByArea,
		arg.ViewerUserID,
		arg.AreaFilter,
		arg.IntentTypeFilter,
		arg.TimeWindowFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberIntentsByAreaRow{}
	for rows.Next() {
		var i ListMemberIntentsByAreaRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorAppUserID,
			&i.DiveSiteID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.HomeArea,
			&i.Area,
			&i.IntentType,
			&i.TimeWindow,
			&i.DateStart,
			&i.DateEnd,
			&i.Note,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.EmailVerified,
			&i.PhoneVerified,
			&i.CertLevel,
			&i.BuddyCount,
			&i.ReportCount,
			&i.MutualBuddiesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberIntentsBySite = `-- name: ListMemberIntentsBySite :many
SELECT
  bi.id,
  bi.author_app_user_id,
  bi.dive_site_id,
  u.username,
  u.display_name,
  COALESCE(p.avatar_url, '') AS avatar_url,
  p.home_area,
  bi.area,
  bi.intent_type,
  bi.time_window,
  bi.date_start,
  bi.date_end,
  bi.note,
  bi.created_at,
  bi.expires_at,
  u.email_verified,
  u.phone_verified,
  p.cert_level,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM (
      SELECT app_user_id_a AS app_user_id FROM buddies
      UNION ALL
      SELECT app_user_id_b AS app_user_id FROM buddies
    ) pairs
    WHERE pairs.app_user_id = bi.author_app_user_id
  ), 0)::bigint AS buddy_count,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM reports r
    WHERE r.target_app_user_id = bi.author_app_user_id
  ), 0)::bigint AS report_count,
  0::bigint AS mutual_buddies_count
FROM buddy_intents bi
JOIN users u ON u.id = bi.author_app_user_id
JOIN profiles p ON p.user_id = bi.author_app_user_id
WHERE bi.state = 'active'
  AND bi.visibility = 'members'
  AND bi.expires_at > NOW()
  AND u.account_status = 'active'
  AND bi.author_app_user_id <> $1
  AND bi.dive_site_id = $2
  AND NOT EXISTS (
    SELECT 1
    FROM user_blocks ub
    WHERE (ub.blocker_app_user_id = $1 AND ub.blocked_app_user_id = bi.author_app_user_id)
       OR (ub.blocker_app_user_id = bi.author_app_user_id AND ub.blocked_app_user_id = $1)
  )
  AND (bi.created_at < $3 OR (bi.created_at = $3 AND bi.id < $4))
ORDER BY bi.created_at DESC, bi.id DESC
LIMIT $5
`

type ListMemberIntentsBySiteParams struct {
	ViewerUserID    pgtype.UUID        `db:"viewer_user_id" json:"viewer_user_id"`
	DiveSiteID      pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	LimitRows       int32              `db:"limit_rows" json:"limit_rows"`
}

type ListMemberIntentsBySiteRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	AuthorAppUserID    pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	DiveSiteID         pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Username           string             `db:"username" json:"username"`
	DisplayName        string             `db:"display_name" json:"display_name"`
	AvatarUrl          string             `db:"avatar_url" json:"avatar_url"`
	HomeArea           string             `db:"home_area" json:"home_area"`
	Area               string             `db:"area" json:"area"`
	IntentType         string             `db:"intent_type" json:"intent_type"`
	TimeWindow         string             `db:"time_window" json:"time_window"`
	DateStart          pgtype.Date        `db:"date_start" json:"date_start"`
	DateEnd            pgtype.Date        `db:"date_end" json:"date_end"`
	Note               *string            `db:"note" json:"note"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	EmailVerified      bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified      bool               `db:"phone_verified" json:"phone_verified"`
	CertLevel          *string            `db:"cert_level" json:"cert_level"`
	BuddyCount         int64              `db:"buddy_count" json:"buddy_count"`
	ReportCount        int64              `db:"report_count" json:"report_count"`
	MutualBuddiesCount int64              `db:"mutual_buddies_count" json:"mutual_buddies_count"`
}

func (q *Queries) ListMemberIntentsBySite(ctx context.Context, arg ListMemberIntentsBySiteParams) ([]ListMemberIntentsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listMemberIntentsBySite,
		arg.ViewerUserID,
		arg.DiveSiteID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberIntentsBySiteRow{}
	for rows.Next() {
		var i ListMemberIntentsBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorAppUserID,
			&i.DiveSiteID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.HomeArea,
			&i.Area,
			&i.IntentType,
			&i.TimeWindow,
			&i.DateStart,
			&i.DateEnd,
			&i.Note,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.EmailVerified,
			&i.PhoneVerified,
			&i.CertLevel,
			&i.BuddyCount,
			&i.ReportCount,
			&i.MutualBuddiesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewByArea = `-- name: ListPreviewByArea :many
SELECT
  bi.id,
  bi.author_app_user_id,
  bi.dive_site_id,
  p.home_area,
  bi.area,
  bi.intent_type,
  bi.time_window,
  bi.date_start,
  bi.date_end,
  bi.note,
  bi.created_at,
  bi.expires_at,
  u.email_verified,
  u.phone_verified,
  p.cert_level,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM (
      SELECT app_user_id_a AS app_user_id FROM buddies
      UNION ALL
      SELECT app_user_id_b AS app_user_id FROM buddies
    ) pairs
    WHERE pairs.app_user_id = bi.author_app_user_id
  ), 0)::bigint AS buddy_count,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM reports r
    WHERE r.target_app_user_id = bi.author_app_user_id
  ), 0)::bigint AS report_count,
  0::bigint AS mutual_buddies_count
FROM buddy_intents bi
JOIN users u ON u.id = bi.author_app_user_id
JOIN profiles p ON p.user_id = bi.author_app_user_id
WHERE bi.state = 'active'
  AND bi.visibility = 'members'
  AND bi.expires_at > NOW()
  AND u.account_status = 'active'
  AND ($1::text = '' OR bi.area = $1)
ORDER BY bi.created_at DESC, bi.id DESC
LIMIT $2
`

type ListPreviewByAreaParams struct {
	AreaFilter string `db:"area_filter" json:"area_filter"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

type ListPreviewByAreaRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	AuthorAppUserID    pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	DiveSiteID         pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	HomeArea           string             `db:"home_area" json:"home_area"`
	Area               string             `db:"area" json:"area"`
	IntentType         string             `db:"intent_type" json:"intent_type"`
	TimeWindow         string             `db:"time_window" json:"time_window"`
	DateStart          pgtype.Date        `db:"date_start" json:"date_start"`
	DateEnd            pgtype.Date        `db:"date_end" json:"date_end"`
	Note               *string            `db:"note" json:"note"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	EmailVerified      bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified      bool               `db:"phone_verified" json:"phone_verified"`
	CertLevel          *string            `db:"cert_level" json:"cert_level"`
	BuddyCount         int64              `db:"buddy_count" json:"buddy_count"`
	ReportCount        int64              `db:"report_count" json:"report_count"`
	MutualBuddiesCount int64              `db:"mutual_buddies_count" json:"mutual_buddies_count"`
}

func (q *Queries) ListPreviewByArea(ctx context.Context, arg ListPreviewByAreaParams) ([]ListPreviewByAreaRow, error) {
	rows, err := q.db.Query(ctx, listPreviewByArea, arg.AreaFilter, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreviewByAreaRow{}
	for rows.Next() {
		var i ListPreviewByAreaRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorAppUserID,
			&i.DiveSiteID,
			&i.HomeArea,
			&i.Area,
			&i.IntentType,
			&i.TimeWindow,
			&i.DateStart,
			&i.DateEnd,
			&i.Note,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.EmailVerified,
			&i.PhoneVerified,
			&i.CertLevel,
			&i.BuddyCount,
			&i.ReportCount,
			&i.MutualBuddiesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewBySite = `-- name: ListPreviewBySite :many
SELECT
  bi.id,
  bi.author_app_user_id,
  bi.dive_site_id,
  p.home_area,
  bi.area,
  bi.intent_type,
  bi.time_window,
  bi.date_start,
  bi.date_end,
  bi.note,
  bi.created_at,
  bi.expires_at,
  u.email_verified,
  u.phone_verified,
  p.cert_level,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM (
      SELECT app_user_id_a AS app_user_id FROM buddies
      UNION ALL
      SELECT app_user_id_b AS app_user_id FROM buddies
    ) pairs
    WHERE pairs.app_user_id = bi.author_app_user_id
  ), 0)::bigint AS buddy_count,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM reports r
    WHERE r.target_app_user_id = bi.author_app_user_id
  ), 0)::bigint AS report_count,
  0::bigint AS mutual_buddies_count
FROM buddy_intents bi
JOIN users u ON u.id = bi.author_app_user_id
JOIN profiles p ON p.user_id = bi.author_app_user_id
WHERE bi.state = 'active'
  AND bi.visibility = 'members'
  AND bi.expires_at > NOW()
  AND u.account_status = 'active'
  AND bi.dive_site_id = $1
ORDER BY bi.created_at DESC, bi.id DESC
LIMIT $2
`

type ListPreviewBySiteParams struct {
	DiveSiteID pgtype.UUID `db:"dive_site_id" json:"dive_site_id"`
	LimitRows  int32       `db:"limit_rows" json:"limit_rows"`
}

type ListPreviewBySiteRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	AuthorAppUserID    pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	DiveSiteID         pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	HomeArea           string             `db:"home_area" json:"home_area"`
	Area               string             `db:"area" json:"area"`
	IntentType         string             `db:"intent_type" json:"intent_type"`
	TimeWindow         string             `db:"time_window" json:"time_window"`
	DateStart          pgtype.Date        `db:"date_start" json:"date_start"`
	DateEnd            pgtype.Date        `db:"date_end" json:"date_end"`
	Note               *string            `db:"note" json:"note"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	EmailVerified      bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified      bool               `db:"phone_verified" json:"phone_verified"`
	CertLevel          *string            `db:"cert_level" json:"cert_level"`
	BuddyCount         int64              `db:"buddy_count" json:"buddy_count"`
	ReportCount        int64              `db:"report_count" json:"report_count"`
	MutualBuddiesCount int64              `db:"mutual_buddies_count" json:"mutual_buddies_count"`
}

func (q *Queries) ListPreviewBySite(ctx context.Context, arg ListPreviewBySiteParams) ([]ListPreviewBySiteRow, error) {
	rows, err := q.db.Query(ctx, listPreviewBySite, arg.DiveSiteID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreviewBySiteRow{}
	for rows.Next() {
		var i ListPreviewBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorAppUserID,
			&i.DiveSiteID,
			&i.HomeArea,
			&i.Area,
			&i.IntentType,
			&i.TimeWindow,
			&i.DateStart,
			&i.DateEnd,
			&i.Note,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.EmailVerified,
			&i.PhoneVerified,
			&i.CertLevel,
			&i.BuddyCount,
			&i.ReportCount,
			&i.MutualBuddiesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
