// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package profilesqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	BlockerID pgtype.UUID        `db:"blocker_id" json:"blocker_id"`
	BlockedID pgtype.UUID        `db:"blocked_id" json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Buddy struct {
	AppUserIDA pgtype.UUID        `db:"app_user_id_a" json:"app_user_id_a"`
	AppUserIDB pgtype.UUID        `db:"app_user_id_b" json:"app_user_id_b"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BuddyIntent struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	AuthorAppUserID pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	DiveSiteID      pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Area            string             `db:"area" json:"area"`
	IntentType      string             `db:"intent_type" json:"intent_type"`
	TimeWindow      string             `db:"time_window" json:"time_window"`
	DateStart       pgtype.Date        `db:"date_start" json:"date_start"`
	DateEnd         pgtype.Date        `db:"date_end" json:"date_end"`
	Note            *string            `db:"note" json:"note"`
	Visibility      string             `db:"visibility" json:"visibility"`
	State           string             `db:"state" json:"state"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type BuddyRelationship struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	BuddyID   pgtype.UUID        `db:"buddy_id" json:"buddy_id"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type BuddyRequest struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	RequesterAppUserID pgtype.UUID        `db:"requester_app_user_id" json:"requester_app_user_id"`
	TargetAppUserID    pgtype.UUID        `db:"target_app_user_id" json:"target_app_user_id"`
	Status             string             `db:"status" json:"status"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ChikaCategory struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Slug         string             `db:"slug" json:"slug"`
	Name         string             `db:"name" json:"name"`
	Pseudonymous bool               `db:"pseudonymous" json:"pseudonymous"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ChikaComment struct {
	ID           int64              `db:"id" json:"id"`
	ThreadID     pgtype.UUID        `db:"thread_id" json:"thread_id"`
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	Pseudonym    string             `db:"pseudonym" json:"pseudonym"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	HiddenAt     pgtype.Timestamptz `db:"hidden_at" json:"hidden_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ChikaPost struct {
	ID           int64              `db:"id" json:"id"`
	ThreadID     pgtype.UUID        `db:"thread_id" json:"thread_id"`
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	Pseudonym    string             `db:"pseudonym" json:"pseudonym"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ChikaThread struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Title           string             `db:"title" json:"title"`
	Mode            string             `db:"mode" json:"mode"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	CreatedByUserID pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	HiddenAt        pgtype.Timestamptz `db:"hidden_at" json:"hidden_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ChikaThreadReaction struct {
	ThreadID     pgtype.UUID        `db:"thread_id" json:"thread_id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	ReactionType string             `db:"reaction_type" json:"reaction_type"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Conversation struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Kind            string             `db:"kind" json:"kind"`
	DmPairKey       string             `db:"dm_pair_key" json:"dm_pair_key"`
	InitiatorUserID pgtype.UUID        `db:"initiator_user_id" json:"initiator_user_id"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ConversationParticipant struct {
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	LastReadAt     pgtype.Timestamptz `db:"last_read_at" json:"last_read_at"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type DiveSite struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Name                string             `db:"name" json:"name"`
	Slug                string             `db:"slug" json:"slug"`
	Area                string             `db:"area" json:"area"`
	Latitude            *float64           `db:"latitude" json:"latitude"`
	Longitude           *float64           `db:"longitude" json:"longitude"`
	EntryDifficulty     string             `db:"entry_difficulty" json:"entry_difficulty"`
	DepthMinM           pgtype.Numeric     `db:"depth_min_m" json:"depth_min_m"`
	DepthMaxM           pgtype.Numeric     `db:"depth_max_m" json:"depth_max_m"`
	Hazards             []string           `db:"hazards" json:"hazards"`
	BestSeason          *string            `db:"best_season" json:"best_season"`
	TypicalConditions   *string            `db:"typical_conditions" json:"typical_conditions"`
	Access              *string            `db:"access" json:"access"`
	Fees                *string            `db:"fees" json:"fees"`
	ContactInfo         *string            `db:"contact_info" json:"contact_info"`
	VerificationStatus  string             `db:"verification_status" json:"verification_status"`
	VerifiedByAppUserID pgtype.UUID        `db:"verified_by_app_user_id" json:"verified_by_app_user_id"`
	ModerationState     string             `db:"moderation_state" json:"moderation_state"`
	LastUpdatedAt       pgtype.Timestamptz `db:"last_updated_at" json:"last_updated_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DiveSiteSafe struct {
	AppUserID  pgtype.UUID        `db:"app_user_id" json:"app_user_id"`
	DiveSiteID pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DiveSiteUpdate struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	DiveSiteID           pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	AuthorAppUserID      pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	Note                 string             `db:"note" json:"note"`
	ConditionVisibilityM pgtype.Numeric     `db:"condition_visibility_m" json:"condition_visibility_m"`
	ConditionCurrent     *string            `db:"condition_current" json:"condition_current"`
	ConditionWaves       *string            `db:"condition_waves" json:"condition_waves"`
	ConditionTempC       pgtype.Numeric     `db:"condition_temp_c" json:"condition_temp_c"`
	OccurredAt           pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	State                string             `db:"state" json:"state"`
}

type Event struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EventMembership struct {
	EventID   pgtype.UUID        `db:"event_id" json:"event_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Group struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GroupMembership struct {
	GroupID   pgtype.UUID        `db:"group_id" json:"group_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MediaAsset struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OwnerUserID pgtype.UUID        `db:"owner_user_id" json:"owner_user_id"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    string             `db:"entity_id" json:"entity_id"`
	StorageKey  string             `db:"storage_key" json:"storage_key"`
	Url         string             `db:"url" json:"url"`
	MimeType    string             `db:"mime_type" json:"mime_type"`
	SizeBytes   int64              `db:"size_bytes" json:"size_bytes"`
	Width       *int32             `db:"width" json:"width"`
	Height      *int32             `db:"height" json:"height"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MediaObject struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	OwnerAppUserID pgtype.UUID        `db:"owner_app_user_id" json:"owner_app_user_id"`
	ContextType    string             `db:"context_type" json:"context_type"`
	ContextID      pgtype.UUID        `db:"context_id" json:"context_id"`
	ObjectKey      string             `db:"object_key" json:"object_key"`
	MimeType       string             `db:"mime_type" json:"mime_type"`
	SizeBytes      int64              `db:"size_bytes" json:"size_bytes"`
	Width          int32              `db:"width" json:"width"`
	Height         int32              `db:"height" json:"height"`
	State          string             `db:"state" json:"state"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Message struct {
	ID             int64              `db:"id" json:"id"`
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	SenderUserID   pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Content        string             `db:"content" json:"content"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	IdempotencyKey *string            `db:"idempotency_key" json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ModerationAction struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ActorAppUserID pgtype.UUID        `db:"actor_app_user_id" json:"actor_app_user_id"`
	TargetType     string             `db:"target_type" json:"target_type"`
	TargetUuid     pgtype.UUID        `db:"target_uuid" json:"target_uuid"`
	TargetBigint   *int64             `db:"target_bigint" json:"target_bigint"`
	Action         string             `db:"action" json:"action"`
	Reason         string             `db:"reason" json:"reason"`
	ReportID       pgtype.UUID        `db:"report_id" json:"report_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Profile struct {
	UserID              pgtype.UUID        `db:"user_id" json:"user_id"`
	Bio                 string             `db:"bio" json:"bio"`
	AvatarUrl           string             `db:"avatar_url" json:"avatar_url"`
	Location            string             `db:"location" json:"location"`
	HomeArea            string             `db:"home_area" json:"home_area"`
	Interests           []string           `db:"interests" json:"interests"`
	CertLevel           *string            `db:"cert_level" json:"cert_level"`
	Socials             []byte             `db:"socials" json:"socials"`
	PseudonymousEnabled bool               `db:"pseudonymous_enabled" json:"pseudonymous_enabled"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RateLimitEvent struct {
	ID            int64              `db:"id" json:"id"`
	Scope         string             `db:"scope" json:"scope"`
	KeyHash       string             `db:"key_hash" json:"key_hash"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	WindowSeconds int32              `db:"window_seconds" json:"window_seconds"`
}

type Report struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ReporterAppUserID pgtype.UUID        `db:"reporter_app_user_id" json:"reporter_app_user_id"`
	TargetType        string             `db:"target_type" json:"target_type"`
	TargetUuid        pgtype.UUID        `db:"target_uuid" json:"target_uuid"`
	TargetBigint      *int64             `db:"target_bigint" json:"target_bigint"`
	TargetAppUserID   pgtype.UUID        `db:"target_app_user_id" json:"target_app_user_id"`
	ReasonCode        string             `db:"reason_code" json:"reason_code"`
	Details           *string            `db:"details" json:"details"`
	EvidenceUrls      []byte             `db:"evidence_urls" json:"evidence_urls"`
	Status            string             `db:"status" json:"status"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ReportEvent struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ReportID       pgtype.UUID        `db:"report_id" json:"report_id"`
	ActorAppUserID pgtype.UUID        `db:"actor_app_user_id" json:"actor_app_user_id"`
	EventType      string             `db:"event_type" json:"event_type"`
	FromStatus     *string            `db:"from_status" json:"from_status"`
	ToStatus       *string            `db:"to_status" json:"to_status"`
	Note           *string            `db:"note" json:"note"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SavedUser struct {
	ViewerAppUserID pgtype.UUID        `db:"viewer_app_user_id" json:"viewer_app_user_id"`
	SavedAppUserID  pgtype.UUID        `db:"saved_app_user_id" json:"saved_app_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Username           string             `db:"username" json:"username"`
	DisplayName        string             `db:"display_name" json:"display_name"`
	AuthProvider       string             `db:"auth_provider" json:"auth_provider"`
	AuthProviderUserID *string            `db:"auth_provider_user_id" json:"auth_provider_user_id"`
	EmailVerified      bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified      bool               `db:"phone_verified" json:"phone_verified"`
	GlobalRole         string             `db:"global_role" json:"global_role"`
	AccountStatus      string             `db:"account_status" json:"account_status"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserBlock struct {
	BlockerAppUserID pgtype.UUID        `db:"blocker_app_user_id" json:"blocker_app_user_id"`
	BlockedAppUserID pgtype.UUID        `db:"blocked_app_user_id" json:"blocked_app_user_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserPermissionOverride struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Overrides []byte             `db:"overrides" json:"overrides"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
