// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package profilesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfileByUserID = `-- name: GetProfileByUserID :one
WITH buddy_counts AS (
  SELECT app_user_id, COUNT(*)::bigint AS buddy_count
  FROM (
    SELECT app_user_id_a AS app_user_id FROM buddies
    UNION ALL
    SELECT app_user_id_b AS app_user_id FROM buddies
  ) pairs
  GROUP BY app_user_id
),
report_counts AS (
  SELECT target_app_user_id AS user_id, COUNT(*)::bigint AS report_count
  FROM reports
  WHERE target_app_user_id IS NOT NULL
  GROUP BY target_app_user_id
)
SELECT
  u.id AS user_id,
  u.username,
  u.display_name,
  u.email_verified,
  u.phone_verified,
  COALESCE(bc.buddy_count, 0)::bigint AS buddy_count,
  COALESCE(rc.report_count, 0)::bigint AS report_count,
  p.bio,
  p.avatar_url,
  p.location,
  p.home_area,
  p.interests,
  p.cert_level,
  p.socials,
  p.updated_at
FROM users u
JOIN profiles p ON p.user_id = u.id
LEFT JOIN buddy_counts bc ON bc.app_user_id = u.id
LEFT JOIN report_counts rc ON rc.user_id = u.id
WHERE u.id = $1
`

type GetProfileByUserIDRow struct {
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified bool               `db:"phone_verified" json:"phone_verified"`
	BuddyCount    int64              `db:"buddy_count" json:"buddy_count"`
	ReportCount   int64              `db:"report_count" json:"report_count"`
	Bio           string             `db:"bio" json:"bio"`
	AvatarUrl     string             `db:"avatar_url" json:"avatar_url"`
	Location      string             `db:"location" json:"location"`
	HomeArea      string             `db:"home_area" json:"home_area"`
	Interests     []string           `db:"interests" json:"interests"`
	CertLevel     *string            `db:"cert_level" json:"cert_level"`
	Socials       []byte             `db:"socials" json:"socials"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetProfileByUserID(ctx context.Context, id pgtype.UUID) (GetProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, id)
	var i GetProfileByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.BuddyCount,
		&i.ReportCount,
		&i.Bio,
		&i.AvatarUrl,
		&i.Location,
		&i.HomeArea,
		&i.Interests,
		&i.CertLevel,
		&i.Socials,
		&i.UpdatedAt,
	)
	return i, err
}

const listSavedSitesForUser = `-- name: ListSavedSitesForUser :many
SELECT
  s.id,
  s.slug,
  s.name,
  s.area,
  s.entry_difficulty,
  s.last_updated_at,
  COALESCE((
    SELECT
      COALESCE(
        NULLIF(u.note, ''),
        TRIM(BOTH ' ' FROM CONCAT(
          CASE WHEN u.condition_visibility_m IS NOT NULL THEN 'Vis ' || u.condition_visibility_m::text || 'm.' ELSE '' END,
          CASE WHEN u.condition_current IS NOT NULL THEN ' Current ' || u.condition_current || '.' ELSE '' END,
          CASE WHEN u.condition_waves IS NOT NULL THEN ' Waves ' || u.condition_waves || '.' ELSE '' END
        ))
      )
    FROM dive_site_updates u
    WHERE u.dive_site_id = s.id
      AND u.state = 'active'
    ORDER BY u.occurred_at DESC, u.id DESC
    LIMIT 1
  ), '') AS last_condition_summary,
  ss.created_at AS saved_at
FROM dive_site_saves ss
JOIN dive_sites s ON s.id = ss.dive_site_id
WHERE ss.app_user_id = $1
  AND s.moderation_state = 'approved'
ORDER BY ss.created_at DESC, s.id DESC
`

type ListSavedSitesForUserRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	Slug                 string             `db:"slug" json:"slug"`
	Name                 string             `db:"name" json:"name"`
	Area                 string             `db:"area" json:"area"`
	EntryDifficulty      string             `db:"entry_difficulty" json:"entry_difficulty"`
	LastUpdatedAt        pgtype.Timestamptz `db:"last_updated_at" json:"last_updated_at"`
	LastConditionSummary interface{}        `db:"last_condition_summary" json:"last_condition_summary"`
	SavedAt              pgtype.Timestamptz `db:"saved_at" json:"saved_at"`
}

func (q *Queries) ListSavedSitesForUser(ctx context.Context, appUserID pgtype.UUID) ([]ListSavedSitesForUserRow, error) {
	rows, err := q.db.Query(ctx, listSavedSitesForUser, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedSitesForUserRow{}
	for rows.Next() {
		var i ListSavedSitesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Area,
			&i.EntryDifficulty,
			&i.LastUpdatedAt,
			&i.LastConditionSummary,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedUsersForUser = `-- name: ListSavedUsersForUser :many
WITH buddy_counts AS (
  SELECT app_user_id, COUNT(*)::bigint AS buddy_count
  FROM (
    SELECT app_user_id_a AS app_user_id FROM buddies
    UNION ALL
    SELECT app_user_id_b AS app_user_id FROM buddies
  ) pairs
  GROUP BY app_user_id
),
report_counts AS (
  SELECT target_app_user_id AS user_id, COUNT(*)::bigint AS report_count
  FROM reports
  WHERE target_app_user_id IS NOT NULL
  GROUP BY target_app_user_id
)
SELECT
  u.id AS user_id,
  u.username,
  u.display_name,
  u.email_verified,
  u.phone_verified,
  COALESCE(p.avatar_url, '') AS avatar_url,
  COALESCE(p.home_area, p.location, '') AS home_area,
  COALESCE(p.cert_level, '') AS cert_level,
  COALESCE(bc.buddy_count, 0)::bigint AS buddy_count,
  COALESCE(rc.report_count, 0)::bigint AS report_count,
  su.created_at AS saved_at
FROM saved_users su
JOIN users u ON u.id = su.saved_app_user_id
LEFT JOIN profiles p ON p.user_id = u.id
LEFT JOIN buddy_counts bc ON bc.app_user_id = u.id
LEFT JOIN report_counts rc ON rc.user_id = u.id
WHERE su.viewer_app_user_id = $1
  AND u.account_status = 'active'
  AND NOT EXISTS (
    SELECT 1
    FROM user_blocks b
    WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = u.id)
       OR (b.blocker_app_user_id = u.id AND b.blocked_app_user_id = $1)
  )
ORDER BY su.created_at DESC, u.id DESC
`

type ListSavedUsersForUserRow struct {
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Username      string             `db:"username" json:"username"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	PhoneVerified bool               `db:"phone_verified" json:"phone_verified"`
	AvatarUrl     string             `db:"avatar_url" json:"avatar_url"`
	HomeArea      string             `db:"home_area" json:"home_area"`
	CertLevel     string             `db:"cert_level" json:"cert_level"`
	BuddyCount    int64              `db:"buddy_count" json:"buddy_count"`
	ReportCount   int64              `db:"report_count" json:"report_count"`
	SavedAt       pgtype.Timestamptz `db:"saved_at" json:"saved_at"`
}

func (q *Queries) ListSavedUsersForUser(ctx context.Context, viewerAppUserID pgtype.UUID) ([]ListSavedUsersForUserRow, error) {
	rows, err := q.db.Query(ctx, listSavedUsersForUser, viewerAppUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedUsersForUserRow{}
	for rows.Next() {
		var i ListSavedUsersForUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.EmailVerified,
			&i.PhoneVerified,
			&i.AvatarUrl,
			&i.HomeArea,
			&i.CertLevel,
			&i.BuddyCount,
			&i.ReportCount,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT
  u.id AS user_id,
  u.username,
  u.display_name,
  COALESCE(p.avatar_url, '') AS avatar_url,
  COALESCE(p.home_area, p.location, '') AS location
FROM users u
LEFT JOIN profiles p ON p.user_id = u.id
WHERE u.id <> $1
  AND u.account_status = 'active'
  AND (
    lower(u.username) LIKE lower($2) || '%'
    OR lower(u.display_name) LIKE '%' || lower($2) || '%'
  )
ORDER BY
  CASE WHEN lower(u.username) LIKE lower($2) || '%' THEN 0 ELSE 1 END,
  lower(u.display_name),
  lower(u.username)
LIMIT $3
`

type SearchUsersParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Q         string      `db:"q" json:"q"`
	LimitRows int32       `db:"limit_rows" json:"limit_rows"`
}

type SearchUsersRow struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	Username    string      `db:"username" json:"username"`
	DisplayName string      `db:"display_name" json:"display_name"`
	AvatarUrl   string      `db:"avatar_url" json:"avatar_url"`
	Location    string      `db:"location" json:"location"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.ID, arg.Q, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisplayName = `-- name: UpdateDisplayName :exec
UPDATE users
SET display_name = $2
WHERE id = $1
`

type UpdateDisplayNameParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	return err
}

const upsertMyProfile = `-- name: UpsertMyProfile :one
INSERT INTO profiles (user_id, bio, avatar_url, location, home_area, interests, cert_level, socials, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (user_id) DO UPDATE
SET
  bio = EXCLUDED.bio,
  avatar_url = EXCLUDED.avatar_url,
  location = EXCLUDED.location,
  home_area = EXCLUDED.home_area,
  interests = EXCLUDED.interests,
  cert_level = EXCLUDED.cert_level,
  socials = EXCLUDED.socials,
  updated_at = NOW()
RETURNING
  user_id,
  bio,
  avatar_url,
  location,
  home_area,
  interests,
  cert_level,
  socials,
  updated_at
`

type UpsertMyProfileParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	Bio       string      `db:"bio" json:"bio"`
	AvatarUrl string      `db:"avatar_url" json:"avatar_url"`
	Location  string      `db:"location" json:"location"`
	HomeArea  string      `db:"home_area" json:"home_area"`
	Interests []string    `db:"interests" json:"interests"`
	CertLevel *string     `db:"cert_level" json:"cert_level"`
	Socials   []byte      `db:"socials" json:"socials"`
}

type UpsertMyProfileRow struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Bio       string             `db:"bio" json:"bio"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
	Location  string             `db:"location" json:"location"`
	HomeArea  string             `db:"home_area" json:"home_area"`
	Interests []string           `db:"interests" json:"interests"`
	CertLevel *string            `db:"cert_level" json:"cert_level"`
	Socials   []byte             `db:"socials" json:"socials"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertMyProfile(ctx context.Context, arg UpsertMyProfileParams) (UpsertMyProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertMyProfile,
		arg.UserID,
		arg.Bio,
		arg.AvatarUrl,
		arg.Location,
		arg.HomeArea,
		arg.Interests,
		arg.CertLevel,
		arg.Socials,
	)
	var i UpsertMyProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Bio,
		&i.AvatarUrl,
		&i.Location,
		&i.HomeArea,
		&i.Interests,
		&i.CertLevel,
		&i.Socials,
		&i.UpdatedAt,
	)
	return i, err
}
