// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package profilesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT
  u.id AS user_id,
  u.username,
  u.display_name,
  p.bio,
  p.avatar_url,
  p.location,
  p.socials,
  p.updated_at
FROM users u
JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1
`

type GetProfileByUserIDRow struct {
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Bio         string             `db:"bio" json:"bio"`
	AvatarUrl   string             `db:"avatar_url" json:"avatar_url"`
	Location    string             `db:"location" json:"location"`
	Socials     []byte             `db:"socials" json:"socials"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetProfileByUserID(ctx context.Context, id pgtype.UUID) (GetProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, id)
	var i GetProfileByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Location,
		&i.Socials,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT
  u.id AS user_id,
  u.username,
  u.display_name,
  COALESCE(p.avatar_url, '') AS avatar_url,
  COALESCE(p.location, '') AS location
FROM users u
LEFT JOIN profiles p ON p.user_id = u.id
WHERE u.id <> $1
  AND u.account_status = 'active'
  AND (
    lower(u.username) LIKE lower($2) || '%'
    OR lower(u.display_name) LIKE '%' || lower($2) || '%'
  )
ORDER BY
  CASE WHEN lower(u.username) LIKE lower($2) || '%' THEN 0 ELSE 1 END,
  lower(u.display_name),
  lower(u.username)
LIMIT $3
`

type SearchUsersParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Q         string      `db:"q" json:"q"`
	LimitRows int32       `db:"limit_rows" json:"limit_rows"`
}

type SearchUsersRow struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	Username    string      `db:"username" json:"username"`
	DisplayName string      `db:"display_name" json:"display_name"`
	AvatarUrl   string      `db:"avatar_url" json:"avatar_url"`
	Location    string      `db:"location" json:"location"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.ID, arg.Q, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisplayName = `-- name: UpdateDisplayName :exec
UPDATE users
SET display_name = $2
WHERE id = $1
`

type UpdateDisplayNameParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	return err
}

const upsertMyProfile = `-- name: UpsertMyProfile :one
INSERT INTO profiles (user_id, bio, avatar_url, location, socials, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (user_id) DO UPDATE
SET
  bio = EXCLUDED.bio,
  avatar_url = EXCLUDED.avatar_url,
  location = EXCLUDED.location,
  socials = EXCLUDED.socials,
  updated_at = NOW()
RETURNING
  user_id,
  bio,
  avatar_url,
  location,
  socials,
  updated_at
`

type UpsertMyProfileParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	Bio       string      `db:"bio" json:"bio"`
	AvatarUrl string      `db:"avatar_url" json:"avatar_url"`
	Location  string      `db:"location" json:"location"`
	Socials   []byte      `db:"socials" json:"socials"`
}

type UpsertMyProfileRow struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Bio       string             `db:"bio" json:"bio"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
	Location  string             `db:"location" json:"location"`
	Socials   []byte             `db:"socials" json:"socials"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertMyProfile(ctx context.Context, arg UpsertMyProfileParams) (UpsertMyProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertMyProfile,
		arg.UserID,
		arg.Bio,
		arg.AvatarUrl,
		arg.Location,
		arg.Socials,
	)
	var i UpsertMyProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Bio,
		&i.AvatarUrl,
		&i.Location,
		&i.Socials,
		&i.UpdatedAt,
	)
	return i, err
}
