import { getDiveSpotSlug, type DiveSpot } from "./types";

type MockDiveSpotSeed = Pick<
  DiveSpot,
  "id" | "name" | "area" | "lat" | "lng" | "rating" | "reviewCount" | "tags"
>;

const MOCK_EXPLORE_SPOT_SEEDS: MockDiveSpotSeed[] = [
  {
    id: "anilao-cathedral",
    name: "Cathedral Rock",
    area: "Anilao, Batangas",
    lat: 13.757,
    lng: 120.912,
    rating: 4.8,
    reviewCount: 183,
    tags: ["Boat", "Reef", "Photography"],
  },
  {
    id: "anilao-secret-bay",
    name: "Secret Bay",
    area: "Anilao, Batangas",
    lat: 13.7582,
    lng: 120.9052,
    rating: 4.7,
    reviewCount: 141,
    tags: ["Macro", "Beginner", "Boat"],
  },
  {
    id: "coron-barracuda",
    name: "Barracuda Lake Entrance",
    area: "Coron, Palawan",
    lat: 11.9825,
    lng: 120.1996,
    rating: 4.9,
    reviewCount: 228,
    tags: ["Deep", "Training", "Boat"],
  },
  {
    id: "coron-east-tangat",
    name: "East Tangat Wall",
    area: "Coron, Palawan",
    lat: 11.9911,
    lng: 120.1432,
    rating: 4.6,
    reviewCount: 96,
    tags: ["Wall", "Boat", "Reef"],
  },
  {
    id: "apo-island-rock-point",
    name: "Rock Point West",
    area: "Apo Island, Negros Oriental",
    lat: 9.072,
    lng: 123.2708,
    rating: 4.9,
    reviewCount: 267,
    tags: ["Reef", "Boat", "Drift"],
  },
  {
    id: "apo-island-chapel",
    name: "Chapel Point",
    area: "Apo Island, Negros Oriental",
    lat: 9.0744,
    lng: 123.2683,
    rating: 4.7,
    reviewCount: 132,
    tags: ["Beginner", "Reef", "Photography"],
  },
  {
    id: "balicasag-black-forest",
    name: "Black Forest Edge",
    area: "Balicasag, Bohol",
    lat: 9.5175,
    lng: 123.6832,
    rating: 4.8,
    reviewCount: 201,
    tags: ["Wall", "Boat", "Deep"],
  },
  {
    id: "balicasag-divers-heaven",
    name: "Diver's Heaven",
    area: "Balicasag, Bohol",
    lat: 9.5161,
    lng: 123.6854,
    rating: 4.6,
    reviewCount: 119,
    tags: ["Beginner", "Reef", "Boat"],
  },
  {
    id: "moalboal-sardines",
    name: "Sardine Run Drop",
    area: "Moalboal, Cebu",
    lat: 9.9435,
    lng: 123.3797,
    rating: 4.8,
    reviewCount: 312,
    tags: ["Wall", "Drift", "Photography"],
  },
  {
    id: "pescador-east",
    name: "Pescador East",
    area: "Moalboal, Cebu",
    lat: 9.8863,
    lng: 123.3377,
    rating: 4.7,
    reviewCount: 154,
    tags: ["Boat", "Reef", "Deep"],
  },
  {
    id: "siquijor-tulapos",
    name: "Tulapos Marine Shelf",
    area: "Siquijor",
    lat: 9.2181,
    lng: 123.5532,
    rating: 4.5,
    reviewCount: 71,
    tags: ["Reef", "Beginner", "Boat"],
  },
  {
    id: "siquijor-paliton",
    name: "Paliton Blue Edge",
    area: "Siquijor",
    lat: 9.1658,
    lng: 123.4708,
    rating: 4.6,
    reviewCount: 88,
    tags: ["Photography", "Reef", "Boat"],
  },
  {
    id: "camiguin-mantigue",
    name: "Mantigue Sanctuary",
    area: "Camiguin",
    lat: 9.2776,
    lng: 124.7642,
    rating: 4.7,
    reviewCount: 103,
    tags: ["Reef", "Boat", "Beginner"],
  },
  {
    id: "camiguin-old-volcano",
    name: "Old Volcano Slope",
    area: "Camiguin",
    lat: 9.1934,
    lng: 124.7189,
    rating: 4.4,
    reviewCount: 43,
    tags: ["Deep", "Drift", "Boat"],
  },
  {
    id: "puerto-galera-canyons",
    name: "The Canyons",
    area: "Puerto Galera, Mindoro",
    lat: 13.5089,
    lng: 120.9614,
    rating: 4.8,
    reviewCount: 247,
    tags: ["Drift", "Boat", "Wall"],
  },
  {
    id: "puerto-galera-sabang",
    name: "Sabang Wreck Line",
    area: "Puerto Galera, Mindoro",
    lat: 13.5196,
    lng: 120.9678,
    rating: 4.5,
    reviewCount: 90,
    tags: ["Wreck", "Boat", "Photography"],
  },
  {
    id: "dauin-san-miguel",
    name: "San Miguel House Reef",
    area: "Dauin, Negros Oriental",
    lat: 9.1914,
    lng: 123.2643,
    rating: 4.7,
    reviewCount: 173,
    tags: ["Macro", "Reef", "Beginner"],
  },
  {
    id: "dauin-luca",
    name: "Luca Sanctuary",
    area: "Dauin, Negros Oriental",
    lat: 9.1647,
    lng: 123.2488,
    rating: 4.8,
    reviewCount: 158,
    tags: ["Macro", "Photography", "Boat"],
  },
  {
    id: "subic-el-capitan",
    name: "El Capitan Access",
    area: "Subic Bay, Zambales",
    lat: 14.7908,
    lng: 120.2424,
    rating: 4.6,
    reviewCount: 110,
    tags: ["Wreck", "Training", "Boat"],
  },
  {
    id: "subic-tribal",
    name: "Tribal Point",
    area: "Subic Bay, Zambales",
    lat: 14.8114,
    lng: 120.2305,
    rating: 4.3,
    reviewCount: 49,
    tags: ["Training", "Beginner", "Reef"],
  },
  {
    id: "boracay-yapak",
    name: "Yapak Pinnacle",
    area: "Boracay, Aklan",
    lat: 11.9981,
    lng: 121.8975,
    rating: 4.7,
    reviewCount: 138,
    tags: ["Wall", "Boat", "Deep"],
  },
  {
    id: "boracay-crocodile",
    name: "Crocodile Shelf",
    area: "Boracay, Aklan",
    lat: 11.9595,
    lng: 121.9057,
    rating: 4.4,
    reviewCount: 54,
    tags: ["Reef", "Boat", "Beginner"],
  },
  {
    id: "siargao-club-tara",
    name: "Club Tara Drop",
    area: "Siargao, Surigao del Norte",
    lat: 9.9011,
    lng: 126.1475,
    rating: 4.8,
    reviewCount: 77,
    tags: ["Boat", "Wall", "Photography"],
  },
  {
    id: "siargao-pilar",
    name: "Pilar Reef Channel",
    area: "Siargao, Surigao del Norte",
    lat: 9.8734,
    lng: 126.0621,
    rating: 4.5,
    reviewCount: 39,
    tags: ["Drift", "Reef", "Boat"],
  },
];

export const MOCK_EXPLORE_SPOTS: DiveSpot[] = MOCK_EXPLORE_SPOT_SEEDS.map(
  (spot) => ({
    ...spot,
    slug: spot.id,
    difficulty: "moderate",
    verificationStatus: "community",
    recentUpdateCount: 0,
    isSaved: false,
  }),
);

export const getMockDiveSpotBySlug = (slug: string) =>
  MOCK_EXPLORE_SPOTS.find((spot) => getDiveSpotSlug(spot) === slug) ?? null;
