variable "aws_region" {}
variable "environment" {}
variable "project" {}
variable "aws_project_name" {}
variable "module_networking_main_id" {}
variable "module_networking_subnet1_id" {}
variable "module_networking_subnet2_id" {}
variable "module_networking_ecs_express_sg_id" {}
variable "module_networking_ecs_nextjs_sg_id" {}
variable "module_networking_lb_target_group_nextjs_tg_id" {}
