// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chikaqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	BlockerID pgtype.UUID        `db:"blocker_id" json:"blocker_id"`
	BlockedID pgtype.UUID        `db:"blocked_id" json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BuddyRelationship struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	BuddyID   pgtype.UUID        `db:"buddy_id" json:"buddy_id"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ChikaPost struct {
	ID           int64              `db:"id" json:"id"`
	ThreadID     pgtype.UUID        `db:"thread_id" json:"thread_id"`
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	Pseudonym    string             `db:"pseudonym" json:"pseudonym"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ChikaThread struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Conversation struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Kind            string             `db:"kind" json:"kind"`
	DmPairKey       string             `db:"dm_pair_key" json:"dm_pair_key"`
	InitiatorUserID pgtype.UUID        `db:"initiator_user_id" json:"initiator_user_id"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ConversationParticipant struct {
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	LastReadAt     pgtype.Timestamptz `db:"last_read_at" json:"last_read_at"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type DiveSite struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Location        string             `db:"location" json:"location"`
	ModerationState string             `db:"moderation_state" json:"moderation_state"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Message struct {
	ID             int64              `db:"id" json:"id"`
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	SenderUserID   pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Content        string             `db:"content" json:"content"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Profile struct {
	UserID              pgtype.UUID        `db:"user_id" json:"user_id"`
	Bio                 string             `db:"bio" json:"bio"`
	AvatarUrl           string             `db:"avatar_url" json:"avatar_url"`
	PseudonymousEnabled bool               `db:"pseudonymous_enabled" json:"pseudonymous_enabled"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Username           string             `db:"username" json:"username"`
	DisplayName        string             `db:"display_name" json:"display_name"`
	AuthProvider       string             `db:"auth_provider" json:"auth_provider"`
	AuthProviderUserID *string            `db:"auth_provider_user_id" json:"auth_provider_user_id"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
