// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messaging.sql

package messagingqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationParticipant = `-- name: AddConversationParticipant :exec
INSERT INTO conversation_participants (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT (conversation_id, user_id) DO NOTHING
`

type AddConversationParticipantParams struct {
	ConversationID pgtype.UUID `db:"conversation_id" json:"conversation_id"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) AddConversationParticipant(ctx context.Context, arg AddConversationParticipantParams) error {
	_, err := q.db.Exec(ctx, addConversationParticipant, arg.ConversationID, arg.UserID)
	return err
}

const areBuddies = `-- name: AreBuddies :one
SELECT EXISTS (
  SELECT 1 FROM buddy_relationships
  WHERE status = 'accepted'
    AND ((user_id = $1 AND buddy_id = $2) OR (user_id = $2 AND buddy_id = $1))
)
`

type AreBuddiesParams struct {
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	BuddyID pgtype.UUID `db:"buddy_id" json:"buddy_id"`
}

func (q *Queries) AreBuddies(ctx context.Context, arg AreBuddiesParams) (bool, error) {
	row := q.db.QueryRow(ctx, areBuddies, arg.UserID, arg.BuddyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, kind, dm_pair_key, initiator_user_id, status, created_at, updated_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DmPairKey,
		&i.InitiatorUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inbox = `-- name: Inbox :many
SELECT
  m.conversation_id,
  m.id,
  m.sender_user_id,
  m.content,
  c.status,
  m.created_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
JOIN conversation_participants cp ON cp.conversation_id = c.id
JOIN conversation_participants other_cp ON other_cp.conversation_id = c.id AND other_cp.user_id <> $1
WHERE cp.user_id = $1
  AND c.status = 'active'
  AND NOT EXISTS (
    SELECT 1
    FROM user_blocks b
    WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = other_cp.user_id)
       OR (b.blocker_app_user_id = other_cp.user_id AND b.blocked_app_user_id = $1)
  )
ORDER BY m.created_at DESC
LIMIT 100
`

type InboxRow struct {
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	ID             int64              `db:"id" json:"id"`
	SenderUserID   pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Content        string             `db:"content" json:"content"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) Inbox(ctx context.Context, userID pgtype.UUID) ([]InboxRow, error) {
	rows, err := q.db.Query(ctx, inbox, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxRow{}
	for rows.Next() {
		var i InboxRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ID,
			&i.SenderUserID,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (conversation_id, sender_user_id, content)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertMessageParams struct {
	ConversationID pgtype.UUID `db:"conversation_id" json:"conversation_id"`
	SenderUserID   pgtype.UUID `db:"sender_user_id" json:"sender_user_id"`
	Content        string      `db:"content" json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.ConversationID, arg.SenderUserID, arg.Content)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const isBlockedEither = `-- name: IsBlockedEither :one
SELECT EXISTS (
  SELECT 1 FROM user_blocks
  WHERE (blocker_app_user_id = $1 AND blocked_app_user_id = $2)
     OR (blocker_app_user_id = $2 AND blocked_app_user_id = $1)
)
`

type IsBlockedEitherParams struct {
	BlockerAppUserID pgtype.UUID `db:"blocker_app_user_id" json:"blocker_app_user_id"`
	BlockedAppUserID pgtype.UUID `db:"blocked_app_user_id" json:"blocked_app_user_id"`
}

func (q *Queries) IsBlockedEither(ctx context.Context, arg IsBlockedEitherParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedEither, arg.BlockerAppUserID, arg.BlockedAppUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS (
  SELECT 1 FROM conversation_participants
  WHERE conversation_id = $1 AND user_id = $2
)
`

type IsParticipantParams struct {
	ConversationID pgtype.UUID `db:"conversation_id" json:"conversation_id"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const requests = `-- name: Requests :many
SELECT
  m.conversation_id,
  m.id,
  m.sender_user_id,
  m.content,
  c.status,
  m.created_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
JOIN conversation_participants cp ON cp.conversation_id = c.id
JOIN conversation_participants other_cp ON other_cp.conversation_id = c.id AND other_cp.user_id <> $1
WHERE cp.user_id = $1
  AND c.status = 'pending'
  AND c.initiator_user_id <> $1
  AND NOT EXISTS (
    SELECT 1
    FROM user_blocks b
    WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = other_cp.user_id)
       OR (b.blocker_app_user_id = other_cp.user_id AND b.blocked_app_user_id = $1)
  )
ORDER BY m.created_at DESC
LIMIT 100
`

type RequestsRow struct {
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	ID             int64              `db:"id" json:"id"`
	SenderUserID   pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Content        string             `db:"content" json:"content"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) Requests(ctx context.Context, userID pgtype.UUID) ([]RequestsRow, error) {
	rows, err := q.db.Query(ctx, requests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestsRow{}
	for rows.Next() {
		var i RequestsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ID,
			&i.SenderUserID,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationStatus = `-- name: SetConversationStatus :exec
UPDATE conversations
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type SetConversationStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) SetConversationStatus(ctx context.Context, arg SetConversationStatusParams) error {
	_, err := q.db.Exec(ctx, setConversationStatus, arg.ID, arg.Status)
	return err
}

const upsertDMConversation = `-- name: UpsertDMConversation :one
INSERT INTO conversations (id, kind, dm_pair_key, initiator_user_id, status)
VALUES ($1, 'dm', $2, $3, $4)
ON CONFLICT (dm_pair_key)
DO UPDATE SET status = CASE WHEN conversations.status = 'active' THEN 'active' ELSE EXCLUDED.status END,
              updated_at = NOW()
RETURNING id, kind, dm_pair_key, initiator_user_id, status, created_at, updated_at
`

type UpsertDMConversationParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	DmPairKey       string      `db:"dm_pair_key" json:"dm_pair_key"`
	InitiatorUserID pgtype.UUID `db:"initiator_user_id" json:"initiator_user_id"`
	Status          string      `db:"status" json:"status"`
}

func (q *Queries) UpsertDMConversation(ctx context.Context, arg UpsertDMConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, upsertDMConversation,
		arg.ID,
		arg.DmPairKey,
		arg.InitiatorUserID,
		arg.Status,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DmPairKey,
		&i.InitiatorUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
