import type { GlobalRole } from "./roles";

export const PERMISSION_FLAGS = [
  "users.read",
  "users.manage",
  "content.write",
  "content.read",
  "messaging.read",
  "messaging.write",
  "chika.read",
  "chika.write",
  "chika.moderate",
  "chika.reveal_identity",
  "explore.read",
  "explore.submit",
  "explore.moderate",
  "profiles.read",
  "profiles.write",
  "blocks.read",
  "blocks.write",
  "buddies.read",
  "buddies.write",
  "groups.read",
  "groups.manage",
  "events.read",
  "events.manage",
  "reports.read",
  "reports.write",
  "reports.moderate",
  "moderation.read",
  "moderation.write",
  "media.read",
  "media.write",
  "notifications.read",
  "notifications.write",
] as const;

export type PermissionFlag = (typeof PERMISSION_FLAGS)[number];

export type PermissionMatrix = Record<PermissionFlag, boolean>;

export const emptyPermissions = (): PermissionMatrix =>
  Object.fromEntries(
    PERMISSION_FLAGS.map((perm) => [perm, false]),
  ) as PermissionMatrix;

const allow = (...flags: PermissionFlag[]): PermissionMatrix => {
  const matrix = emptyPermissions();
  for (const flag of flags) {
    matrix[flag] = true;
  }
  return matrix;
};

export const ROLE_CONFIGS: Record<GlobalRole, PermissionMatrix> = {
  member: allow(
    "content.read",
    "messaging.read",
    "messaging.write",
    "chika.read",
    "chika.write",
    "explore.read",
    "explore.submit",
    "profiles.read",
    "profiles.write",
    "blocks.read",
    "blocks.write",
    "buddies.read",
    "buddies.write",
    "reports.write",
    "media.read",
    "media.write",
    "notifications.read",
    "notifications.write",
  ),
  trusted_member: allow(
    "content.read",
    "messaging.read",
    "messaging.write",
    "chika.read",
    "chika.write",
    "explore.read",
    "explore.submit",
    "profiles.read",
    "profiles.write",
    "blocks.read",
    "blocks.write",
    "buddies.read",
    "buddies.write",
    "reports.write",
    "media.read",
    "media.write",
    "notifications.read",
    "notifications.write",
  ),
  support: allow(
    "content.read",
    "messaging.read",
    "chika.read",
    "explore.read",
    "profiles.read",
    "profiles.write",
    "blocks.read",
    "buddies.read",
    "reports.read",
    "reports.write",
    "moderation.read",
    "media.read",
    "notifications.read",
    "notifications.write",
  ),
  moderator: allow(
    "content.read",
    "messaging.read",
    "messaging.write",
    "chika.read",
    "chika.write",
    "chika.moderate",
    "chika.reveal_identity",
    "explore.read",
    "explore.submit",
    "explore.moderate",
    "profiles.read",
    "profiles.write",
    "blocks.read",
    "blocks.write",
    "buddies.read",
    "buddies.write",
    "reports.read",
    "reports.write",
    "reports.moderate",
    "moderation.read",
    "moderation.write",
    "media.read",
    "media.write",
    "notifications.read",
    "notifications.write",
    "users.read",
  ),
  explore_curator: allow(
    "content.read",
    "messaging.read",
    "messaging.write",
    "chika.read",
    "chika.write",
    "explore.read",
    "explore.submit",
    "explore.moderate",
    "profiles.read",
    "profiles.write",
    "blocks.read",
    "blocks.write",
    "buddies.read",
    "buddies.write",
    "reports.write",
    "media.read",
    "media.write",
    "notifications.read",
    "notifications.write",
  ),
  records_verifier: allow(
    "content.read",
    "messaging.read",
    "messaging.write",
    "chika.read",
    "chika.write",
    "explore.read",
    "explore.submit",
    "profiles.read",
    "profiles.write",
    "blocks.read",
    "blocks.write",
    "buddies.read",
    "buddies.write",
    "reports.write",
    "media.read",
    "media.write",
    "notifications.read",
    "notifications.write",
  ),
  admin: allow(...PERMISSION_FLAGS),
  super_admin: allow(...PERMISSION_FLAGS),
};
