// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package mediaqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaObject = `-- name: CreateMediaObject :one
INSERT INTO media_objects (
  owner_app_user_id,
  context_type,
  context_id,
  object_key,
  mime_type,
  size_bytes,
  width,
  height,
  state
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
`

type CreateMediaObjectParams struct {
	OwnerAppUserID pgtype.UUID `db:"owner_app_user_id" json:"owner_app_user_id"`
	ContextType    string      `db:"context_type" json:"context_type"`
	ContextID      pgtype.UUID `db:"context_id" json:"context_id"`
	ObjectKey      string      `db:"object_key" json:"object_key"`
	MimeType       string      `db:"mime_type" json:"mime_type"`
	SizeBytes      int64       `db:"size_bytes" json:"size_bytes"`
	Width          int32       `db:"width" json:"width"`
	Height         int32       `db:"height" json:"height"`
	State          string      `db:"state" json:"state"`
}

func (q *Queries) CreateMediaObject(ctx context.Context, arg CreateMediaObjectParams) (MediaObject, error) {
	row := q.db.QueryRow(ctx, createMediaObject,
		arg.OwnerAppUserID,
		arg.ContextType,
		arg.ContextID,
		arg.ObjectKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.State,
	)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerAppUserID,
		&i.ContextType,
		&i.ContextID,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaObjectByID = `-- name: GetMediaObjectByID :one
SELECT id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
FROM media_objects
WHERE id = $1
`

func (q *Queries) GetMediaObjectByID(ctx context.Context, id pgtype.UUID) (MediaObject, error) {
	row := q.db.QueryRow(ctx, getMediaObjectByID, id)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerAppUserID,
		&i.ContextType,
		&i.ContextID,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaObjectsByIDs = `-- name: GetMediaObjectsByIDs :many
SELECT id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
FROM media_objects
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetMediaObjectsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]MediaObject, error) {
	rows, err := q.db.Query(ctx, getMediaObjectsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaObject{}
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAppUserID,
			&i.ContextType,
			&i.ContextID,
			&i.ObjectKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByContext = `-- name: ListMediaByContext :many
SELECT id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
FROM media_objects m
WHERE m.context_type = $1
  AND m.context_id IS NOT DISTINCT FROM $2
  AND (m.created_at < $3 OR (m.created_at = $3 AND m.id < $4))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5
`

type ListMediaByContextParams struct {
	ContextType string             `db:"context_type" json:"context_type"`
	ContextID   pgtype.UUID        `db:"context_id" json:"context_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID          pgtype.UUID        `db:"id" json:"id"`
	Limit       int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListMediaByContext(ctx context.Context, arg ListMediaByContextParams) ([]MediaObject, error) {
	rows, err := q.db.Query(ctx, listMediaByContext,
		arg.ContextType,
		arg.ContextID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaObject{}
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAppUserID,
			&i.ContextType,
			&i.ContextID,
			&i.ObjectKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByOwner = `-- name: ListMediaByOwner :many
SELECT id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
FROM media_objects m
WHERE m.owner_app_user_id = $1
  AND (m.created_at < $2 OR (m.created_at = $2 AND m.id < $3))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type ListMediaByOwnerParams struct {
	OwnerAppUserID pgtype.UUID        `db:"owner_app_user_id" json:"owner_app_user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID             pgtype.UUID        `db:"id" json:"id"`
	Limit          int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListMediaByOwner(ctx context.Context, arg ListMediaByOwnerParams) ([]MediaObject, error) {
	rows, err := q.db.Query(ctx, listMediaByOwner,
		arg.OwnerAppUserID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaObject{}
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAppUserID,
			&i.ContextType,
			&i.ContextID,
			&i.ObjectKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaState = `-- name: UpdateMediaState :one
UPDATE media_objects
SET state = $2
WHERE id = $1
RETURNING id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
`

type UpdateMediaStateParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	State string      `db:"state" json:"state"`
}

func (q *Queries) UpdateMediaState(ctx context.Context, arg UpdateMediaStateParams) (MediaObject, error) {
	row := q.db.QueryRow(ctx, updateMediaState, arg.ID, arg.State)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerAppUserID,
		&i.ContextType,
		&i.ContextID,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}
