// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package mediaqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaItem = `-- name: CreateMediaItem :one
INSERT INTO media_items (
  post_id,
  media_object_id,
  author_app_user_id,
  upload_group_id,
  dive_site_id,
  type,
  storage_key,
  mime_type,
  width,
  height,
  duration_ms,
  caption,
  sort_order,
  status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING
  id,
  post_id,
  media_object_id,
  author_app_user_id,
  upload_group_id,
  dive_site_id,
  type,
  storage_key,
  mime_type,
  width,
  height,
  duration_ms,
  caption,
  sort_order,
  status,
  provider,
  stream_uid,
  playback_uid,
  playback_url,
  thumbnail_url,
  preview_url,
  aspect_ratio,
  has_audio,
  processing_status,
  moderation_status,
  upload_expires_at,
  ready_at,
  failed_reason,
  created_at,
  updated_at,
  deleted_at
`

type CreateMediaItemParams struct {
	PostID          pgtype.UUID `db:"post_id" json:"post_id"`
	MediaObjectID   pgtype.UUID `db:"media_object_id" json:"media_object_id"`
	AuthorAppUserID pgtype.UUID `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID   pgtype.UUID `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID      pgtype.UUID `db:"dive_site_id" json:"dive_site_id"`
	Type            string      `db:"type" json:"type"`
	StorageKey      string      `db:"storage_key" json:"storage_key"`
	MimeType        string      `db:"mime_type" json:"mime_type"`
	Width           int32       `db:"width" json:"width"`
	Height          int32       `db:"height" json:"height"`
	DurationMs      *int32      `db:"duration_ms" json:"duration_ms"`
	Caption         *string     `db:"caption" json:"caption"`
	SortOrder       int32       `db:"sort_order" json:"sort_order"`
	Status          string      `db:"status" json:"status"`
}

func (q *Queries) CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, createMediaItem,
		arg.PostID,
		arg.MediaObjectID,
		arg.AuthorAppUserID,
		arg.UploadGroupID,
		arg.DiveSiteID,
		arg.Type,
		arg.StorageKey,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.Caption,
		arg.SortOrder,
		arg.Status,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaObjectID,
		&i.AuthorAppUserID,
		&i.UploadGroupID,
		&i.DiveSiteID,
		&i.Type,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Caption,
		&i.SortOrder,
		&i.Status,
		&i.Provider,
		&i.StreamUid,
		&i.PlaybackUid,
		&i.PlaybackUrl,
		&i.ThumbnailUrl,
		&i.PreviewUrl,
		&i.AspectRatio,
		&i.HasAudio,
		&i.ProcessingStatus,
		&i.ModerationStatus,
		&i.UploadExpiresAt,
		&i.ReadyAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMediaObject = `-- name: CreateMediaObject :one
INSERT INTO media_objects (
  owner_app_user_id,
  context_type,
  context_id,
  object_key,
  mime_type,
  size_bytes,
  width,
  height,
  state
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
`

type CreateMediaObjectParams struct {
	OwnerAppUserID pgtype.UUID `db:"owner_app_user_id" json:"owner_app_user_id"`
	ContextType    string      `db:"context_type" json:"context_type"`
	ContextID      pgtype.UUID `db:"context_id" json:"context_id"`
	ObjectKey      string      `db:"object_key" json:"object_key"`
	MimeType       string      `db:"mime_type" json:"mime_type"`
	SizeBytes      int64       `db:"size_bytes" json:"size_bytes"`
	Width          int32       `db:"width" json:"width"`
	Height         int32       `db:"height" json:"height"`
	State          string      `db:"state" json:"state"`
}

func (q *Queries) CreateMediaObject(ctx context.Context, arg CreateMediaObjectParams) (MediaObject, error) {
	row := q.db.QueryRow(ctx, createMediaObject,
		arg.OwnerAppUserID,
		arg.ContextType,
		arg.ContextID,
		arg.ObjectKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.State,
	)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerAppUserID,
		&i.ContextType,
		&i.ContextID,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const createMediaPost = `-- name: CreateMediaPost :one
INSERT INTO media_posts (
  author_app_user_id,
  upload_group_id,
  dive_site_id,
  post_caption
)
VALUES ($1, $2, $3, $4)
RETURNING id, author_app_user_id, upload_group_id, dive_site_id, post_caption, created_at, updated_at, deleted_at
`

type CreateMediaPostParams struct {
	AuthorAppUserID pgtype.UUID `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID   pgtype.UUID `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID      pgtype.UUID `db:"dive_site_id" json:"dive_site_id"`
	PostCaption     *string     `db:"post_caption" json:"post_caption"`
}

func (q *Queries) CreateMediaPost(ctx context.Context, arg CreateMediaPostParams) (MediaPost, error) {
	row := q.db.QueryRow(ctx, createMediaPost,
		arg.AuthorAppUserID,
		arg.UploadGroupID,
		arg.DiveSiteID,
		arg.PostCaption,
	)
	var i MediaPost
	err := row.Scan(
		&i.ID,
		&i.AuthorAppUserID,
		&i.UploadGroupID,
		&i.DiveSiteID,
		&i.PostCaption,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMediaPostComment = `-- name: CreateMediaPostComment :one
INSERT INTO media_post_comments (media_post_id, author_user_id, body)
VALUES ($1, $2, $3)
RETURNING id, media_post_id, author_user_id, body, created_at, updated_at, deleted_at, deleted_by_user_id
`

type CreateMediaPostCommentParams struct {
	MediaPostID  pgtype.UUID `db:"media_post_id" json:"media_post_id"`
	AuthorUserID pgtype.UUID `db:"author_user_id" json:"author_user_id"`
	Body         string      `db:"body" json:"body"`
}

func (q *Queries) CreateMediaPostComment(ctx context.Context, arg CreateMediaPostCommentParams) (MediaPostComment, error) {
	row := q.db.QueryRow(ctx, createMediaPostComment, arg.MediaPostID, arg.AuthorUserID, arg.Body)
	var i MediaPostComment
	err := row.Scan(
		&i.ID,
		&i.MediaPostID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByUserID,
	)
	return i, err
}

const createMediaUploadGroup = `-- name: CreateMediaUploadGroup :one
INSERT INTO media_upload_groups (
  author_app_user_id,
  source,
  item_count
)
VALUES ($1, $2, $3)
RETURNING id, author_app_user_id, source, item_count, created_at
`

type CreateMediaUploadGroupParams struct {
	AuthorAppUserID pgtype.UUID `db:"author_app_user_id" json:"author_app_user_id"`
	Source          string      `db:"source" json:"source"`
	ItemCount       int32       `db:"item_count" json:"item_count"`
}

func (q *Queries) CreateMediaUploadGroup(ctx context.Context, arg CreateMediaUploadGroupParams) (MediaUploadGroup, error) {
	row := q.db.QueryRow(ctx, createMediaUploadGroup, arg.AuthorAppUserID, arg.Source, arg.ItemCount)
	var i MediaUploadGroup
	err := row.Scan(
		&i.ID,
		&i.AuthorAppUserID,
		&i.Source,
		&i.ItemCount,
		&i.CreatedAt,
	)
	return i, err
}

const createMomentMediaItem = `-- name: CreateMomentMediaItem :one
INSERT INTO media_items (
  post_id,
  media_object_id,
  author_app_user_id,
  upload_group_id,
  dive_site_id,
  type,
  storage_key,
  mime_type,
  width,
  height,
  duration_ms,
  caption,
  sort_order,
  status,
  provider,
  stream_uid,
  playback_uid,
  playback_url,
  thumbnail_url,
  preview_url,
  aspect_ratio,
  has_audio,
  processing_status,
  moderation_status,
  upload_expires_at,
  ready_at,
  failed_reason
)
VALUES (
  $1, $2, $3, $4, $5,
  'video', $6, $7, $8, $9, $10, $11, 0,
  $12, 'cloudflare_stream', $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
)
RETURNING
  id,
  post_id,
  media_object_id,
  author_app_user_id,
  upload_group_id,
  dive_site_id,
  type,
  storage_key,
  mime_type,
  width,
  height,
  duration_ms,
  caption,
  sort_order,
  status,
  provider,
  stream_uid,
  playback_uid,
  playback_url,
  thumbnail_url,
  preview_url,
  aspect_ratio,
  has_audio,
  processing_status,
  moderation_status,
  upload_expires_at,
  ready_at,
  failed_reason,
  created_at,
  updated_at,
  deleted_at
`

type CreateMomentMediaItemParams struct {
	PostID           pgtype.UUID        `db:"post_id" json:"post_id"`
	MediaObjectID    pgtype.UUID        `db:"media_object_id" json:"media_object_id"`
	AuthorAppUserID  pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID    pgtype.UUID        `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID       pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	StorageKey       string             `db:"storage_key" json:"storage_key"`
	MimeType         string             `db:"mime_type" json:"mime_type"`
	Width            int32              `db:"width" json:"width"`
	Height           int32              `db:"height" json:"height"`
	DurationMs       *int32             `db:"duration_ms" json:"duration_ms"`
	Caption          *string            `db:"caption" json:"caption"`
	Status           string             `db:"status" json:"status"`
	StreamUid        *string            `db:"stream_uid" json:"stream_uid"`
	PlaybackUid      *string            `db:"playback_uid" json:"playback_uid"`
	PlaybackUrl      *string            `db:"playback_url" json:"playback_url"`
	ThumbnailUrl     *string            `db:"thumbnail_url" json:"thumbnail_url"`
	PreviewUrl       *string            `db:"preview_url" json:"preview_url"`
	AspectRatio      pgtype.Numeric     `db:"aspect_ratio" json:"aspect_ratio"`
	HasAudio         *bool              `db:"has_audio" json:"has_audio"`
	ProcessingStatus string             `db:"processing_status" json:"processing_status"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	UploadExpiresAt  pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	ReadyAt          pgtype.Timestamptz `db:"ready_at" json:"ready_at"`
	FailedReason     *string            `db:"failed_reason" json:"failed_reason"`
}

func (q *Queries) CreateMomentMediaItem(ctx context.Context, arg CreateMomentMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, createMomentMediaItem,
		arg.PostID,
		arg.MediaObjectID,
		arg.AuthorAppUserID,
		arg.UploadGroupID,
		arg.DiveSiteID,
		arg.StorageKey,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.Caption,
		arg.Status,
		arg.StreamUid,
		arg.PlaybackUid,
		arg.PlaybackUrl,
		arg.ThumbnailUrl,
		arg.PreviewUrl,
		arg.AspectRatio,
		arg.HasAudio,
		arg.ProcessingStatus,
		arg.ModerationStatus,
		arg.UploadExpiresAt,
		arg.ReadyAt,
		arg.FailedReason,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaObjectID,
		&i.AuthorAppUserID,
		&i.UploadGroupID,
		&i.DiveSiteID,
		&i.Type,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Caption,
		&i.SortOrder,
		&i.Status,
		&i.Provider,
		&i.StreamUid,
		&i.PlaybackUid,
		&i.PlaybackUrl,
		&i.ThumbnailUrl,
		&i.PreviewUrl,
		&i.AspectRatio,
		&i.HasAudio,
		&i.ProcessingStatus,
		&i.ModerationStatus,
		&i.UploadExpiresAt,
		&i.ReadyAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMomentMediaPost = `-- name: CreateMomentMediaPost :one
INSERT INTO media_posts (
  author_app_user_id,
  upload_group_id,
  dive_site_id,
  post_caption
)
VALUES ($1, $2, $3, $4)
RETURNING id, author_app_user_id, upload_group_id, dive_site_id, post_caption, created_at, updated_at, deleted_at
`

type CreateMomentMediaPostParams struct {
	AuthorAppUserID pgtype.UUID `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID   pgtype.UUID `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID      pgtype.UUID `db:"dive_site_id" json:"dive_site_id"`
	PostCaption     *string     `db:"post_caption" json:"post_caption"`
}

func (q *Queries) CreateMomentMediaPost(ctx context.Context, arg CreateMomentMediaPostParams) (MediaPost, error) {
	row := q.db.QueryRow(ctx, createMomentMediaPost,
		arg.AuthorAppUserID,
		arg.UploadGroupID,
		arg.DiveSiteID,
		arg.PostCaption,
	)
	var i MediaPost
	err := row.Scan(
		&i.ID,
		&i.AuthorAppUserID,
		&i.UploadGroupID,
		&i.DiveSiteID,
		&i.PostCaption,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaObjectByID = `-- name: GetMediaObjectByID :one
SELECT id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
FROM media_objects
WHERE id = $1
`

func (q *Queries) GetMediaObjectByID(ctx context.Context, id pgtype.UUID) (MediaObject, error) {
	row := q.db.QueryRow(ctx, getMediaObjectByID, id)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerAppUserID,
		&i.ContextType,
		&i.ContextID,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaObjectsByIDs = `-- name: GetMediaObjectsByIDs :many
SELECT id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
FROM media_objects
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetMediaObjectsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]MediaObject, error) {
	rows, err := q.db.Query(ctx, getMediaObjectsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaObject{}
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAppUserID,
			&i.ContextType,
			&i.ContextID,
			&i.ObjectKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaPostComment = `-- name: GetMediaPostComment :one
SELECT
  c.id,
  c.media_post_id,
  c.author_user_id,
  COALESCE(u.username, '') AS author_username,
  COALESCE(NULLIF(u.display_name, ''), u.username, '') AS author_display_name,
  COALESCE(p.avatar_url, '') AS author_avatar_url,
  c.body,
  COALESCE(like_counts.like_count, 0)::bigint AS like_count,
  EXISTS (
    SELECT 1
    FROM media_post_comment_likes viewer_like
    WHERE viewer_like.comment_id = c.id
      AND viewer_like.user_id = $1
  ) AS viewer_has_liked,
  c.created_at,
  c.updated_at
FROM media_post_comments c
JOIN users u ON u.id = c.author_user_id
LEFT JOIN profiles p ON p.user_id = c.author_user_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS like_count
  FROM media_post_comment_likes mpcl
  WHERE mpcl.comment_id = c.id
) like_counts ON true
WHERE c.id = $2
  AND c.media_post_id = $3
  AND c.deleted_at IS NULL
  AND u.account_status = 'active'
`

type GetMediaPostCommentParams struct {
	ViewerUserID pgtype.UUID `db:"viewer_user_id" json:"viewer_user_id"`
	CommentID    pgtype.UUID `db:"comment_id" json:"comment_id"`
	MediaPostID  pgtype.UUID `db:"media_post_id" json:"media_post_id"`
}

type GetMediaPostCommentRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	MediaPostID       pgtype.UUID        `db:"media_post_id" json:"media_post_id"`
	AuthorUserID      pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   string             `db:"author_avatar_url" json:"author_avatar_url"`
	Body              string             `db:"body" json:"body"`
	LikeCount         int64              `db:"like_count" json:"like_count"`
	ViewerHasLiked    bool               `db:"viewer_has_liked" json:"viewer_has_liked"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMediaPostComment(ctx context.Context, arg GetMediaPostCommentParams) (GetMediaPostCommentRow, error) {
	row := q.db.QueryRow(ctx, getMediaPostComment, arg.ViewerUserID, arg.CommentID, arg.MediaPostID)
	var i GetMediaPostCommentRow
	err := row.Scan(
		&i.ID,
		&i.MediaPostID,
		&i.AuthorUserID,
		&i.AuthorUsername,
		&i.AuthorDisplayName,
		&i.AuthorAvatarUrl,
		&i.Body,
		&i.LikeCount,
		&i.ViewerHasLiked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaPostDetail = `-- name: GetMediaPostDetail :many
SELECT
  mi.id,
  mi.post_id,
  mp.post_caption,
  mi.media_object_id,
  mi.author_app_user_id,
  mi.upload_group_id,
  mi.dive_site_id,
  mi.type,
  mi.storage_key,
  mi.mime_type,
  mi.width,
  mi.height,
  mi.duration_ms,
  mi.caption,
  mi.sort_order,
  mi.status,
  mi.provider,
  mi.stream_uid,
  mi.playback_uid,
  mi.playback_url,
  mi.thumbnail_url,
  mi.preview_url,
  mi.aspect_ratio,
  mi.has_audio,
  mi.processing_status,
  mi.moderation_status,
  mi.upload_expires_at,
  mi.ready_at,
  mi.failed_reason,
  mi.created_at,
  mi.updated_at,
  mi.deleted_at,
  mp.created_at AS post_created_at,
  mp.updated_at AS post_updated_at,
  COALESCE(ds.slug, '') AS dive_site_slug,
  COALESCE(ds.name, '') AS dive_site_name,
  COALESCE(ds.area, '') AS dive_site_area,
  COALESCE(u.username, '') AS author_username,
  COALESCE(NULLIF(u.display_name, ''), u.username, '') AS author_display_name,
  COALESCE(p.avatar_url, '') AS author_avatar_url,
  COALESCE(like_counts.like_count, 0)::bigint AS like_count,
  COALESCE(comment_counts.comment_count, 0)::bigint AS comment_count,
  EXISTS (
    SELECT 1
    FROM media_post_likes viewer_like
    WHERE viewer_like.media_post_id = mp.id
      AND viewer_like.user_id = $1
  ) AS viewer_has_liked,
  EXISTS (
    SELECT 1
    FROM media_post_saves viewer_save
    WHERE viewer_save.media_post_id = mp.id
      AND viewer_save.user_id = $1
  ) AS viewer_has_saved
FROM media_items mi
JOIN media_posts mp ON mp.id = mi.post_id
JOIN users u ON u.id = mp.author_app_user_id
LEFT JOIN profiles p ON p.user_id = mp.author_app_user_id
JOIN media_objects mo ON mo.id = mi.media_object_id
LEFT JOIN dive_sites ds ON ds.id = mi.dive_site_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS like_count
  FROM media_post_likes mpl
  WHERE mpl.media_post_id = mp.id
) like_counts ON true
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS comment_count
  FROM media_post_comments mpc
  WHERE mpc.media_post_id = mp.id
    AND mpc.deleted_at IS NULL
) comment_counts ON true
WHERE mp.id = $2
  AND mp.deleted_at IS NULL
  AND u.account_status = 'active'
  AND mo.state = 'active'
  AND (mi.dive_site_id IS NULL OR ds.moderation_state = 'approved')
  AND mi.status = 'active'
  AND mi.moderation_status = 'approved'
  AND (
    mi.type = 'photo'
    OR (
      mi.type = 'video'
      AND mi.provider = 'cloudflare_stream'
      AND mi.processing_status = 'ready'
    )
  )
  AND mi.deleted_at IS NULL
  AND (
    $1::uuid IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM user_blocks b
      WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = mp.author_app_user_id)
         OR (b.blocker_app_user_id = mp.author_app_user_id AND b.blocked_app_user_id = $1)
    )
  )
ORDER BY mi.sort_order ASC, mi.created_at ASC, mi.id ASC
`

type GetMediaPostDetailParams struct {
	ViewerUserID pgtype.UUID `db:"viewer_user_id" json:"viewer_user_id"`
	MediaPostID  pgtype.UUID `db:"media_post_id" json:"media_post_id"`
}

type GetMediaPostDetailRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	PostID            pgtype.UUID        `db:"post_id" json:"post_id"`
	PostCaption       *string            `db:"post_caption" json:"post_caption"`
	MediaObjectID     pgtype.UUID        `db:"media_object_id" json:"media_object_id"`
	AuthorAppUserID   pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID     pgtype.UUID        `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID        pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Type              string             `db:"type" json:"type"`
	StorageKey        string             `db:"storage_key" json:"storage_key"`
	MimeType          string             `db:"mime_type" json:"mime_type"`
	Width             int32              `db:"width" json:"width"`
	Height            int32              `db:"height" json:"height"`
	DurationMs        *int32             `db:"duration_ms" json:"duration_ms"`
	Caption           *string            `db:"caption" json:"caption"`
	SortOrder         int32              `db:"sort_order" json:"sort_order"`
	Status            string             `db:"status" json:"status"`
	Provider          string             `db:"provider" json:"provider"`
	StreamUid         *string            `db:"stream_uid" json:"stream_uid"`
	PlaybackUid       *string            `db:"playback_uid" json:"playback_uid"`
	PlaybackUrl       *string            `db:"playback_url" json:"playback_url"`
	ThumbnailUrl      *string            `db:"thumbnail_url" json:"thumbnail_url"`
	PreviewUrl        *string            `db:"preview_url" json:"preview_url"`
	AspectRatio       pgtype.Numeric     `db:"aspect_ratio" json:"aspect_ratio"`
	HasAudio          *bool              `db:"has_audio" json:"has_audio"`
	ProcessingStatus  string             `db:"processing_status" json:"processing_status"`
	ModerationStatus  string             `db:"moderation_status" json:"moderation_status"`
	UploadExpiresAt   pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	ReadyAt           pgtype.Timestamptz `db:"ready_at" json:"ready_at"`
	FailedReason      *string            `db:"failed_reason" json:"failed_reason"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	PostCreatedAt     pgtype.Timestamptz `db:"post_created_at" json:"post_created_at"`
	PostUpdatedAt     pgtype.Timestamptz `db:"post_updated_at" json:"post_updated_at"`
	DiveSiteSlug      string             `db:"dive_site_slug" json:"dive_site_slug"`
	DiveSiteName      string             `db:"dive_site_name" json:"dive_site_name"`
	DiveSiteArea      string             `db:"dive_site_area" json:"dive_site_area"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   string             `db:"author_avatar_url" json:"author_avatar_url"`
	LikeCount         int64              `db:"like_count" json:"like_count"`
	CommentCount      int64              `db:"comment_count" json:"comment_count"`
	ViewerHasLiked    bool               `db:"viewer_has_liked" json:"viewer_has_liked"`
	ViewerHasSaved    bool               `db:"viewer_has_saved" json:"viewer_has_saved"`
}

func (q *Queries) GetMediaPostDetail(ctx context.Context, arg GetMediaPostDetailParams) ([]GetMediaPostDetailRow, error) {
	rows, err := q.db.Query(ctx, getMediaPostDetail, arg.ViewerUserID, arg.MediaPostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMediaPostDetailRow{}
	for rows.Next() {
		var i GetMediaPostDetailRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PostCaption,
			&i.MediaObjectID,
			&i.AuthorAppUserID,
			&i.UploadGroupID,
			&i.DiveSiteID,
			&i.Type,
			&i.StorageKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.Caption,
			&i.SortOrder,
			&i.Status,
			&i.Provider,
			&i.StreamUid,
			&i.PlaybackUid,
			&i.PlaybackUrl,
			&i.ThumbnailUrl,
			&i.PreviewUrl,
			&i.AspectRatio,
			&i.HasAudio,
			&i.ProcessingStatus,
			&i.ModerationStatus,
			&i.UploadExpiresAt,
			&i.ReadyAt,
			&i.FailedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PostCreatedAt,
			&i.PostUpdatedAt,
			&i.DiveSiteSlug,
			&i.DiveSiteName,
			&i.DiveSiteArea,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.LikeCount,
			&i.CommentCount,
			&i.ViewerHasLiked,
			&i.ViewerHasSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMomentMediaItemByPostForOwner = `-- name: GetMomentMediaItemByPostForOwner :one
SELECT
  id,
  post_id,
  media_object_id,
  author_app_user_id,
  upload_group_id,
  dive_site_id,
  type,
  storage_key,
  mime_type,
  width,
  height,
  duration_ms,
  caption,
  sort_order,
  status,
  provider,
  stream_uid,
  playback_uid,
  playback_url,
  thumbnail_url,
  preview_url,
  aspect_ratio,
  has_audio,
  processing_status,
  moderation_status,
  upload_expires_at,
  ready_at,
  failed_reason,
  created_at,
  updated_at,
  deleted_at
FROM media_items
WHERE post_id = $1
  AND author_app_user_id = $2
  AND type = 'video'
  AND provider = 'cloudflare_stream'
  AND deleted_at IS NULL
LIMIT 1
`

type GetMomentMediaItemByPostForOwnerParams struct {
	PostID          pgtype.UUID `db:"post_id" json:"post_id"`
	AuthorAppUserID pgtype.UUID `db:"author_app_user_id" json:"author_app_user_id"`
}

func (q *Queries) GetMomentMediaItemByPostForOwner(ctx context.Context, arg GetMomentMediaItemByPostForOwnerParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, getMomentMediaItemByPostForOwner, arg.PostID, arg.AuthorAppUserID)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaObjectID,
		&i.AuthorAppUserID,
		&i.UploadGroupID,
		&i.DiveSiteID,
		&i.Type,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Caption,
		&i.SortOrder,
		&i.Status,
		&i.Provider,
		&i.StreamUid,
		&i.PlaybackUid,
		&i.PlaybackUrl,
		&i.ThumbnailUrl,
		&i.PreviewUrl,
		&i.AspectRatio,
		&i.HasAudio,
		&i.ProcessingStatus,
		&i.ModerationStatus,
		&i.UploadExpiresAt,
		&i.ReadyAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMomentMediaItemByStreamUID = `-- name: GetMomentMediaItemByStreamUID :one
SELECT
  id,
  post_id,
  media_object_id,
  author_app_user_id,
  upload_group_id,
  dive_site_id,
  type,
  storage_key,
  mime_type,
  width,
  height,
  duration_ms,
  caption,
  sort_order,
  status,
  provider,
  stream_uid,
  playback_uid,
  playback_url,
  thumbnail_url,
  preview_url,
  aspect_ratio,
  has_audio,
  processing_status,
  moderation_status,
  upload_expires_at,
  ready_at,
  failed_reason,
  created_at,
  updated_at,
  deleted_at
FROM media_items
WHERE stream_uid = $1
  AND type = 'video'
  AND provider = 'cloudflare_stream'
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetMomentMediaItemByStreamUID(ctx context.Context, streamUid *string) (MediaItem, error) {
	row := q.db.QueryRow(ctx, getMomentMediaItemByStreamUID, streamUid)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaObjectID,
		&i.AuthorAppUserID,
		&i.UploadGroupID,
		&i.DiveSiteID,
		&i.Type,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Caption,
		&i.SortOrder,
		&i.Status,
		&i.Provider,
		&i.StreamUid,
		&i.PlaybackUid,
		&i.PlaybackUrl,
		&i.ThumbnailUrl,
		&i.PreviewUrl,
		&i.AspectRatio,
		&i.HasAudio,
		&i.ProcessingStatus,
		&i.ModerationStatus,
		&i.UploadExpiresAt,
		&i.ReadyAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVisibleMediaPostCommentLikeState = `-- name: GetVisibleMediaPostCommentLikeState :one
SELECT
  c.id,
  c.media_post_id,
  COALESCE(like_counts.like_count, 0)::bigint AS like_count,
  EXISTS (
    SELECT 1
    FROM media_post_comment_likes viewer_like
    WHERE viewer_like.comment_id = c.id
      AND viewer_like.user_id = $1
  ) AS viewer_has_liked
FROM media_post_comments c
JOIN media_posts mp ON mp.id = c.media_post_id
JOIN users post_author ON post_author.id = mp.author_app_user_id
JOIN users comment_author ON comment_author.id = c.author_user_id
JOIN dive_sites ds ON ds.id = mp.dive_site_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS like_count
  FROM media_post_comment_likes mpcl
  WHERE mpcl.comment_id = c.id
) like_counts ON true
WHERE c.id = $2
  AND c.media_post_id = $3
  AND c.deleted_at IS NULL
  AND mp.deleted_at IS NULL
  AND post_author.account_status = 'active'
  AND comment_author.account_status = 'active'
  AND ds.moderation_state = 'approved'
  AND EXISTS (
    SELECT 1
    FROM media_items mi
    JOIN media_objects mo ON mo.id = mi.media_object_id
    WHERE mi.post_id = mp.id
      AND mi.status = 'active'
      AND mi.deleted_at IS NULL
      AND mo.state = 'active'
  )
  AND (
    $1::uuid IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM user_blocks b
      WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id IN (mp.author_app_user_id, c.author_user_id))
         OR (b.blocked_app_user_id = $1 AND b.blocker_app_user_id IN (mp.author_app_user_id, c.author_user_id))
    )
  )
`

type GetVisibleMediaPostCommentLikeStateParams struct {
	ViewerUserID pgtype.UUID `db:"viewer_user_id" json:"viewer_user_id"`
	CommentID    pgtype.UUID `db:"comment_id" json:"comment_id"`
	MediaPostID  pgtype.UUID `db:"media_post_id" json:"media_post_id"`
}

type GetVisibleMediaPostCommentLikeStateRow struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	MediaPostID    pgtype.UUID `db:"media_post_id" json:"media_post_id"`
	LikeCount      int64       `db:"like_count" json:"like_count"`
	ViewerHasLiked bool        `db:"viewer_has_liked" json:"viewer_has_liked"`
}

func (q *Queries) GetVisibleMediaPostCommentLikeState(ctx context.Context, arg GetVisibleMediaPostCommentLikeStateParams) (GetVisibleMediaPostCommentLikeStateRow, error) {
	row := q.db.QueryRow(ctx, getVisibleMediaPostCommentLikeState, arg.ViewerUserID, arg.CommentID, arg.MediaPostID)
	var i GetVisibleMediaPostCommentLikeStateRow
	err := row.Scan(
		&i.ID,
		&i.MediaPostID,
		&i.LikeCount,
		&i.ViewerHasLiked,
	)
	return i, err
}

const getVisibleMediaPostSocialState = `-- name: GetVisibleMediaPostSocialState :one
SELECT
  mp.id,
  mp.author_app_user_id,
  COALESCE(u.username, '') AS author_username,
  COALESCE(NULLIF(u.display_name, ''), u.username, '') AS author_display_name,
  COALESCE(p.avatar_url, '') AS author_avatar_url,
  COALESCE(like_counts.like_count, 0)::bigint AS like_count,
  COALESCE(comment_counts.comment_count, 0)::bigint AS comment_count,
  EXISTS (
    SELECT 1
    FROM media_post_likes viewer_like
    WHERE viewer_like.media_post_id = mp.id
      AND viewer_like.user_id = $1
  ) AS viewer_has_liked,
  EXISTS (
    SELECT 1
    FROM media_post_saves viewer_save
    WHERE viewer_save.media_post_id = mp.id
      AND viewer_save.user_id = $1
  ) AS viewer_has_saved
FROM media_posts mp
JOIN users u ON u.id = mp.author_app_user_id
LEFT JOIN profiles p ON p.user_id = mp.author_app_user_id
LEFT JOIN dive_sites ds ON ds.id = mp.dive_site_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS like_count
  FROM media_post_likes mpl
  WHERE mpl.media_post_id = mp.id
) like_counts ON true
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS comment_count
  FROM media_post_comments mpc
  WHERE mpc.media_post_id = mp.id
    AND mpc.deleted_at IS NULL
) comment_counts ON true
WHERE mp.id = $2
  AND mp.deleted_at IS NULL
  AND u.account_status = 'active'
  AND (mp.dive_site_id IS NULL OR ds.moderation_state = 'approved')
  AND EXISTS (
    SELECT 1
    FROM media_items mi
    JOIN media_objects mo ON mo.id = mi.media_object_id
    WHERE mi.post_id = mp.id
      AND mi.status = 'active'
      AND mi.moderation_status = 'approved'
      AND (
        mi.type = 'photo'
        OR (
          mi.type = 'video'
          AND mi.provider = 'cloudflare_stream'
          AND mi.processing_status = 'ready'
        )
      )
      AND mi.deleted_at IS NULL
      AND mo.state = 'active'
  )
  AND (
    $1::uuid IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM user_blocks b
      WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = mp.author_app_user_id)
         OR (b.blocker_app_user_id = mp.author_app_user_id AND b.blocked_app_user_id = $1)
    )
  )
`

type GetVisibleMediaPostSocialStateParams struct {
	ViewerUserID pgtype.UUID `db:"viewer_user_id" json:"viewer_user_id"`
	MediaPostID  pgtype.UUID `db:"media_post_id" json:"media_post_id"`
}

type GetVisibleMediaPostSocialStateRow struct {
	ID                pgtype.UUID `db:"id" json:"id"`
	AuthorAppUserID   pgtype.UUID `db:"author_app_user_id" json:"author_app_user_id"`
	AuthorUsername    string      `db:"author_username" json:"author_username"`
	AuthorDisplayName string      `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   string      `db:"author_avatar_url" json:"author_avatar_url"`
	LikeCount         int64       `db:"like_count" json:"like_count"`
	CommentCount      int64       `db:"comment_count" json:"comment_count"`
	ViewerHasLiked    bool        `db:"viewer_has_liked" json:"viewer_has_liked"`
	ViewerHasSaved    bool        `db:"viewer_has_saved" json:"viewer_has_saved"`
}

func (q *Queries) GetVisibleMediaPostSocialState(ctx context.Context, arg GetVisibleMediaPostSocialStateParams) (GetVisibleMediaPostSocialStateRow, error) {
	row := q.db.QueryRow(ctx, getVisibleMediaPostSocialState, arg.ViewerUserID, arg.MediaPostID)
	var i GetVisibleMediaPostSocialStateRow
	err := row.Scan(
		&i.ID,
		&i.AuthorAppUserID,
		&i.AuthorUsername,
		&i.AuthorDisplayName,
		&i.AuthorAvatarUrl,
		&i.LikeCount,
		&i.CommentCount,
		&i.ViewerHasLiked,
		&i.ViewerHasSaved,
	)
	return i, err
}

const likeMediaPost = `-- name: LikeMediaPost :exec
INSERT INTO media_post_likes (media_post_id, user_id)
VALUES ($1, $2)
ON CONFLICT (media_post_id, user_id) DO NOTHING
`

type LikeMediaPostParams struct {
	MediaPostID pgtype.UUID `db:"media_post_id" json:"media_post_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) LikeMediaPost(ctx context.Context, arg LikeMediaPostParams) error {
	_, err := q.db.Exec(ctx, likeMediaPost, arg.MediaPostID, arg.UserID)
	return err
}

const likeMediaPostComment = `-- name: LikeMediaPostComment :exec
INSERT INTO media_post_comment_likes (comment_id, user_id)
VALUES ($1, $2)
ON CONFLICT (comment_id, user_id) DO NOTHING
`

type LikeMediaPostCommentParams struct {
	CommentID pgtype.UUID `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) LikeMediaPostComment(ctx context.Context, arg LikeMediaPostCommentParams) error {
	_, err := q.db.Exec(ctx, likeMediaPostComment, arg.CommentID, arg.UserID)
	return err
}

const listDiveSiteMoments = `-- name: ListDiveSiteMoments :many
SELECT
  mi.id,
  mi.post_id,
  mp.post_caption,
  mi.media_object_id,
  mi.author_app_user_id,
  mi.upload_group_id,
  mi.dive_site_id,
  mi.type,
  mi.storage_key,
  mi.mime_type,
  mi.width,
  mi.height,
  mi.duration_ms,
  mi.caption,
  mi.sort_order,
  mi.status,
  mi.provider,
  mi.stream_uid,
  mi.playback_uid,
  mi.playback_url,
  mi.thumbnail_url,
  mi.preview_url,
  mi.aspect_ratio,
  mi.has_audio,
  mi.processing_status,
  mi.moderation_status,
  mi.upload_expires_at,
  mi.ready_at,
  mi.failed_reason,
  mi.created_at,
  mi.updated_at,
  mi.deleted_at,
  COALESCE(ds.slug, '') AS dive_site_slug,
  COALESCE(ds.name, '') AS dive_site_name,
  COALESCE(ds.area, '') AS dive_site_area,
  COALESCE(like_counts.like_count, 0)::bigint AS like_count,
  COALESCE(comment_counts.comment_count, 0)::bigint AS comment_count,
  EXISTS (
    SELECT 1
    FROM media_post_likes viewer_like
    WHERE viewer_like.media_post_id = mp.id
      AND viewer_like.user_id = $1
  ) AS viewer_has_liked,
  EXISTS (
    SELECT 1
    FROM media_post_saves viewer_save
    WHERE viewer_save.media_post_id = mp.id
      AND viewer_save.user_id = $1
  ) AS viewer_has_saved
FROM media_items mi
JOIN media_posts mp ON mp.id = mi.post_id
JOIN media_objects mo ON mo.id = mi.media_object_id
JOIN users u ON u.id = mi.author_app_user_id
JOIN dive_sites ds ON ds.id = mi.dive_site_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS like_count
  FROM media_post_likes mpl
  WHERE mpl.media_post_id = mp.id
) like_counts ON true
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS comment_count
  FROM media_post_comments mpc
  WHERE mpc.media_post_id = mp.id
    AND mpc.deleted_at IS NULL
) comment_counts ON true
WHERE mi.dive_site_id = $2
  AND u.account_status = 'active'
  AND ds.moderation_state = 'approved'
  AND mo.state = 'active'
  AND mo.context_type = 'profile_feed'
  AND mi.status = 'active'
  AND mi.type = 'video'
  AND mi.provider = 'cloudflare_stream'
  AND mi.processing_status = 'ready'
  AND mi.moderation_status = 'approved'
  AND mi.deleted_at IS NULL
  AND mp.deleted_at IS NULL
  AND (
    $1::uuid IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM user_blocks b
      WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = mi.author_app_user_id)
         OR (b.blocker_app_user_id = mi.author_app_user_id AND b.blocked_app_user_id = $1)
    )
  )
  AND (mi.created_at < $3 OR (mi.created_at = $3 AND mi.id < $4))
ORDER BY mi.created_at DESC, mi.id DESC
LIMIT $5
`

type ListDiveSiteMomentsParams struct {
	ViewerUserID pgtype.UUID        `db:"viewer_user_id" json:"viewer_user_id"`
	DiveSiteID   pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID           pgtype.UUID        `db:"id" json:"id"`
	LimitCount   int32              `db:"limit_count" json:"limit_count"`
}

type ListDiveSiteMomentsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PostID           pgtype.UUID        `db:"post_id" json:"post_id"`
	PostCaption      *string            `db:"post_caption" json:"post_caption"`
	MediaObjectID    pgtype.UUID        `db:"media_object_id" json:"media_object_id"`
	AuthorAppUserID  pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID    pgtype.UUID        `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID       pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Type             string             `db:"type" json:"type"`
	StorageKey       string             `db:"storage_key" json:"storage_key"`
	MimeType         string             `db:"mime_type" json:"mime_type"`
	Width            int32              `db:"width" json:"width"`
	Height           int32              `db:"height" json:"height"`
	DurationMs       *int32             `db:"duration_ms" json:"duration_ms"`
	Caption          *string            `db:"caption" json:"caption"`
	SortOrder        int32              `db:"sort_order" json:"sort_order"`
	Status           string             `db:"status" json:"status"`
	Provider         string             `db:"provider" json:"provider"`
	StreamUid        *string            `db:"stream_uid" json:"stream_uid"`
	PlaybackUid      *string            `db:"playback_uid" json:"playback_uid"`
	PlaybackUrl      *string            `db:"playback_url" json:"playback_url"`
	ThumbnailUrl     *string            `db:"thumbnail_url" json:"thumbnail_url"`
	PreviewUrl       *string            `db:"preview_url" json:"preview_url"`
	AspectRatio      pgtype.Numeric     `db:"aspect_ratio" json:"aspect_ratio"`
	HasAudio         *bool              `db:"has_audio" json:"has_audio"`
	ProcessingStatus string             `db:"processing_status" json:"processing_status"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	UploadExpiresAt  pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	ReadyAt          pgtype.Timestamptz `db:"ready_at" json:"ready_at"`
	FailedReason     *string            `db:"failed_reason" json:"failed_reason"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DiveSiteSlug     string             `db:"dive_site_slug" json:"dive_site_slug"`
	DiveSiteName     string             `db:"dive_site_name" json:"dive_site_name"`
	DiveSiteArea     string             `db:"dive_site_area" json:"dive_site_area"`
	LikeCount        int64              `db:"like_count" json:"like_count"`
	CommentCount     int64              `db:"comment_count" json:"comment_count"`
	ViewerHasLiked   bool               `db:"viewer_has_liked" json:"viewer_has_liked"`
	ViewerHasSaved   bool               `db:"viewer_has_saved" json:"viewer_has_saved"`
}

func (q *Queries) ListDiveSiteMoments(ctx context.Context, arg ListDiveSiteMomentsParams) ([]ListDiveSiteMomentsRow, error) {
	rows, err := q.db.Query(ctx, listDiveSiteMoments,
		arg.ViewerUserID,
		arg.DiveSiteID,
		arg.CreatedAt,
		arg.ID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiveSiteMomentsRow{}
	for rows.Next() {
		var i ListDiveSiteMomentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PostCaption,
			&i.MediaObjectID,
			&i.AuthorAppUserID,
			&i.UploadGroupID,
			&i.DiveSiteID,
			&i.Type,
			&i.StorageKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.Caption,
			&i.SortOrder,
			&i.Status,
			&i.Provider,
			&i.StreamUid,
			&i.PlaybackUid,
			&i.PlaybackUrl,
			&i.ThumbnailUrl,
			&i.PreviewUrl,
			&i.AspectRatio,
			&i.HasAudio,
			&i.ProcessingStatus,
			&i.ModerationStatus,
			&i.UploadExpiresAt,
			&i.ReadyAt,
			&i.FailedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DiveSiteSlug,
			&i.DiveSiteName,
			&i.DiveSiteArea,
			&i.LikeCount,
			&i.CommentCount,
			&i.ViewerHasLiked,
			&i.ViewerHasSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByContext = `-- name: ListMediaByContext :many
SELECT id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
FROM media_objects m
WHERE m.context_type = $1
  AND m.context_id IS NOT DISTINCT FROM $2
  AND (m.created_at < $3 OR (m.created_at = $3 AND m.id < $4))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5
`

type ListMediaByContextParams struct {
	ContextType string             `db:"context_type" json:"context_type"`
	ContextID   pgtype.UUID        `db:"context_id" json:"context_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID          pgtype.UUID        `db:"id" json:"id"`
	Limit       int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListMediaByContext(ctx context.Context, arg ListMediaByContextParams) ([]MediaObject, error) {
	rows, err := q.db.Query(ctx, listMediaByContext,
		arg.ContextType,
		arg.ContextID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaObject{}
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAppUserID,
			&i.ContextType,
			&i.ContextID,
			&i.ObjectKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByOwner = `-- name: ListMediaByOwner :many
SELECT id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
FROM media_objects m
WHERE m.owner_app_user_id = $1
  AND (m.created_at < $2 OR (m.created_at = $2 AND m.id < $3))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type ListMediaByOwnerParams struct {
	OwnerAppUserID pgtype.UUID        `db:"owner_app_user_id" json:"owner_app_user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID             pgtype.UUID        `db:"id" json:"id"`
	Limit          int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListMediaByOwner(ctx context.Context, arg ListMediaByOwnerParams) ([]MediaObject, error) {
	rows, err := q.db.Query(ctx, listMediaByOwner,
		arg.OwnerAppUserID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaObject{}
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.ID,
			&i.OwnerAppUserID,
			&i.ContextType,
			&i.ContextID,
			&i.ObjectKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaPostComments = `-- name: ListMediaPostComments :many
SELECT
  c.id,
  c.media_post_id,
  c.author_user_id,
  COALESCE(u.username, '') AS author_username,
  COALESCE(NULLIF(u.display_name, ''), u.username, '') AS author_display_name,
  COALESCE(p.avatar_url, '') AS author_avatar_url,
  c.body,
  COALESCE(like_counts.like_count, 0)::bigint AS like_count,
  EXISTS (
    SELECT 1
    FROM media_post_comment_likes viewer_like
    WHERE viewer_like.comment_id = c.id
      AND viewer_like.user_id = $1
  ) AS viewer_has_liked,
  c.created_at,
  c.updated_at
FROM media_post_comments c
JOIN users u ON u.id = c.author_user_id
LEFT JOIN profiles p ON p.user_id = c.author_user_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS like_count
  FROM media_post_comment_likes mpcl
  WHERE mpcl.comment_id = c.id
) like_counts ON true
WHERE c.media_post_id = $2
  AND c.deleted_at IS NULL
  AND u.account_status = 'active'
  AND (c.created_at < $3 OR (c.created_at = $3 AND c.id < $4))
  AND (
    $1::uuid IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM user_blocks b
      WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = c.author_user_id)
         OR (b.blocker_app_user_id = c.author_user_id AND b.blocked_app_user_id = $1)
    )
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $5
`

type ListMediaPostCommentsParams struct {
	ViewerUserID pgtype.UUID        `db:"viewer_user_id" json:"viewer_user_id"`
	MediaPostID  pgtype.UUID        `db:"media_post_id" json:"media_post_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID           pgtype.UUID        `db:"id" json:"id"`
	LimitCount   int32              `db:"limit_count" json:"limit_count"`
}

type ListMediaPostCommentsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	MediaPostID       pgtype.UUID        `db:"media_post_id" json:"media_post_id"`
	AuthorUserID      pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	AuthorUsername    string             `db:"author_username" json:"author_username"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorAvatarUrl   string             `db:"author_avatar_url" json:"author_avatar_url"`
	Body              string             `db:"body" json:"body"`
	LikeCount         int64              `db:"like_count" json:"like_count"`
	ViewerHasLiked    bool               `db:"viewer_has_liked" json:"viewer_has_liked"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListMediaPostComments(ctx context.Context, arg ListMediaPostCommentsParams) ([]ListMediaPostCommentsRow, error) {
	rows, err := q.db.Query(ctx, listMediaPostComments,
		arg.ViewerUserID,
		arg.MediaPostID,
		arg.CreatedAt,
		arg.ID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaPostCommentsRow{}
	for rows.Next() {
		var i ListMediaPostCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaPostID,
			&i.AuthorUserID,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.LikeCount,
			&i.ViewerHasLiked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileDiveSpotHighlightsByUsername = `-- name: ListProfileDiveSpotHighlightsByUsername :many
WITH visible_items AS (
  SELECT
    mi.id,
    mi.post_id,
    mi.media_object_id,
    mi.author_app_user_id,
    mi.upload_group_id,
    mi.dive_site_id,
    mi.type,
    mi.storage_key,
    mi.mime_type,
    mi.width,
    mi.height,
    mi.duration_ms,
    mi.caption,
    mi.sort_order,
    mi.status,
    mi.provider,
    mi.stream_uid,
    mi.playback_uid,
    mi.playback_url,
    mi.thumbnail_url,
    mi.preview_url,
    mi.aspect_ratio,
    mi.has_audio,
    mi.processing_status,
    mi.moderation_status,
    mi.upload_expires_at,
    mi.ready_at,
    mi.failed_reason,
    mi.created_at,
    mi.updated_at,
    mi.deleted_at,
    mp.post_caption,
    ds.slug AS dive_site_slug,
    ds.name AS dive_site_name,
    ds.area AS dive_site_area
  FROM media_items mi
  JOIN media_posts mp ON mp.id = mi.post_id
  JOIN media_objects mo ON mo.id = mi.media_object_id
  JOIN users u ON u.id = mi.author_app_user_id
  JOIN dive_sites ds ON ds.id = mi.dive_site_id
  WHERE lower(u.username) = lower($2)
    AND u.account_status = 'active'
    AND mo.state = 'active'
    AND mo.context_type = 'profile_feed'
    AND mi.status = 'active'
    AND mi.moderation_status = 'approved'
    AND (
      mi.type = 'photo'
      OR (
        mi.type = 'video'
        AND mi.provider = 'cloudflare_stream'
        AND mi.processing_status = 'ready'
      )
    )
    AND mi.deleted_at IS NULL
    AND mp.deleted_at IS NULL
    AND ds.moderation_state = 'approved'
    AND (
      $3::uuid IS NULL
      OR NOT EXISTS (
        SELECT 1
        FROM user_blocks b
        WHERE (b.blocker_app_user_id = $3 AND b.blocked_app_user_id = mi.author_app_user_id)
           OR (b.blocker_app_user_id = mi.author_app_user_id AND b.blocked_app_user_id = $3)
      )
    )
),
ranked_covers AS (
  SELECT
    visible_items.id, visible_items.post_id, visible_items.media_object_id, visible_items.author_app_user_id, visible_items.upload_group_id, visible_items.dive_site_id, visible_items.type, visible_items.storage_key, visible_items.mime_type, visible_items.width, visible_items.height, visible_items.duration_ms, visible_items.caption, visible_items.sort_order, visible_items.status, visible_items.provider, visible_items.stream_uid, visible_items.playback_uid, visible_items.playback_url, visible_items.thumbnail_url, visible_items.preview_url, visible_items.aspect_ratio, visible_items.has_audio, visible_items.processing_status, visible_items.moderation_status, visible_items.upload_expires_at, visible_items.ready_at, visible_items.failed_reason, visible_items.created_at, visible_items.updated_at, visible_items.deleted_at, visible_items.post_caption, visible_items.dive_site_slug, visible_items.dive_site_name, visible_items.dive_site_area,
    row_number() OVER (
      PARTITION BY visible_items.dive_site_id
      ORDER BY visible_items.created_at DESC, visible_items.id DESC
    ) AS cover_rank,
    count(*) OVER (PARTITION BY visible_items.dive_site_id)::bigint AS media_count,
    max(visible_items.created_at) OVER (PARTITION BY visible_items.dive_site_id) AS latest_media_created_at
  FROM visible_items
)
SELECT
  id,
  post_id,
  post_caption,
  media_object_id,
  author_app_user_id,
  upload_group_id,
  dive_site_id,
  type,
  storage_key,
  mime_type,
  width,
  height,
  duration_ms,
  caption,
  sort_order,
  status,
  provider,
  stream_uid,
  playback_uid,
  playback_url,
  thumbnail_url,
  preview_url,
  aspect_ratio,
  has_audio,
  processing_status,
  moderation_status,
  upload_expires_at,
  ready_at,
  failed_reason,
  created_at,
  updated_at,
  deleted_at,
  dive_site_slug,
  dive_site_name,
  dive_site_area,
  media_count,
  latest_media_created_at
FROM ranked_covers
WHERE cover_rank = 1
ORDER BY latest_media_created_at DESC, dive_site_id DESC
LIMIT $1
`

type ListProfileDiveSpotHighlightsByUsernameParams struct {
	LimitCount   int32       `db:"limit_count" json:"limit_count"`
	Username     string      `db:"username" json:"username"`
	ViewerUserID pgtype.UUID `db:"viewer_user_id" json:"viewer_user_id"`
}

type ListProfileDiveSpotHighlightsByUsernameRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	PostID               pgtype.UUID        `db:"post_id" json:"post_id"`
	PostCaption          *string            `db:"post_caption" json:"post_caption"`
	MediaObjectID        pgtype.UUID        `db:"media_object_id" json:"media_object_id"`
	AuthorAppUserID      pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID        pgtype.UUID        `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID           pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Type                 string             `db:"type" json:"type"`
	StorageKey           string             `db:"storage_key" json:"storage_key"`
	MimeType             string             `db:"mime_type" json:"mime_type"`
	Width                int32              `db:"width" json:"width"`
	Height               int32              `db:"height" json:"height"`
	DurationMs           *int32             `db:"duration_ms" json:"duration_ms"`
	Caption              *string            `db:"caption" json:"caption"`
	SortOrder            int32              `db:"sort_order" json:"sort_order"`
	Status               string             `db:"status" json:"status"`
	Provider             string             `db:"provider" json:"provider"`
	StreamUid            *string            `db:"stream_uid" json:"stream_uid"`
	PlaybackUid          *string            `db:"playback_uid" json:"playback_uid"`
	PlaybackUrl          *string            `db:"playback_url" json:"playback_url"`
	ThumbnailUrl         *string            `db:"thumbnail_url" json:"thumbnail_url"`
	PreviewUrl           *string            `db:"preview_url" json:"preview_url"`
	AspectRatio          pgtype.Numeric     `db:"aspect_ratio" json:"aspect_ratio"`
	HasAudio             *bool              `db:"has_audio" json:"has_audio"`
	ProcessingStatus     string             `db:"processing_status" json:"processing_status"`
	ModerationStatus     string             `db:"moderation_status" json:"moderation_status"`
	UploadExpiresAt      pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	ReadyAt              pgtype.Timestamptz `db:"ready_at" json:"ready_at"`
	FailedReason         *string            `db:"failed_reason" json:"failed_reason"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DiveSiteSlug         string             `db:"dive_site_slug" json:"dive_site_slug"`
	DiveSiteName         string             `db:"dive_site_name" json:"dive_site_name"`
	DiveSiteArea         string             `db:"dive_site_area" json:"dive_site_area"`
	MediaCount           int64              `db:"media_count" json:"media_count"`
	LatestMediaCreatedAt interface{}        `db:"latest_media_created_at" json:"latest_media_created_at"`
}

func (q *Queries) ListProfileDiveSpotHighlightsByUsername(ctx context.Context, arg ListProfileDiveSpotHighlightsByUsernameParams) ([]ListProfileDiveSpotHighlightsByUsernameRow, error) {
	rows, err := q.db.Query(ctx, listProfileDiveSpotHighlightsByUsername, arg.LimitCount, arg.Username, arg.ViewerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileDiveSpotHighlightsByUsernameRow{}
	for rows.Next() {
		var i ListProfileDiveSpotHighlightsByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PostCaption,
			&i.MediaObjectID,
			&i.AuthorAppUserID,
			&i.UploadGroupID,
			&i.DiveSiteID,
			&i.Type,
			&i.StorageKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.Caption,
			&i.SortOrder,
			&i.Status,
			&i.Provider,
			&i.StreamUid,
			&i.PlaybackUid,
			&i.PlaybackUrl,
			&i.ThumbnailUrl,
			&i.PreviewUrl,
			&i.AspectRatio,
			&i.HasAudio,
			&i.ProcessingStatus,
			&i.ModerationStatus,
			&i.UploadExpiresAt,
			&i.ReadyAt,
			&i.FailedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DiveSiteSlug,
			&i.DiveSiteName,
			&i.DiveSiteArea,
			&i.MediaCount,
			&i.LatestMediaCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileMediaByUsername = `-- name: ListProfileMediaByUsername :many
SELECT
  mi.id,
  mi.post_id,
  mp.post_caption,
  mi.media_object_id,
  mi.author_app_user_id,
  mi.upload_group_id,
  mi.dive_site_id,
  mi.type,
  mi.storage_key,
  mi.mime_type,
  mi.width,
  mi.height,
  mi.duration_ms,
  mi.caption,
  mi.sort_order,
  mi.status,
  mi.provider,
  mi.stream_uid,
  mi.playback_uid,
  mi.playback_url,
  mi.thumbnail_url,
  mi.preview_url,
  mi.aspect_ratio,
  mi.has_audio,
  mi.processing_status,
  mi.moderation_status,
  mi.upload_expires_at,
  mi.ready_at,
  mi.failed_reason,
  mi.created_at,
  mi.updated_at,
  mi.deleted_at,
  COALESCE(ds.slug, '') AS dive_site_slug,
  COALESCE(ds.name, '') AS dive_site_name,
  COALESCE(ds.area, '') AS dive_site_area,
  COALESCE(like_counts.like_count, 0)::bigint AS like_count,
  COALESCE(comment_counts.comment_count, 0)::bigint AS comment_count,
  EXISTS (
    SELECT 1
    FROM media_post_likes viewer_like
    WHERE viewer_like.media_post_id = mp.id
      AND viewer_like.user_id = $1
  ) AS viewer_has_liked,
  EXISTS (
    SELECT 1
    FROM media_post_saves viewer_save
    WHERE viewer_save.media_post_id = mp.id
      AND viewer_save.user_id = $1
  ) AS viewer_has_saved
FROM media_items mi
JOIN media_posts mp ON mp.id = mi.post_id
JOIN media_objects mo ON mo.id = mi.media_object_id
JOIN users u ON u.id = mi.author_app_user_id
LEFT JOIN dive_sites ds
  ON ds.id = mi.dive_site_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS like_count
  FROM media_post_likes mpl
  WHERE mpl.media_post_id = mp.id
) like_counts ON true
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS comment_count
  FROM media_post_comments mpc
  WHERE mpc.media_post_id = mp.id
    AND mpc.deleted_at IS NULL
) comment_counts ON true
WHERE lower(u.username) = lower($2)
  AND u.account_status = 'active'
  AND mo.state = 'active'
  AND mo.context_type = 'profile_feed'
  AND mi.status = 'active'
  AND mi.moderation_status = 'approved'
  AND (
    mi.type = 'photo'
    OR (
      mi.type = 'video'
      AND mi.provider = 'cloudflare_stream'
      AND mi.processing_status = 'ready'
    )
  )
  AND mi.deleted_at IS NULL
  AND mp.deleted_at IS NULL
  AND (mi.dive_site_id IS NULL OR ds.moderation_state = 'approved')
  AND (
    $1::uuid IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM user_blocks b
      WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = mi.author_app_user_id)
         OR (b.blocker_app_user_id = mi.author_app_user_id AND b.blocked_app_user_id = $1)
    )
  )
  AND (mi.created_at < $3 OR (mi.created_at = $3 AND mi.id < $4))
	ORDER BY mi.created_at DESC, mi.id DESC
	LIMIT $5
`

type ListProfileMediaByUsernameParams struct {
	ViewerUserID pgtype.UUID        `db:"viewer_user_id" json:"viewer_user_id"`
	Username     string             `db:"username" json:"username"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID           pgtype.UUID        `db:"id" json:"id"`
	LimitCount   int32              `db:"limit_count" json:"limit_count"`
}

type ListProfileMediaByUsernameRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PostID           pgtype.UUID        `db:"post_id" json:"post_id"`
	PostCaption      *string            `db:"post_caption" json:"post_caption"`
	MediaObjectID    pgtype.UUID        `db:"media_object_id" json:"media_object_id"`
	AuthorAppUserID  pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID    pgtype.UUID        `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID       pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Type             string             `db:"type" json:"type"`
	StorageKey       string             `db:"storage_key" json:"storage_key"`
	MimeType         string             `db:"mime_type" json:"mime_type"`
	Width            int32              `db:"width" json:"width"`
	Height           int32              `db:"height" json:"height"`
	DurationMs       *int32             `db:"duration_ms" json:"duration_ms"`
	Caption          *string            `db:"caption" json:"caption"`
	SortOrder        int32              `db:"sort_order" json:"sort_order"`
	Status           string             `db:"status" json:"status"`
	Provider         string             `db:"provider" json:"provider"`
	StreamUid        *string            `db:"stream_uid" json:"stream_uid"`
	PlaybackUid      *string            `db:"playback_uid" json:"playback_uid"`
	PlaybackUrl      *string            `db:"playback_url" json:"playback_url"`
	ThumbnailUrl     *string            `db:"thumbnail_url" json:"thumbnail_url"`
	PreviewUrl       *string            `db:"preview_url" json:"preview_url"`
	AspectRatio      pgtype.Numeric     `db:"aspect_ratio" json:"aspect_ratio"`
	HasAudio         *bool              `db:"has_audio" json:"has_audio"`
	ProcessingStatus string             `db:"processing_status" json:"processing_status"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	UploadExpiresAt  pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	ReadyAt          pgtype.Timestamptz `db:"ready_at" json:"ready_at"`
	FailedReason     *string            `db:"failed_reason" json:"failed_reason"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DiveSiteSlug     string             `db:"dive_site_slug" json:"dive_site_slug"`
	DiveSiteName     string             `db:"dive_site_name" json:"dive_site_name"`
	DiveSiteArea     string             `db:"dive_site_area" json:"dive_site_area"`
	LikeCount        int64              `db:"like_count" json:"like_count"`
	CommentCount     int64              `db:"comment_count" json:"comment_count"`
	ViewerHasLiked   bool               `db:"viewer_has_liked" json:"viewer_has_liked"`
	ViewerHasSaved   bool               `db:"viewer_has_saved" json:"viewer_has_saved"`
}

func (q *Queries) ListProfileMediaByUsername(ctx context.Context, arg ListProfileMediaByUsernameParams) ([]ListProfileMediaByUsernameRow, error) {
	rows, err := q.db.Query(ctx, listProfileMediaByUsername,
		arg.ViewerUserID,
		arg.Username,
		arg.CreatedAt,
		arg.ID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileMediaByUsernameRow{}
	for rows.Next() {
		var i ListProfileMediaByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PostCaption,
			&i.MediaObjectID,
			&i.AuthorAppUserID,
			&i.UploadGroupID,
			&i.DiveSiteID,
			&i.Type,
			&i.StorageKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.Caption,
			&i.SortOrder,
			&i.Status,
			&i.Provider,
			&i.StreamUid,
			&i.PlaybackUid,
			&i.PlaybackUrl,
			&i.ThumbnailUrl,
			&i.PreviewUrl,
			&i.AspectRatio,
			&i.HasAudio,
			&i.ProcessingStatus,
			&i.ModerationStatus,
			&i.UploadExpiresAt,
			&i.ReadyAt,
			&i.FailedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DiveSiteSlug,
			&i.DiveSiteName,
			&i.DiveSiteArea,
			&i.LikeCount,
			&i.CommentCount,
			&i.ViewerHasLiked,
			&i.ViewerHasSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileMediaByUsernameAndDiveSite = `-- name: ListProfileMediaByUsernameAndDiveSite :many
SELECT
  mi.id,
  mi.post_id,
  mp.post_caption,
  mi.media_object_id,
  mi.author_app_user_id,
  mi.upload_group_id,
  mi.dive_site_id,
  mi.type,
  mi.storage_key,
  mi.mime_type,
  mi.width,
  mi.height,
  mi.duration_ms,
  mi.caption,
  mi.sort_order,
  mi.status,
  mi.provider,
  mi.stream_uid,
  mi.playback_uid,
  mi.playback_url,
  mi.thumbnail_url,
  mi.preview_url,
  mi.aspect_ratio,
  mi.has_audio,
  mi.processing_status,
  mi.moderation_status,
  mi.upload_expires_at,
  mi.ready_at,
  mi.failed_reason,
  mi.created_at,
  mi.updated_at,
  mi.deleted_at,
  COALESCE(ds.slug, '') AS dive_site_slug,
  COALESCE(ds.name, '') AS dive_site_name,
  COALESCE(ds.area, '') AS dive_site_area,
  COALESCE(like_counts.like_count, 0)::bigint AS like_count,
  COALESCE(comment_counts.comment_count, 0)::bigint AS comment_count,
  EXISTS (
    SELECT 1
    FROM media_post_likes viewer_like
    WHERE viewer_like.media_post_id = mp.id
      AND viewer_like.user_id = $1
  ) AS viewer_has_liked,
  EXISTS (
    SELECT 1
    FROM media_post_saves viewer_save
    WHERE viewer_save.media_post_id = mp.id
      AND viewer_save.user_id = $1
  ) AS viewer_has_saved
FROM media_items mi
JOIN media_posts mp ON mp.id = mi.post_id
JOIN media_objects mo ON mo.id = mi.media_object_id
JOIN users u ON u.id = mi.author_app_user_id
JOIN dive_sites ds ON ds.id = mi.dive_site_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS like_count
  FROM media_post_likes mpl
  WHERE mpl.media_post_id = mp.id
) like_counts ON true
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS comment_count
  FROM media_post_comments mpc
  WHERE mpc.media_post_id = mp.id
    AND mpc.deleted_at IS NULL
) comment_counts ON true
WHERE lower(u.username) = lower($2)
  AND mi.dive_site_id = $3
  AND u.account_status = 'active'
  AND mo.state = 'active'
  AND mo.context_type = 'profile_feed'
  AND mi.status = 'active'
  AND mi.moderation_status = 'approved'
  AND (
    mi.type = 'photo'
    OR (
      mi.type = 'video'
      AND mi.provider = 'cloudflare_stream'
      AND mi.processing_status = 'ready'
    )
  )
  AND mi.deleted_at IS NULL
  AND mp.deleted_at IS NULL
  AND ds.moderation_state = 'approved'
  AND (mi.created_at < $4 OR (mi.created_at = $4 AND mi.id < $5))
  AND (
    $1::uuid IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM user_blocks b
      WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = mi.author_app_user_id)
         OR (b.blocker_app_user_id = mi.author_app_user_id AND b.blocked_app_user_id = $1)
    )
  )
ORDER BY mi.created_at DESC, mi.id DESC
LIMIT $6
`

type ListProfileMediaByUsernameAndDiveSiteParams struct {
	ViewerUserID pgtype.UUID        `db:"viewer_user_id" json:"viewer_user_id"`
	Username     string             `db:"username" json:"username"`
	DiveSiteID   pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID           pgtype.UUID        `db:"id" json:"id"`
	LimitCount   int32              `db:"limit_count" json:"limit_count"`
}

type ListProfileMediaByUsernameAndDiveSiteRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PostID           pgtype.UUID        `db:"post_id" json:"post_id"`
	PostCaption      *string            `db:"post_caption" json:"post_caption"`
	MediaObjectID    pgtype.UUID        `db:"media_object_id" json:"media_object_id"`
	AuthorAppUserID  pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID    pgtype.UUID        `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID       pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Type             string             `db:"type" json:"type"`
	StorageKey       string             `db:"storage_key" json:"storage_key"`
	MimeType         string             `db:"mime_type" json:"mime_type"`
	Width            int32              `db:"width" json:"width"`
	Height           int32              `db:"height" json:"height"`
	DurationMs       *int32             `db:"duration_ms" json:"duration_ms"`
	Caption          *string            `db:"caption" json:"caption"`
	SortOrder        int32              `db:"sort_order" json:"sort_order"`
	Status           string             `db:"status" json:"status"`
	Provider         string             `db:"provider" json:"provider"`
	StreamUid        *string            `db:"stream_uid" json:"stream_uid"`
	PlaybackUid      *string            `db:"playback_uid" json:"playback_uid"`
	PlaybackUrl      *string            `db:"playback_url" json:"playback_url"`
	ThumbnailUrl     *string            `db:"thumbnail_url" json:"thumbnail_url"`
	PreviewUrl       *string            `db:"preview_url" json:"preview_url"`
	AspectRatio      pgtype.Numeric     `db:"aspect_ratio" json:"aspect_ratio"`
	HasAudio         *bool              `db:"has_audio" json:"has_audio"`
	ProcessingStatus string             `db:"processing_status" json:"processing_status"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	UploadExpiresAt  pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	ReadyAt          pgtype.Timestamptz `db:"ready_at" json:"ready_at"`
	FailedReason     *string            `db:"failed_reason" json:"failed_reason"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DiveSiteSlug     string             `db:"dive_site_slug" json:"dive_site_slug"`
	DiveSiteName     string             `db:"dive_site_name" json:"dive_site_name"`
	DiveSiteArea     string             `db:"dive_site_area" json:"dive_site_area"`
	LikeCount        int64              `db:"like_count" json:"like_count"`
	CommentCount     int64              `db:"comment_count" json:"comment_count"`
	ViewerHasLiked   bool               `db:"viewer_has_liked" json:"viewer_has_liked"`
	ViewerHasSaved   bool               `db:"viewer_has_saved" json:"viewer_has_saved"`
}

func (q *Queries) ListProfileMediaByUsernameAndDiveSite(ctx context.Context, arg ListProfileMediaByUsernameAndDiveSiteParams) ([]ListProfileMediaByUsernameAndDiveSiteRow, error) {
	rows, err := q.db.Query(ctx, listProfileMediaByUsernameAndDiveSite,
		arg.ViewerUserID,
		arg.Username,
		arg.DiveSiteID,
		arg.CreatedAt,
		arg.ID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileMediaByUsernameAndDiveSiteRow{}
	for rows.Next() {
		var i ListProfileMediaByUsernameAndDiveSiteRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PostCaption,
			&i.MediaObjectID,
			&i.AuthorAppUserID,
			&i.UploadGroupID,
			&i.DiveSiteID,
			&i.Type,
			&i.StorageKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.Caption,
			&i.SortOrder,
			&i.Status,
			&i.Provider,
			&i.StreamUid,
			&i.PlaybackUid,
			&i.PlaybackUrl,
			&i.ThumbnailUrl,
			&i.PreviewUrl,
			&i.AspectRatio,
			&i.HasAudio,
			&i.ProcessingStatus,
			&i.ModerationStatus,
			&i.UploadExpiresAt,
			&i.ReadyAt,
			&i.FailedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DiveSiteSlug,
			&i.DiveSiteName,
			&i.DiveSiteArea,
			&i.LikeCount,
			&i.CommentCount,
			&i.ViewerHasLiked,
			&i.ViewerHasSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileMomentsByUsername = `-- name: ListProfileMomentsByUsername :many
SELECT
  mi.id,
  mi.post_id,
  mp.post_caption,
  mi.media_object_id,
  mi.author_app_user_id,
  mi.upload_group_id,
  mi.dive_site_id,
  mi.type,
  mi.storage_key,
  mi.mime_type,
  mi.width,
  mi.height,
  mi.duration_ms,
  mi.caption,
  mi.sort_order,
  mi.status,
  mi.provider,
  mi.stream_uid,
  mi.playback_uid,
  mi.playback_url,
  mi.thumbnail_url,
  mi.preview_url,
  mi.aspect_ratio,
  mi.has_audio,
  mi.processing_status,
  mi.moderation_status,
  mi.upload_expires_at,
  mi.ready_at,
  mi.failed_reason,
  mi.created_at,
  mi.updated_at,
  mi.deleted_at,
  COALESCE(ds.slug, '') AS dive_site_slug,
  COALESCE(ds.name, '') AS dive_site_name,
  COALESCE(ds.area, '') AS dive_site_area,
  COALESCE(like_counts.like_count, 0)::bigint AS like_count,
  COALESCE(comment_counts.comment_count, 0)::bigint AS comment_count,
  EXISTS (
    SELECT 1
    FROM media_post_likes viewer_like
    WHERE viewer_like.media_post_id = mp.id
      AND viewer_like.user_id = $1
  ) AS viewer_has_liked,
  EXISTS (
    SELECT 1
    FROM media_post_saves viewer_save
    WHERE viewer_save.media_post_id = mp.id
      AND viewer_save.user_id = $1
  ) AS viewer_has_saved
FROM media_items mi
JOIN media_posts mp ON mp.id = mi.post_id
JOIN media_objects mo ON mo.id = mi.media_object_id
JOIN users u ON u.id = mi.author_app_user_id
LEFT JOIN dive_sites ds
  ON ds.id = mi.dive_site_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS like_count
  FROM media_post_likes mpl
  WHERE mpl.media_post_id = mp.id
) like_counts ON true
LEFT JOIN LATERAL (
  SELECT COUNT(*)::bigint AS comment_count
  FROM media_post_comments mpc
  WHERE mpc.media_post_id = mp.id
    AND mpc.deleted_at IS NULL
) comment_counts ON true
WHERE lower(u.username) = lower($2)
  AND u.account_status = 'active'
  AND mo.state = 'active'
  AND mo.context_type = 'profile_feed'
  AND mi.status = 'active'
  AND mi.type = 'video'
  AND mi.provider = 'cloudflare_stream'
  AND mi.processing_status = 'ready'
  AND mi.moderation_status = 'approved'
  AND mi.deleted_at IS NULL
  AND mp.deleted_at IS NULL
  AND (mi.dive_site_id IS NULL OR ds.moderation_state = 'approved')
  AND (
    $1::uuid IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM user_blocks b
      WHERE (b.blocker_app_user_id = $1 AND b.blocked_app_user_id = mi.author_app_user_id)
         OR (b.blocker_app_user_id = mi.author_app_user_id AND b.blocked_app_user_id = $1)
    )
  )
  AND (mi.created_at < $3 OR (mi.created_at = $3 AND mi.id < $4))
ORDER BY mi.created_at DESC, mi.id DESC
LIMIT $5
`

type ListProfileMomentsByUsernameParams struct {
	ViewerUserID pgtype.UUID        `db:"viewer_user_id" json:"viewer_user_id"`
	Username     string             `db:"username" json:"username"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ID           pgtype.UUID        `db:"id" json:"id"`
	LimitCount   int32              `db:"limit_count" json:"limit_count"`
}

type ListProfileMomentsByUsernameRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PostID           pgtype.UUID        `db:"post_id" json:"post_id"`
	PostCaption      *string            `db:"post_caption" json:"post_caption"`
	MediaObjectID    pgtype.UUID        `db:"media_object_id" json:"media_object_id"`
	AuthorAppUserID  pgtype.UUID        `db:"author_app_user_id" json:"author_app_user_id"`
	UploadGroupID    pgtype.UUID        `db:"upload_group_id" json:"upload_group_id"`
	DiveSiteID       pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Type             string             `db:"type" json:"type"`
	StorageKey       string             `db:"storage_key" json:"storage_key"`
	MimeType         string             `db:"mime_type" json:"mime_type"`
	Width            int32              `db:"width" json:"width"`
	Height           int32              `db:"height" json:"height"`
	DurationMs       *int32             `db:"duration_ms" json:"duration_ms"`
	Caption          *string            `db:"caption" json:"caption"`
	SortOrder        int32              `db:"sort_order" json:"sort_order"`
	Status           string             `db:"status" json:"status"`
	Provider         string             `db:"provider" json:"provider"`
	StreamUid        *string            `db:"stream_uid" json:"stream_uid"`
	PlaybackUid      *string            `db:"playback_uid" json:"playback_uid"`
	PlaybackUrl      *string            `db:"playback_url" json:"playback_url"`
	ThumbnailUrl     *string            `db:"thumbnail_url" json:"thumbnail_url"`
	PreviewUrl       *string            `db:"preview_url" json:"preview_url"`
	AspectRatio      pgtype.Numeric     `db:"aspect_ratio" json:"aspect_ratio"`
	HasAudio         *bool              `db:"has_audio" json:"has_audio"`
	ProcessingStatus string             `db:"processing_status" json:"processing_status"`
	ModerationStatus string             `db:"moderation_status" json:"moderation_status"`
	UploadExpiresAt  pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	ReadyAt          pgtype.Timestamptz `db:"ready_at" json:"ready_at"`
	FailedReason     *string            `db:"failed_reason" json:"failed_reason"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DiveSiteSlug     string             `db:"dive_site_slug" json:"dive_site_slug"`
	DiveSiteName     string             `db:"dive_site_name" json:"dive_site_name"`
	DiveSiteArea     string             `db:"dive_site_area" json:"dive_site_area"`
	LikeCount        int64              `db:"like_count" json:"like_count"`
	CommentCount     int64              `db:"comment_count" json:"comment_count"`
	ViewerHasLiked   bool               `db:"viewer_has_liked" json:"viewer_has_liked"`
	ViewerHasSaved   bool               `db:"viewer_has_saved" json:"viewer_has_saved"`
}

func (q *Queries) ListProfileMomentsByUsername(ctx context.Context, arg ListProfileMomentsByUsernameParams) ([]ListProfileMomentsByUsernameRow, error) {
	rows, err := q.db.Query(ctx, listProfileMomentsByUsername,
		arg.ViewerUserID,
		arg.Username,
		arg.CreatedAt,
		arg.ID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileMomentsByUsernameRow{}
	for rows.Next() {
		var i ListProfileMomentsByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PostCaption,
			&i.MediaObjectID,
			&i.AuthorAppUserID,
			&i.UploadGroupID,
			&i.DiveSiteID,
			&i.Type,
			&i.StorageKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.Caption,
			&i.SortOrder,
			&i.Status,
			&i.Provider,
			&i.StreamUid,
			&i.PlaybackUid,
			&i.PlaybackUrl,
			&i.ThumbnailUrl,
			&i.PreviewUrl,
			&i.AspectRatio,
			&i.HasAudio,
			&i.ProcessingStatus,
			&i.ModerationStatus,
			&i.UploadExpiresAt,
			&i.ReadyAt,
			&i.FailedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DiveSiteSlug,
			&i.DiveSiteName,
			&i.DiveSiteArea,
			&i.LikeCount,
			&i.CommentCount,
			&i.ViewerHasLiked,
			&i.ViewerHasSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpiredMomentUploadsFailed = `-- name: MarkExpiredMomentUploadsFailed :execrows
UPDATE media_items
SET processing_status = 'failed',
    status = 'hidden',
    failed_reason = $2,
    updated_at = NOW()
WHERE type = 'video'
  AND provider = 'cloudflare_stream'
  AND processing_status IN ('upload_requested', 'uploading', 'uploaded', 'processing')
  AND upload_expires_at IS NOT NULL
  AND upload_expires_at < $1
  AND deleted_at IS NULL
`

type MarkExpiredMomentUploadsFailedParams struct {
	UploadExpiresAt pgtype.Timestamptz `db:"upload_expires_at" json:"upload_expires_at"`
	FailedReason    *string            `db:"failed_reason" json:"failed_reason"`
}

func (q *Queries) MarkExpiredMomentUploadsFailed(ctx context.Context, arg MarkExpiredMomentUploadsFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markExpiredMomentUploadsFailed, arg.UploadExpiresAt, arg.FailedReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markMomentFailed = `-- name: MarkMomentFailed :one
UPDATE media_items
SET processing_status = 'failed',
    status = 'hidden',
    failed_reason = $2,
    updated_at = NOW()
WHERE stream_uid = $1
  AND type = 'video'
  AND provider = 'cloudflare_stream'
  AND processing_status <> 'ready'
  AND deleted_at IS NULL
RETURNING
  id, post_id, media_object_id, author_app_user_id, upload_group_id, dive_site_id,
  type, storage_key, mime_type, width, height, duration_ms, caption, sort_order,
  status, provider, stream_uid, playback_uid, playback_url, thumbnail_url,
  preview_url, aspect_ratio, has_audio, processing_status, moderation_status,
  upload_expires_at, ready_at, failed_reason, created_at, updated_at, deleted_at
`

type MarkMomentFailedParams struct {
	StreamUid    *string `db:"stream_uid" json:"stream_uid"`
	FailedReason *string `db:"failed_reason" json:"failed_reason"`
}

func (q *Queries) MarkMomentFailed(ctx context.Context, arg MarkMomentFailedParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, markMomentFailed, arg.StreamUid, arg.FailedReason)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaObjectID,
		&i.AuthorAppUserID,
		&i.UploadGroupID,
		&i.DiveSiteID,
		&i.Type,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Caption,
		&i.SortOrder,
		&i.Status,
		&i.Provider,
		&i.StreamUid,
		&i.PlaybackUid,
		&i.PlaybackUrl,
		&i.ThumbnailUrl,
		&i.PreviewUrl,
		&i.AspectRatio,
		&i.HasAudio,
		&i.ProcessingStatus,
		&i.ModerationStatus,
		&i.UploadExpiresAt,
		&i.ReadyAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markMomentReady = `-- name: MarkMomentReady :one
UPDATE media_items
SET processing_status = 'ready',
    status = 'active',
    width = GREATEST($2, 1),
    height = GREATEST($3, 1),
    duration_ms = $4,
    playback_uid = COALESCE(NULLIF($5, ''), playback_uid),
    playback_url = COALESCE(NULLIF($6, ''), playback_url),
    thumbnail_url = COALESCE(NULLIF($7, ''), thumbnail_url),
    preview_url = COALESCE(NULLIF($8, ''), preview_url),
    aspect_ratio = CASE WHEN GREATEST($3, 1) > 0 THEN GREATEST($2, 1)::numeric / GREATEST($3, 1)::numeric ELSE aspect_ratio END,
    has_audio = $9,
    ready_at = COALESCE(ready_at, NOW()),
    failed_reason = NULL,
    updated_at = NOW()
WHERE stream_uid = $1
  AND type = 'video'
  AND provider = 'cloudflare_stream'
  AND processing_status <> 'rejected'
  AND deleted_at IS NULL
RETURNING
  id, post_id, media_object_id, author_app_user_id, upload_group_id, dive_site_id,
  type, storage_key, mime_type, width, height, duration_ms, caption, sort_order,
  status, provider, stream_uid, playback_uid, playback_url, thumbnail_url,
  preview_url, aspect_ratio, has_audio, processing_status, moderation_status,
  upload_expires_at, ready_at, failed_reason, created_at, updated_at, deleted_at
`

type MarkMomentReadyParams struct {
	StreamUid  *string     `db:"stream_uid" json:"stream_uid"`
	Width      int32       `db:"width" json:"width"`
	Height     int32       `db:"height" json:"height"`
	DurationMs *int32      `db:"duration_ms" json:"duration_ms"`
	Column5    interface{} `db:"column_5" json:"column_5"`
	Column6    interface{} `db:"column_6" json:"column_6"`
	Column7    interface{} `db:"column_7" json:"column_7"`
	Column8    interface{} `db:"column_8" json:"column_8"`
	HasAudio   *bool       `db:"has_audio" json:"has_audio"`
}

func (q *Queries) MarkMomentReady(ctx context.Context, arg MarkMomentReadyParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, markMomentReady,
		arg.StreamUid,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.HasAudio,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaObjectID,
		&i.AuthorAppUserID,
		&i.UploadGroupID,
		&i.DiveSiteID,
		&i.Type,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Caption,
		&i.SortOrder,
		&i.Status,
		&i.Provider,
		&i.StreamUid,
		&i.PlaybackUid,
		&i.PlaybackUrl,
		&i.ThumbnailUrl,
		&i.PreviewUrl,
		&i.AspectRatio,
		&i.HasAudio,
		&i.ProcessingStatus,
		&i.ModerationStatus,
		&i.UploadExpiresAt,
		&i.ReadyAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markMomentUploaded = `-- name: MarkMomentUploaded :one
UPDATE media_items
SET processing_status = 'processing',
    status = 'hidden',
    updated_at = NOW()
WHERE post_id = $1
  AND author_app_user_id = $2
  AND type = 'video'
  AND provider = 'cloudflare_stream'
  AND deleted_at IS NULL
RETURNING
  id, post_id, media_object_id, author_app_user_id, upload_group_id, dive_site_id,
  type, storage_key, mime_type, width, height, duration_ms, caption, sort_order,
  status, provider, stream_uid, playback_uid, playback_url, thumbnail_url,
  preview_url, aspect_ratio, has_audio, processing_status, moderation_status,
  upload_expires_at, ready_at, failed_reason, created_at, updated_at, deleted_at
`

type MarkMomentUploadedParams struct {
	PostID          pgtype.UUID `db:"post_id" json:"post_id"`
	AuthorAppUserID pgtype.UUID `db:"author_app_user_id" json:"author_app_user_id"`
}

func (q *Queries) MarkMomentUploaded(ctx context.Context, arg MarkMomentUploadedParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, markMomentUploaded, arg.PostID, arg.AuthorAppUserID)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaObjectID,
		&i.AuthorAppUserID,
		&i.UploadGroupID,
		&i.DiveSiteID,
		&i.Type,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Caption,
		&i.SortOrder,
		&i.Status,
		&i.Provider,
		&i.StreamUid,
		&i.PlaybackUid,
		&i.PlaybackUrl,
		&i.ThumbnailUrl,
		&i.PreviewUrl,
		&i.AspectRatio,
		&i.HasAudio,
		&i.ProcessingStatus,
		&i.ModerationStatus,
		&i.UploadExpiresAt,
		&i.ReadyAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const saveMediaPost = `-- name: SaveMediaPost :exec
INSERT INTO media_post_saves (media_post_id, user_id)
VALUES ($1, $2)
ON CONFLICT (media_post_id, user_id) DO NOTHING
`

type SaveMediaPostParams struct {
	MediaPostID pgtype.UUID `db:"media_post_id" json:"media_post_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) SaveMediaPost(ctx context.Context, arg SaveMediaPostParams) error {
	_, err := q.db.Exec(ctx, saveMediaPost, arg.MediaPostID, arg.UserID)
	return err
}

const softDeleteMediaPostComment = `-- name: SoftDeleteMediaPostComment :exec
UPDATE media_post_comments
SET deleted_at = NOW(),
    deleted_by_user_id = $3,
    updated_at = NOW()
WHERE id = $1
  AND media_post_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteMediaPostCommentParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	MediaPostID     pgtype.UUID `db:"media_post_id" json:"media_post_id"`
	DeletedByUserID pgtype.UUID `db:"deleted_by_user_id" json:"deleted_by_user_id"`
}

func (q *Queries) SoftDeleteMediaPostComment(ctx context.Context, arg SoftDeleteMediaPostCommentParams) error {
	_, err := q.db.Exec(ctx, softDeleteMediaPostComment, arg.ID, arg.MediaPostID, arg.DeletedByUserID)
	return err
}

const unlikeMediaPost = `-- name: UnlikeMediaPost :exec
DELETE FROM media_post_likes
WHERE media_post_id = $1
  AND user_id = $2
`

type UnlikeMediaPostParams struct {
	MediaPostID pgtype.UUID `db:"media_post_id" json:"media_post_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UnlikeMediaPost(ctx context.Context, arg UnlikeMediaPostParams) error {
	_, err := q.db.Exec(ctx, unlikeMediaPost, arg.MediaPostID, arg.UserID)
	return err
}

const unlikeMediaPostComment = `-- name: UnlikeMediaPostComment :exec
DELETE FROM media_post_comment_likes
WHERE comment_id = $1
  AND user_id = $2
`

type UnlikeMediaPostCommentParams struct {
	CommentID pgtype.UUID `db:"comment_id" json:"comment_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UnlikeMediaPostComment(ctx context.Context, arg UnlikeMediaPostCommentParams) error {
	_, err := q.db.Exec(ctx, unlikeMediaPostComment, arg.CommentID, arg.UserID)
	return err
}

const unsaveMediaPost = `-- name: UnsaveMediaPost :exec
DELETE FROM media_post_saves
WHERE media_post_id = $1
  AND user_id = $2
`

type UnsaveMediaPostParams struct {
	MediaPostID pgtype.UUID `db:"media_post_id" json:"media_post_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UnsaveMediaPost(ctx context.Context, arg UnsaveMediaPostParams) error {
	_, err := q.db.Exec(ctx, unsaveMediaPost, arg.MediaPostID, arg.UserID)
	return err
}

const updateMediaState = `-- name: UpdateMediaState :one
UPDATE media_objects
SET state = $2
WHERE id = $1
RETURNING id, owner_app_user_id, context_type, context_id, object_key, mime_type, size_bytes, width, height, state, created_at
`

type UpdateMediaStateParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	State string      `db:"state" json:"state"`
}

func (q *Queries) UpdateMediaState(ctx context.Context, arg UpdateMediaStateParams) (MediaObject, error) {
	row := q.db.QueryRow(ctx, updateMediaState, arg.ID, arg.State)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerAppUserID,
		&i.ContextType,
		&i.ContextID,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}
