// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: explore.sql

package exploreqlc

import (
	"context"
)

const listDiveSites = `-- name: ListDiveSites :many
SELECT id, name, location, moderation_state, created_at
FROM dive_sites
WHERE moderation_state = 'approved'
  AND ($1 = '' OR name ILIKE '%' || $1 || '%' OR location ILIKE '%' || $1 || '%')
ORDER BY name ASC
LIMIT 100
`

func (q *Queries) ListDiveSites(ctx context.Context, dollar_1 interface{}) ([]DiveSite, error) {
	rows, err := q.db.Query(ctx, listDiveSites, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiveSite{}
	for rows.Next() {
		var i DiveSite
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.ModerationState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
