// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journey.sql

package divejourneysqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createManualJourneyEntry = `-- name: CreateManualJourneyEntry :one
INSERT INTO journey_entries (
  user_id,
  type,
  title,
  body,
  dive_site_id,
  visibility,
  occurred_at
)
VALUES (
  $1,
  'custom',
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING
  id,
  user_id,
  type,
  title,
  body,
  dive_site_id,
  source_type,
  source_id,
  cover_media_id,
  visibility,
  state,
  occurred_at,
  hidden_at,
  deleted_at,
  created_at,
  updated_at
`

type CreateManualJourneyEntryParams struct {
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Title      string             `db:"title" json:"title"`
	Body       string             `db:"body" json:"body"`
	DiveSiteID pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Visibility string             `db:"visibility" json:"visibility"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateManualJourneyEntry(ctx context.Context, arg CreateManualJourneyEntryParams) (JourneyEntry, error) {
	row := q.db.QueryRow(ctx, createManualJourneyEntry,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.DiveSiteID,
		arg.Visibility,
		arg.OccurredAt,
	)
	var i JourneyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.DiveSiteID,
		&i.SourceType,
		&i.SourceID,
		&i.CoverMediaID,
		&i.Visibility,
		&i.State,
		&i.OccurredAt,
		&i.HiddenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJourneyEntryByID = `-- name: GetJourneyEntryByID :one
SELECT
  id,
  user_id,
  type,
  title,
  body,
  dive_site_id,
  source_type,
  source_id,
  cover_media_id,
  visibility,
  state,
  occurred_at,
  hidden_at,
  deleted_at,
  created_at,
  updated_at
FROM journey_entries
WHERE id = $1
`

func (q *Queries) GetJourneyEntryByID(ctx context.Context, id pgtype.UUID) (JourneyEntry, error) {
	row := q.db.QueryRow(ctx, getJourneyEntryByID, id)
	var i JourneyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.DiveSiteID,
		&i.SourceType,
		&i.SourceID,
		&i.CoverMediaID,
		&i.Visibility,
		&i.State,
		&i.OccurredAt,
		&i.HiddenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJourneyOwnerByUsername = `-- name: GetJourneyOwnerByUsername :one
SELECT
  u.id,
  COALESCE(NULLIF($1, '')::uuid = u.id, false)::boolean AS viewer_is_self,
  COALESCE((
    SELECT EXISTS (
      SELECT 1
      FROM saved_users su
      WHERE su.viewer_app_user_id = NULLIF($1, '')::uuid
        AND su.saved_app_user_id = u.id
    )
  ), false)::boolean AS viewer_follows,
  COALESCE((
    SELECT EXISTS (
      SELECT 1
      FROM user_blocks ub
      WHERE (
          ub.blocker_app_user_id = NULLIF($1, '')::uuid
          AND ub.blocked_app_user_id = u.id
        )
        OR (
          ub.blocker_app_user_id = u.id
          AND ub.blocked_app_user_id = NULLIF($1, '')::uuid
        )
    )
  ), false)::boolean AS blocked
FROM users u
WHERE lower(u.username) = lower($2)
  AND u.account_status = 'active'
LIMIT 1
`

type GetJourneyOwnerByUsernameParams struct {
	ViewerUserID interface{} `db:"viewer_user_id" json:"viewer_user_id"`
	Username     string      `db:"username" json:"username"`
}

type GetJourneyOwnerByUsernameRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	ViewerIsSelf  bool        `db:"viewer_is_self" json:"viewer_is_self"`
	ViewerFollows bool        `db:"viewer_follows" json:"viewer_follows"`
	Blocked       bool        `db:"blocked" json:"blocked"`
}

func (q *Queries) GetJourneyOwnerByUsername(ctx context.Context, arg GetJourneyOwnerByUsernameParams) (GetJourneyOwnerByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getJourneyOwnerByUsername, arg.ViewerUserID, arg.Username)
	var i GetJourneyOwnerByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.ViewerIsSelf,
		&i.ViewerFollows,
		&i.Blocked,
	)
	return i, err
}

const hideGeneratedJourneyEntry = `-- name: HideGeneratedJourneyEntry :execrows
UPDATE journey_entries
SET
  state = 'hidden',
  hidden_at = NOW(),
  updated_at = NOW()
WHERE user_id = $1
  AND type = $2
  AND source_type = $3
  AND source_id = $4
  AND source_type IS NOT NULL
  AND source_id IS NOT NULL
  AND state = 'active'
`

type HideGeneratedJourneyEntryParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	Type       string      `db:"type" json:"type"`
	SourceType *string     `db:"source_type" json:"source_type"`
	SourceID   *string     `db:"source_id" json:"source_id"`
}

func (q *Queries) HideGeneratedJourneyEntry(ctx context.Context, arg HideGeneratedJourneyEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, hideGeneratedJourneyEntry,
		arg.UserID,
		arg.Type,
		arg.SourceType,
		arg.SourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listJourneyEntriesForProfile = `-- name: ListJourneyEntriesForProfile :many
SELECT
  id,
  user_id,
  type,
  title,
  body,
  dive_site_id,
  source_type,
  source_id,
  cover_media_id,
  visibility,
  state,
  occurred_at,
  hidden_at,
  deleted_at,
  created_at,
  updated_at
FROM journey_entries
WHERE user_id = $1
  AND state = 'active'
  AND (
    visibility = 'public'
    OR ($2::boolean AND visibility = 'private')
    OR (($2::boolean OR $3::boolean) AND visibility = 'followers')
  )
ORDER BY occurred_at DESC, id DESC
LIMIT $4
`

type ListJourneyEntriesForProfileParams struct {
	TargetUserID  pgtype.UUID `db:"target_user_id" json:"target_user_id"`
	ViewerIsSelf  bool        `db:"viewer_is_self" json:"viewer_is_self"`
	ViewerFollows bool        `db:"viewer_follows" json:"viewer_follows"`
	ResultLimit   int32       `db:"result_limit" json:"result_limit"`
}

func (q *Queries) ListJourneyEntriesForProfile(ctx context.Context, arg ListJourneyEntriesForProfileParams) ([]JourneyEntry, error) {
	rows, err := q.db.Query(ctx, listJourneyEntriesForProfile,
		arg.TargetUserID,
		arg.ViewerIsSelf,
		arg.ViewerFollows,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JourneyEntry{}
	for rows.Next() {
		var i JourneyEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.DiveSiteID,
			&i.SourceType,
			&i.SourceID,
			&i.CoverMediaID,
			&i.Visibility,
			&i.State,
			&i.OccurredAt,
			&i.HiddenAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteManualJourneyEntry = `-- name: SoftDeleteManualJourneyEntry :execrows
UPDATE journey_entries
SET
  state = 'deleted',
  deleted_at = NOW(),
  updated_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND type = 'custom'
  AND source_type IS NULL
  AND source_id IS NULL
  AND state = 'active'
`

type SoftDeleteManualJourneyEntryParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) SoftDeleteManualJourneyEntry(ctx context.Context, arg SoftDeleteManualJourneyEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteManualJourneyEntry, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateManualJourneyEntry = `-- name: UpdateManualJourneyEntry :one
UPDATE journey_entries
SET
  title = $3,
  body = $4,
  dive_site_id = $5,
  visibility = $6,
  occurred_at = $7,
  updated_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND type = 'custom'
  AND source_type IS NULL
  AND source_id IS NULL
  AND state = 'active'
RETURNING
  id,
  user_id,
  type,
  title,
  body,
  dive_site_id,
  source_type,
  source_id,
  cover_media_id,
  visibility,
  state,
  occurred_at,
  hidden_at,
  deleted_at,
  created_at,
  updated_at
`

type UpdateManualJourneyEntryParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Title      string             `db:"title" json:"title"`
	Body       string             `db:"body" json:"body"`
	DiveSiteID pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	Visibility string             `db:"visibility" json:"visibility"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) UpdateManualJourneyEntry(ctx context.Context, arg UpdateManualJourneyEntryParams) (JourneyEntry, error) {
	row := q.db.QueryRow(ctx, updateManualJourneyEntry,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.DiveSiteID,
		arg.Visibility,
		arg.OccurredAt,
	)
	var i JourneyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.DiveSiteID,
		&i.SourceType,
		&i.SourceID,
		&i.CoverMediaID,
		&i.Visibility,
		&i.State,
		&i.OccurredAt,
		&i.HiddenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGeneratedJourneyEntry = `-- name: UpsertGeneratedJourneyEntry :one
INSERT INTO journey_entries (
  user_id,
  type,
  title,
  body,
  dive_site_id,
  source_type,
  source_id,
  visibility,
  occurred_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
ON CONFLICT (user_id, source_type, source_id, type)
  WHERE source_type IS NOT NULL AND source_id IS NOT NULL
DO UPDATE
SET
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  dive_site_id = EXCLUDED.dive_site_id,
  visibility = EXCLUDED.visibility,
  occurred_at = EXCLUDED.occurred_at,
  state = 'active',
  hidden_at = NULL,
  deleted_at = NULL,
  updated_at = NOW()
RETURNING
  id,
  user_id,
  type,
  title,
  body,
  dive_site_id,
  source_type,
  source_id,
  cover_media_id,
  visibility,
  state,
  occurred_at,
  hidden_at,
  deleted_at,
  created_at,
  updated_at
`

type UpsertGeneratedJourneyEntryParams struct {
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Type       string             `db:"type" json:"type"`
	Title      string             `db:"title" json:"title"`
	Body       string             `db:"body" json:"body"`
	DiveSiteID pgtype.UUID        `db:"dive_site_id" json:"dive_site_id"`
	SourceType *string            `db:"source_type" json:"source_type"`
	SourceID   *string            `db:"source_id" json:"source_id"`
	Visibility string             `db:"visibility" json:"visibility"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) UpsertGeneratedJourneyEntry(ctx context.Context, arg UpsertGeneratedJourneyEntryParams) (JourneyEntry, error) {
	row := q.db.QueryRow(ctx, upsertGeneratedJourneyEntry,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.DiveSiteID,
		arg.SourceType,
		arg.SourceID,
		arg.Visibility,
		arg.OccurredAt,
	)
	var i JourneyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.DiveSiteID,
		&i.SourceType,
		&i.SourceID,
		&i.CoverMediaID,
		&i.Visibility,
		&i.State,
		&i.OccurredAt,
		&i.HiddenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
