// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passport.sql

package divepassportqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPassportSettings = `-- name: GetPassportSettings :one
SELECT
  user_id,
  show_map,
  show_badges,
  show_journey,
  show_memories,
  featured_badge_ids,
  created_at,
  updated_at
FROM passport_settings
WHERE user_id = $1
`

func (q *Queries) GetPassportSettings(ctx context.Context, userID pgtype.UUID) (PassportSetting, error) {
	row := q.db.QueryRow(ctx, getPassportSettings, userID)
	var i PassportSetting
	err := row.Scan(
		&i.UserID,
		&i.ShowMap,
		&i.ShowBadges,
		&i.ShowJourney,
		&i.ShowMemories,
		&i.FeaturedBadgeIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPassportSettings = `-- name: UpsertPassportSettings :one
INSERT INTO passport_settings (
  user_id,
  show_map,
  show_badges,
  show_journey,
  show_memories,
  featured_badge_ids
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (user_id) DO UPDATE
SET
  show_map = EXCLUDED.show_map,
  show_badges = EXCLUDED.show_badges,
  show_journey = EXCLUDED.show_journey,
  show_memories = EXCLUDED.show_memories,
  featured_badge_ids = EXCLUDED.featured_badge_ids,
  updated_at = NOW()
RETURNING
  user_id,
  show_map,
  show_badges,
  show_journey,
  show_memories,
  featured_badge_ids,
  created_at,
  updated_at
`

type UpsertPassportSettingsParams struct {
	UserID           pgtype.UUID   `db:"user_id" json:"user_id"`
	ShowMap          bool          `db:"show_map" json:"show_map"`
	ShowBadges       bool          `db:"show_badges" json:"show_badges"`
	ShowJourney      bool          `db:"show_journey" json:"show_journey"`
	ShowMemories     bool          `db:"show_memories" json:"show_memories"`
	FeaturedBadgeIds []pgtype.UUID `db:"featured_badge_ids" json:"featured_badge_ids"`
}

func (q *Queries) UpsertPassportSettings(ctx context.Context, arg UpsertPassportSettingsParams) (PassportSetting, error) {
	row := q.db.QueryRow(ctx, upsertPassportSettings,
		arg.UserID,
		arg.ShowMap,
		arg.ShowBadges,
		arg.ShowJourney,
		arg.ShowMemories,
		arg.FeaturedBadgeIds,
	)
	var i PassportSetting
	err := row.Scan(
		&i.UserID,
		&i.ShowMap,
		&i.ShowBadges,
		&i.ShowJourney,
		&i.ShowMemories,
		&i.FeaturedBadgeIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
