// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chika.sql

package chikaqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO chika_posts (thread_id, author_user_id, pseudonym, content)
VALUES ($1, $2, $3, $4)
RETURNING id, thread_id, author_user_id, pseudonym, content, created_at
`

type CreatePostParams struct {
	ThreadID     pgtype.UUID `db:"thread_id" json:"thread_id"`
	AuthorUserID pgtype.UUID `db:"author_user_id" json:"author_user_id"`
	Pseudonym    string      `db:"pseudonym" json:"pseudonym"`
	Content      string      `db:"content" json:"content"`
}

type CreatePostRow struct {
	ID           int64              `db:"id" json:"id"`
	ThreadID     pgtype.UUID        `db:"thread_id" json:"thread_id"`
	AuthorUserID pgtype.UUID        `db:"author_user_id" json:"author_user_id"`
	Pseudonym    string             `db:"pseudonym" json:"pseudonym"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ThreadID,
		arg.AuthorUserID,
		arg.Pseudonym,
		arg.Content,
	)
	var i CreatePostRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.AuthorUserID,
		&i.Pseudonym,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const ensureThread = `-- name: EnsureThread :exec
INSERT INTO chika_threads (id, title)
VALUES ($1, '')
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureThread(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureThread, id)
	return err
}

const pseudonymEnabled = `-- name: PseudonymEnabled :one
SELECT pseudonymous_enabled
FROM profiles
WHERE user_id = $1
`

func (q *Queries) PseudonymEnabled(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, pseudonymEnabled, userID)
	var pseudonymous_enabled bool
	err := row.Scan(&pseudonymous_enabled)
	return pseudonymous_enabled, err
}
