name: Deploy FPH

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    secrets: inherit
