name: Legacy AWS Deploy (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    secrets: inherit
