// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package usersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, bio)
VALUES ($1, $2)
RETURNING user_id, bio, avatar_url, pseudonymous_enabled, created_at, updated_at
`

type CreateProfileParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Bio    string      `db:"bio" json:"bio"`
}

type CreateProfileRow struct {
	UserID              pgtype.UUID        `db:"user_id" json:"user_id"`
	Bio                 string             `db:"bio" json:"bio"`
	AvatarUrl           string             `db:"avatar_url" json:"avatar_url"`
	PseudonymousEnabled bool               `db:"pseudonymous_enabled" json:"pseudonymous_enabled"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (CreateProfileRow, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.Bio)
	var i CreateProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Bio,
		&i.AvatarUrl,
		&i.PseudonymousEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, display_name)
VALUES ($1, $2, $3)
RETURNING id, username, display_name, created_at
`

type CreateUserParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Username    string      `db:"username" json:"username"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Username    string             `db:"username" json:"username"`
	DisplayName string             `db:"display_name" json:"display_name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username, arg.DisplayName)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  u.id,
  u.username,
  u.display_name,
  p.bio,
  p.avatar_url,
  p.pseudonymous_enabled,
  u.created_at
FROM users u
JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Username            string             `db:"username" json:"username"`
	DisplayName         string             `db:"display_name" json:"display_name"`
	Bio                 string             `db:"bio" json:"bio"`
	AvatarUrl           string             `db:"avatar_url" json:"avatar_url"`
	PseudonymousEnabled bool               `db:"pseudonymous_enabled" json:"pseudonymous_enabled"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.PseudonymousEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const saveUser = `-- name: SaveUser :exec
INSERT INTO saved_users (viewer_app_user_id, saved_app_user_id)
VALUES ($1, $2)
ON CONFLICT (viewer_app_user_id, saved_app_user_id) DO NOTHING
`

type SaveUserParams struct {
	ViewerAppUserID pgtype.UUID `db:"viewer_app_user_id" json:"viewer_app_user_id"`
	SavedAppUserID  pgtype.UUID `db:"saved_app_user_id" json:"saved_app_user_id"`
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.Exec(ctx, saveUser, arg.ViewerAppUserID, arg.SavedAppUserID)
	return err
}

const unsaveUser = `-- name: UnsaveUser :exec
DELETE FROM saved_users
WHERE viewer_app_user_id = $1
  AND saved_app_user_id = $2
`

type UnsaveUserParams struct {
	ViewerAppUserID pgtype.UUID `db:"viewer_app_user_id" json:"viewer_app_user_id"`
	SavedAppUserID  pgtype.UUID `db:"saved_app_user_id" json:"saved_app_user_id"`
}

func (q *Queries) UnsaveUser(ctx context.Context, arg UnsaveUserParams) error {
	_, err := q.db.Exec(ctx, unsaveUser, arg.ViewerAppUserID, arg.SavedAppUserID)
	return err
}
